### ISSUE TITLE
Build Continuous Integrate workflow

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#100]
Build Continuous Integrate workflow:

   * [x] Systematic coding style check (using `pylint`?)
   * [x] Unit tests
   * [x] Travis-CI

**Comment by Grazfather** [comment]
:100:

**Comment by hugsy** [comment]
@Grazfather 
 ![](https://i.imgflip.com/1hsbbn.jpg)

**Comment by Grazfather** [comment]
lol. A lot of them are PRs!

**Comment by hugsy** [comment]
`tests/test-runner.py` can be used a `pre-commit` Git hook.

**Comment by hugsy** [comment]
Commit 06fb889 creates the `pylint` style for systematic code check (`pre-push`)

**Comment by Grazfather** [comment]
Is that rc built based on the list in #115?

**Comment by hugsy** [comment]
Nope, just a first gist I created a few weeks ago. What specific params were you passing to `pylint`?

**Comment by Grazfather** [comment]
Nothing yet, but I went through the report and looked to see which were bullshit. You can see my comments in the table in that issue.

**Comment by hugsy** [comment]
Yep, I saw that. This pylintrc will be updated progressively as well. And I need to push more tests as well... Work is not over :laughing:

**Comment by hugsy** [comment]
About 2 months with this, and I believe this is working well (although more tests will keep being added over time).

Closing this issue!
