### ISSUE TITLE
Make `reset_architecture` accessible via command

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#1002]
### Type of feature request

Additional API

### Summary Description

We tell people to `pi reset_architecture("bla")`.

Let's make a command that makes it easier

### Implementation idea/suggestion

`gef arch` maybe?

* Let them list installed architectures
* Let them set it
* Show what gef thinks the arch is, and why (e.g. from ELF or whatever)

**Comment by Grazfather** [comment]
Can work on this shortly

**Comment by hugsy** [comment]
Assigned to you so stalebot doesn't touch it
