### ISSUE TITLE
how to use gef-remote command when debuging by gdb-multiarch, and target is localhost:1234

### ISSUE THREAD

**Issue by bb33bb** [hugsy/gef#1014]
### GEF+GDB version

```shell
how to use gef-remote command when debuging by gdb-multiarch, and target is localhost:1234

i tried many times and always not successfull .Plz is there any examples?
```

### Operating System

arch linux

### Describe the issue you encountered

connect to gdb

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [ ] X86
- [ ] X64
- [ ] ARM
- [X] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Provide a step-by-step to reproduce your issue.

### Minimalist test case

Use this field for a minimal code to compile and spot the issue:
```c
// compile with gcc -fPIE -pic -o my_issue.out my_issue.c
int main(){ return 0; }
```
You can also provide a Dockerfile if you prefer

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by hugsy** [comment]
This is not a GEF, closing. If you want advices on how to use it, read the docs and/or go to the Discord.
