### ISSUE TITLE
any possible to add vmmap to show kernel memory in qemu?

### ISSUE THREAD

**Issue by bb33bb** [hugsy/gef#1038]
### Type of feature request

Additional API

### Summary Description

when using gef to debug linux /android kernel in qemu
vmmap can not show kernel memory as list ,just like pwndbg did

### Implementation idea/suggestion

add new feature

**Comment by ValekoZ** [comment]
Maybe it would be nice to check how *Qemu-system cooperation* is implemented in [bata's fork](https://github.com/bata24/gef#qemu-system-cooperation---general) ? It adds a lot of improvements for kernel debugging, but it is annoying to have to change gef's version when doing userland or kernel land

We could just add basic features to gef's core and then add plugins to gef extra for more specific features ?

**Comment by bb33bb** [comment]
Ok 
And it's true that pwndbg is really heavy

**Comment by hugsy** [comment]
> We could just add basic features to gef's core and then add plugins to gef extra for more specific features ?

Absolutely, bata's gef fork is now very different from vanilla gef as it relies on a much much older version. Over the last few years, gef has been refactored and simplified to be used as a lib, so many of bata's new commands can be added quite trivially to gef-extras and I'm convinced feature-parity could be reached quickly. Improving kernel debugging has been long standing in the wishlist, but it's hard to find time 😔

**Comment by hugsy** [comment]
> And it's true that pwndbg is really heavy

It's very hard to maintain a balance 🙂 GEF itself (not extra) will always be one single file, no dependency with a strong support for usermode bins of any arch supported by gdb. pwndbg is more of a framework. There's pros and cons to both.

**Comment by hugsy** [comment]
FWIW I've now updated and publicly opened the project for [improving kernel debugging support in GEF](https://github.com/users/hugsy/projects/5/views/1).
