### ISSUE TITLE
The Gef Frame Is small

### ISSUE THREAD

**Issue by SefeinSaeed** [hugsy/gef#1077]
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/home/kali/.gef-2024.01.py): 50cab71b4a7d0c481d97e021166272a860382895
SHA256(/home/kali/.gef-2024.01.py): a11f449895f5214d7a7fa808fb7f8ba5dceb79944902d1a398ce65ec9f520444
GDB: 13.2
GDB-Python: 3.11
```

### Operating System

Kali

### Describe the issue you encountered

The Frame of Gef in the terminal is small as it gets only from the Header "[ Legend: Modified register | Code | Heap | Stack | String ]" and the command and the output doesn't appear

The solution is to make the GEF frame start from the command input

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [X] X86
- [ ] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

open any binary with gef
break at main
run
you see that the frame is reduced to the header GEF output not the output of the program itself

### Additional context?

![image](https://github.com/hugsy/gef/assets/90073839/1d81ec40-82ae-4485-a0d1-934ad13e15f0)

as you can see I minimized my terminal font size and also the issue exist

not big issue but it would enhance productivity

**Comment by hugsy** [comment]
Just set the `context.clear_context` to false, you'll see your output before the context pane

**Comment by hugsy** [comment]
No follow-up, I assume it's fixed as described above.
Closing
