### ISSUE TITLE
[Bug] AssertionError

### ISSUE THREAD

**Issue by Green360** [hugsy/gef#1078]
### GEF+GDB version

```shell
GNU gdb (Debian 13.1-3) 13.1
.gef-2024.01.py
```

### Operating System

Parrot OS 6.5.0

### Describe the issue you encountered

Error when starting gdb:

> Traceback (most recent call last):
  File "/home/parrot/.gef-2024.01.py", line 11303, in <module>
    assert site_packages_dir.is_dir()
AssertionError

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

I just installed GEF via $ bash -c "$(curl -fsSL https://gef.blah.cat/sh)" and opened gdb just to be faced with the following:

> parrot@parrot ~/$ gdb                                                                                                                       
GNU gdb (Debian 13.1-3) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/parrot/.gef-2024.01.py", line 11303, in <module>
    assert site_packages_dir.is_dir()
AssertionError
(gdb)

I use pyenv as I do not have many options with the python "error: externally-managed-environment" pip issue and PEP 668. Besides system I also have python 2.7.18 and python 3.12.2 installed.

> parrot@parrot ~/reg$ pyenv versions
> * system (set by /home/parrot/.pyenv/version)
  2.7.18
  3.12.2
  3.12.2/envs/pwntools
  pwntools --> /home/parrot/.pyenv/versions/3.12.2/envs/pwntools

**Comment by hugsy** [comment]
Note that `pyenv` support is being deprecated for gef and will soon be removed entirely.

**Comment by Green360** [comment]
@hugsy: I am sorry, I was not aware of this. I now activate pyenv only if needed and use my system python3.11 with gef and run pwntools via venv. Yesterday evening it looked like it works this way. gef seems happy and I can still use pyenv for my other use cases.

**Comment by mattzque** [comment]
is there a way to disable pyenv temporarily to make gef work? I still want pyenv for other things, having to init it every time gets a bit annoying.

```
% cat ~/.zshrc
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
% pyenv versions
* system (set by /home/user/.pyenv/version)

% gdb
GNU gdb (Debian 13.2-1) 13.2
Traceback (most recent call last):
  File "/home/user/.gdbinit-gef.py", line 11487, in <module>
    assert site_packages_dir.is_dir()
AssertionError
```

**Comment by hugsy** [comment]
@mattzque 

You can make it disappear permanently by making a PR removing the `pyenv` related code.
It was going to be done sooner or later, so you can go for it.

**Comment by mattzque** [comment]
> @mattzque
> 
> You can make it disappear permanently by making a PR removing the `pyenv` related code. It was going to be done sooner or later, so you can go for it.

works for me @ https://github.com/hugsy/gef/pull/1084
