### ISSUE TITLE
Gef doesn't allow decimal input

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#109]
```bash
[pi@grazberrypi:~]$ gdb
(gdb) p/d 100
$1 = 100
(gdb) quit
[pi@grazberrypi:~]$ vim ~/.gdbinit # Turn on gef
[pi@grazberrypi:~]$ gdb
GEF for linux ready, type `gef' to start, `gef config' to configure
42 commands loaded for GDB 7.7.1 using Python engine 2.7
[*] 7 commands could not be loaded, run `gef missing` to know why.
gef> p/d 100
$1 = 256
```

**Comment by Grazfather** [comment]
Culprit is 5bc0ebebe

**Comment by Grazfather** [comment]
```python
[pi@grazberrypi:~/code/gef]$ git co 5bc0ebebe
[pi@grazberrypi:~/code/gef]$ gdb
GEF for linux ready, type `gef' to start, `gef config' to configure
46 commands loaded for GDB 7.7.1 using Python engine 2.7
[*] 7 commands could not be loaded, run `gef missing` to know why.
gef> p/d 100
Python Exception <class 'gdb.error'> The program is not being run.:
Error occurred in Python command: The program is not being run.
gef> x/w 100
0x100:  Cannot access memory at address 0x100
gef> quit
[pi@grazberrypi:~/code/gef]$ git co 5bc0ebebe^
[pi@grazberrypi:~/code/gef]$ gdb
GEF for linux ready, type `gef' to start, `gef config' to configure
51 commands loaded for GDB 7.7.1 using Python engine 2.7
[*] 7 commands could not be loaded, run `gef missing` to know why.
gef> x/w 100
0x64:   Cannot access memory at address 0x64
```

**Comment by hugsy** [comment]
Yes I know, this is done by [this line](https://github.com/hugsy/gef/blob/master/gef.py#L6638)
```
gdb.execute("set input-radix 0x10")
￼```

Do you think it's a bad feature ?

**Comment by Grazfather** [comment]
Maybe make it configurable? I had someone ask about it because it's weird (explicit is better than implicit? :p)

I know it's annoying for me because i often use gdb to convert decimal to hex and you just can't do that with this setting

**Comment by hugsy** [comment]
All right, I will change it back. It is not much for me to just add this option in my `.gdbinit` :smile:

**Comment by Grazfather** [comment]
haha imposing your preferences on everyone. I think it's better reverted... less surprising.

**Comment by hugsy** [comment]
Done by e422ad9696517651e1a89f749b30d17cb9c84b01

**Comment by Grazfather** [comment]
Can we re-open this? e422ad9 was reverted.

I noticed that this also breaks `p/c 0x41`

**Comment by Grazfather** [comment]
Actually this is a slightly different issue. The `p/c` is for the _output_ radix.

**Comment by Grazfather** [comment]
Hm maybe we could consider this fixed with #125

**Comment by hugsy** [comment]
@Grazfather this is fixed now right ?

**Comment by Grazfather** [comment]
Yes the `output radix` setting is different. It breaks `p/c`, but i worked around that by adding `pchar`. Closing.
