### ISSUE TITLE
[Bug] vmmap command 'offset' column actually shows size

### ISSUE THREAD

**Issue by mjklbhvg** [hugsy/gef#1096]
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/home/fr/.config/gdb/gdbinit-gef.py): a069c75625fe1fe9f520e638094737b037c1a9f6
SHA256(/home/fr/.config/gdb/gdbinit-gef.py): 5499dc017dc390105601a94323ed2b87f6ea407625dadb39c5b36a85be60a975
GDB: 14.2
GDB-Python: 3.12
```

### Operating System

LSB Version:	1.0 Distributor ID:	VoidLinux Description:	Void Linux Release:	rolling Codename:	void

### Describe the issue you encountered

As the title says, the column "offset" in the vmmap output appears to actually show section size.
I am pretty sure this happened in this commit:
https://github.com/hugsy/gef/commit/c9a8b18808f06bb2e8c7fdb6de5a3dafcbfa7c56

I can reproduce with this commit, but not the commit before.

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

gdb /bin/ls
start
vmmap
```
Start              End                Offset             Perm Path
0x0000555555554000 0x0000555555558000 0x0000000000004000 r-- /usr/bin/ls
0x0000555555558000 0x000055555556e000 0x0000000000016000 r-x /usr/bin/ls
0x000055555556e000 0x0000555555577000 0x0000000000009000 r-- /usr/bin/ls
0x0000555555577000 0x0000555555579000 0x0000000000002000 r-- /usr/bin/ls
0x0000555555579000 0x000055555557a000 0x0000000000001000 rw- /usr/bin/ls
```
info proc mappings
```
process 15347
Mapped address spaces:

          Start Addr           End Addr       Size     Offset  Perms  objfile
      0x555555554000     0x555555558000     0x4000        0x0  r--p   /usr/bin/ls
      0x555555558000     0x55555556e000    0x16000     0x4000  r-xp   /usr/bin/ls
      0x55555556e000     0x555555577000     0x9000    0x1a000  r--p   /usr/bin/ls
      0x555555577000     0x555555579000     0x2000    0x23000  r--p   /usr/bin/ls
      0x555555579000     0x55555557a000     0x1000    0x25000  rw-p   /usr/bin/ls
```

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by hugsy** [comment]
Fixed by 13d1de2
