### ISSUE TITLE
[Bug] SyntaxError: unterminated triple-quoted string literal

### ISSUE THREAD

**Issue by Ahmed-Zahran-AZ** [hugsy/gef#1099]
### GEF+GDB version

```shell
GEF:2024.01 - Evergreen Response
GDB: 14.2
```

### Operating System

Windows 10 64-bit msys2 mingw subsystem

### Describe the issue you encountered

  File "<string>", line 11306
    hook = f"""
           ^
SyntaxError: unterminated triple-quoted string literal (detected at line 11310)
C:/msys64/mingw64/bin/../etc/gdbinit:11379: Error in sourced command file:
Error while executing Python code.

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [X] X86
- [ ] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Just by running gdb. I get this syntax error from gdbinit

**Comment by hugsy** [comment]
No explanation whatsoever, closing
