### ISSUE TITLE
Python Exception <class 'RuntimeError'>: No session started

### ISSUE THREAD

**Issue by bb33bb** [hugsy/gef#1104]
### GEF+GDB version

```shell
all the same version to issue 1102
```

### Describe the issue you encountered

![image](https://github.com/hugsy/gef/assets/5463104/705117da-f385-4b86-bb5c-3f3d5c464f38)

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [x] ARM64

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

Provide a step-by-step to reproduce your issue.

start qemu
gdb-multiarch \
-ex "set confirm off" \
-ex "set print pretty on" \
-ex "target remote localhost:1234" \
-ex "set auto-load safe-path /" 

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by bb33bb** [comment]
if u can not reproduce, plz wait for my several trys.

I will update it .

**Comment by bb33bb** [comment]
as u told me ,i use gef-remote

Env:
uname -a  
Linux singapore 6.9.0-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon May 13 07:01:28 UTC 2024 x86_64 GNU/Linux

gdb command:

echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
gdb-multiarch \
-ex "set confirm off" \
-ex "set print pretty on" \
-ex "gef-remote localhost 1234" \
-ex "set auto-load safe-path /" \
-ex "file /run/media/xxxxx/9e4b17d7-a9ed-4cee-90f7-e8b4e511c8c1/u22docker/kernel5.10/common/vmlinux"

0
GNU gdb (GDB) 14.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
GEF for linux ready, type `gef' to start, `gef config' to configure
88 commands loaded and 5 functions added for GDB 14.2 in 0.00ms using Python engine 3.12
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0xffff800008e0ab6c in ?? ()
[!] Command 'gef-remote' failed to execute properly, reason: No session started
Reading symbols from /run/media/


I am debuging qemu which i runing arm64 kernel
this time it is different from the last time's output
but as u can see, there maybe some thing not very ok.
any work if needed to reproduce, i will try my best
if this issue designed just as it is in the above, plz ignore it.

**Comment by bb33bb** [comment]
> I still cannot reproduce. I just re-tested it following [the docs](https://hugsy.github.io/gef/commands/gef-remote/#qemu-system) and it works as expected.

I close it now , and if find time to reproduce it. I will reopen, Thanks !!

**Comment by hurricane618** [comment]
I had the same problem as you, and then my solution was `gef-remote --qemu-user --qemu-binary vmlinux.elf 127.0.0.1 1234`. You need to add `--qemu-user --qemu-binary some.elf` to solve the problem.
