### ISSUE TITLE
Alpine dependencies

### ISSUE THREAD

**Issue by nnewram** [hugsy/gef#1105]
https://github.com/hugsy/gef/blob/18c1f7c433e320066808e31797f18dae30830982/gef.py#L11079

If installing in Alpine which does not have `file` by default you get error message:
```
Traceback (most recent call last):
  File "/root/.gef-2023.06.py", line 11070, in <module>
    reset()
  File "/root/.gef-2023.06.py", line 191, in reset
    gef.setup()
  File "/root/.gef-2023.06.py", line 11001, in setup
    self.reinitialize_managers()
  File "/root/.gef-2023.06.py", line 10996, in reinitialize_managers
    self.session = GefSessionManager()
                   ^^^^^^^^^^^^^^^^^^^
  File "/root/.gef-2023.06.py", line 10602, in __init__
    self.constants[constant] = which(constant)
                               ^^^^^^^^^^^^^^^
  File "/root/.gef-2023.06.py", line 1843, in which
    raise FileNotFoundError(f"Missing file `{program}`")
FileNotFoundError: Missing file `file`
```

Which is a bit cryptic. For Alpine users: in order to use gef you need `file`, e.g. `apk add file`

Might be nice with a better error message here?

**Comment by hugsy** [comment]
Hi,
> Might be nice with a better error message here?

I'm not sure what "better" means. It clearly states the fact a required binary dependency cannot be found. [This is all described in the docs](https://hugsy.github.io/gef/install/#prerequisites). GEF is a Python tool, agnostic of all Linux variants and we cannot (and aren't going to) spend time making it specific to each distro specificities if that's the kind of improvement you were hoping.

If it's not, please explain how.

**Comment by Grazfather** [comment]
I don't think we should add special handling for `file`. I am with hugsy. There has to be some base set of utilities that are needed. I think `FileNotFoundError: Missing file file` is plenty clear.
