### ISSUE TITLE
[Bug] ksymaddr unimplemented?

### ISSUE THREAD

**Issue by k4lizen** [hugsy/gef#1140]
### GEF+GDB version

```shell
GEF: rev:115137cc05d6c90f589f0840009b116c633cb48a (Git - clean)
SHA256(---/hugsygef/gef.py): e4a7853e84d87a88a469bb8d2c9f863fe211e5e43535314c0344a5a98bd712e5
GDB: 15.1
GDB-Python: 3.12
```

### Operating System

Artix Linux

### Describe the issue you encountered

The docs document the following command: https://hugsy.github.io/gef/commands/ksymaddr/
ksymaddr. However I cannot find it in the source code nor get it to work inside gef.
```bash
~/gef> rg ksymaddr
mkdocs.yml
50:  - ksymaddr: commands/ksymaddr.md

docs/commands/ksymaddr.md
1:## Command `ksymaddr`
3:`ksymaddr` helps locate a kernel symbol by its name.
8:ksymaddr <PATTERN>
14:gef➤  ksymaddr commit_creds
```
Why is there nothing referencing it in the gef.py file? Furthermore
```bash
gef➤  ksymaddr
Undefined command: "ksymaddr".  Try "help".
```

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Clone the latest version of hugsy/gef and try to run the ksymaddr command inside it.

**Comment by Grazfather** [comment]
That functionality was moved to [gef-extras](https://github.com/hugsy/gef-extras)

We will have to update the docs in this repo.
