### ISSUE TITLE
[Bug] tmux-setup but no highlight

### ISSUE THREAD

**Issue by wangrongwei** [hugsy/gef#1142]
### GEF+GDB version

```shell
gdb:9.2
gdb-python:3.8
```

### Operating System

centos

### Describe the issue you encountered

When I run tmux-setup, it can split a single window in right, but no any highlight, likes:

![image](https://github.com/user-attachments/assets/e361d9ed-8c67-4843-a7b7-e9d73ea969e6)

I'm not sure whether need to update the gef.
Thanks for your time.

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [X] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Provide a step-by-step to reproduce your issue.

### Minimalist test case

Use this field for a minimal code to compile and spot the issue:
```c
// compile with gcc -fPIE -pic -o my_issue.out my_issue.c
int main(){ return 0; }
```
You can also provide a Dockerfile if you prefer

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by hugsy** [comment]
This doesn't seem like a bug since utf-8 characters are well rendered.

I'd suggest 2 leads: 
 - make sure your tmux settings allow colors (for instance using setting `set -g default-terminal xterm-256color `)
 - make sure your gef configuration doesn't have color disabled (`gef config gef.disable_color 1`)

I'd suggest you join the Discord to ask more configuration question, because this space is for bugs only.

**Comment by wangrongwei** [comment]
> This doesn't seem like a bug since utf-8 characters are well rendered.
> 
> I'd suggest 2 leads:
> 
> * make sure your tmux settings allow colors (for instance using setting `set -g default-terminal xterm-256color `)
> * make sure your gef configuration doesn't have color disabled (`gef config gef.disable_color 1`)
> 
> I'd suggest you join the Discord to ask more configuration question, because this space is for bugs only.
Hi hugsy

Thanks very much, I can sure the two setting: xterm-256color set and disable_color is False.

And I renew a Q&A:
https://github.com/hugsy/gef/discussions/1143

Thanks again!
