### ISSUE TITLE
TriCore support

### ISSUE THREAD

**Issue by HainLuud** [hugsy/gef#1144]
### Type of feature request

New architecture support/Existing architecture improvement

### Summary Description

I'd like to request support for the TriCore intruction set.

I'm currently using the https://github.com/volumit/gdb-tricore fork of gdb that supports debugging TriCore but gef currently doesn't seem to handle the architecture well. The colors are there but displaying code, registers, stack seems to be broken.  

For context, I am using QEMU to actually run the TriCore binaries (in system mode) and attaching to them using `gef-remote`.

### Implementation idea/suggestion

Get the nice default view of gef (where it displays the registers, code, stack, etc) working with QEMU emulated TriCore binaries.

**Comment by hugsy** [comment]
Hi, thanks for the suggestion.

Unfortunately, this arch seems to be very niche and unless any of the devs gets a reason too, it's unlikely we're going to implement this support.

If you feel like trying to integrate, PRs would be welcome but considering it's non standard (and even requires a specific GDB version) it would be to be added in [gef-extras](/hugsy/gef-extras), not gef itself.

Cheers

**Comment by HainLuud** [comment]
Understandable. Unfortunately I probably won't have the time to do it myself anytime soon so we can close this request I think. For now I've managed to get `gdb-dashboard` working quite nicely with the TriCore setup so my immediate wishes have been resolved. 

Thanks for the quick reply!
Cheers

**Comment by hugsy** [comment]
Glad you found a good fix then! 👍 

I'll be closing it, if you ever get a chance to work a PR for GEF you can always link this issue.
