### ISSUE TITLE
Duplicate panes in `context.layout`

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#1145]
## Description

There is a bug in `add_context_layout_mapping()` : the function adds a new layout to the gef config, without checking if already existing. As a result stuff like this happens (reported on [Discord](https://discord.com/channels/705160148813086841/705160148813086843/1298752523674451979))

![image](https://github.com/user-attachments/assets/8885a47b-2bb5-468b-a0e4-8f663958348b)

See https://github.com/hugsy/gef/blob/main/gef.py#L10025

**Comment by Grazfather** [comment]
This was added from the user's gef.rc? Do you know how? should the list be a dict? Since we only support 3.10+ we can count on them being sorted by insertion order.
