### ISSUE TITLE
the promp "Make breakpoint pending on future shared library load? (y or [n]) y" didn't show

### ISSUE THREAD

**Issue by fadhil-riyanto** [hugsy/gef#1157]
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/home/fadhil_riyanto/.gdbinit-gef.py): 166aa230260671bd29b675c99cc9a467cbeb678d
SHA256(/home/fadhil_riyanto/.gdbinit-gef.py): cde0ca3ff9aa51c2346cb515cadcde205c761cac77e088738c78e19bba80df03
GDB: 15.2
GDB-Python: 3.12
```

### Operating System

Archlinux

### Describe the issue you encountered

Hi, this promp didn't showing while I use gef, I think its GDB bug or something, after I realize when using LLDB and using pure GDB the promp showed

its make me a littebit confusing while debugging, until I found it.

here the screenshoof of lldb

![200](https://github.com/user-attachments/assets/39a2a451-b7d1-429d-8db2-24e2c937a9a1)

and this is pure gdb (no gef), its show the promp
![200](https://github.com/user-attachments/assets/d169997e-e097-4ece-af2e-bba74f8627f2)

and this is what happen on gef, the promp not showed
![200](https://github.com/user-attachments/assets/e6e385fe-7745-40f6-a81e-5c46c5a9f7d9)

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

reproduce step

```c
/* main.c */
#include "second.h"

int main()
{
        int a = 10;
        abc();
        return 0;
}
```

```c
/* second.c */
#include "second.h"

int abc()
{
        return 99;
}
```

```c
/* header file second.h */
int abc();
```

```Makefile
# makefile
main: main.o second.o
	gcc main.o second.o -o realmain

main.o: main.c 
	gcc main.c -o main.o -c 

second.o: second.c
	gcc second.c -o second.o -c -g 

clean:
	rm main.o
	rm second.o
```

### Minimalist test case

compile using `make main`
make sure gef installed. run `gdb ./realmain`
then `b main.c:5`

and the original gdb promp didn't showing

**Comment by Grazfather** [comment]
OP showed that the issue disappears if he doesn't load GEF, so it seems that GEF is doing something wrong here.
