### ISSUE TITLE
Python error while debbuging remote target 

### ISSUE THREAD

**Issue by dummys** [hugsy/gef#12]
Hi,
I run openOCD to jtag and attach with GEF+GDB 7.10.

GDB> taget remote 127.0.0.1:3333

Python Exception <class 'TypeError'> invalid file: None: 
Error while running hook_stop:
Error occurred in Python command: invalid file: None
0x802141b4 in ?? ()

Did you have an idea ? How can I help you with more log ?
thanks

**Comment by hugsy** [comment]
Yeah, more logs would be nice.

I'm still working on the support for remote target (see #7 ) which adds new challenges. Most notably, `gdb` cannot systematically retrieve the file being debugged which is important for unlocking all the features in `gef`.

**Comment by dummys** [comment]
tell me how I can produce more logs please

**Comment by hugsy** [comment]
Not sure I'll be able to help on this. I've never used `gdb` like this so it will be hard to find test cases.

But I gladly accept Pull Requests :)

**Comment by dummys** [comment]
yes but just tell me how I can have more logs, and I will try fixing this

**Comment by hugsy** [comment]
A good start will be to start removing some of the exception handlers (`try/except` blocks). This will make Python print out the whole stacktrace.
