### ISSUE TITLE
Use a class decorator or a metaclass to register commands

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#121]
We shouldn't need to add the classes to GefCommand.classes

**Comment by hugsy** [comment]
Agreed, it would be cleaner, just need to need a way to take into account the dependencies for subcommands. 
Been seriously busy lately but it shouldn't be hard to do, so I'll investigate soon.

**Comment by hugsy** [comment]
Done, simply decorate with `register_command`  or `register_priority_command` .
