### ISSUE TITLE
Support non ascii and hex escaped values in search-pattern

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#126]
Peda does this nicely:
```bash
gdb-peda$ find '\x7fELF'
Searching for '\x7fELF' in: None ranges
Found 8 results, display max 8 items:
babyallocator : 0x400000 --> 0x10102464c457f
         libc : 0x7f728a744000 --> 0x3010102464c457f
libgcc_s.so.1 : 0x7f728ab0d000 --> 0x10102464c457f
   ld-2.23.so : 0x7f728ad23000 --> 0x10102464c457f
   ld-2.23.so : 0x7f728ad287d1 (<open_verify+657>:    jg     0x7f728ad28818 <open_verify+728>)
   ld-2.23.so : 0x7f728ad41b20 --> 0x3010102464c457f
   ld-2.23.so : 0x7f728ad45670 --> 0x10102464c457f
```

Gef not so much:
```bash
gef➤  grep '\x7ELF'
[+] Searching 'x7ELF' in memory
gef➤  grep 'ELF'
[+] Searching 'ELF' in memory
0x8048001 - 0x8048007  →   "ELF"
0xf7c1e001 - 0xf7c1e007  →   "ELF"
0xf7c23001 - 0xf7c23008  →   "ELF"
```

`PatchStringCommand` DOES support it, but we have to double escape the string (e.g. `"\\x7f"`). This was my code, and apparently I should have looked harder for a nice way to do it :)

**Comment by hugsy** [comment]
This already works, but is ugly:
![](https://i.imgur.com/FLPPe3R.png) 

I will improve it.

**Comment by Grazfather** [comment]
Sorry yes I discovered it in IRC but should have pasted it here.

The way it's done in `peda` is that they don't use `gdb.string_to_argv`, they wrote their own that uses `codecs.decode('unicode_escape')` (for py3). Our `GenericCommand`'s `invoke` uses the GDB variety which gobbles up single backslashes.

Since it's at least _possible_ to do this as is, I'd personally lower the priority here. (I should work on #56)

**Comment by hugsy** [comment]
The improvement as you suggest does not look hard to implement so I will do that over the weekend :smile:

**Comment by hugsy** [comment]
And maybe a good extension would be something like: if `pattern.startswith("0x")` then we search all over the address space for this address. `find` does it but stop when you hit an unmmaped memory page. That would allow to search for cross-reference.

What do you think?

**Comment by Grazfather** [comment]
Yeah that would be a great addition. That way you don't need to hex escape large numbers. Maybe it could be behind a flag? I don't think it would be common, but what if you wanted to search for a literal string that starts with "0x"?

**Comment by hugsy** [comment]
There you go buddy:

![](https://i.imgur.com/2FZX7JT.png)

**Comment by Grazfather** [comment]
👌 
Beautiful. This doesn't get around the need for double escaping hex chars, but that could be another issue. This is great.

**Comment by hugsy** [comment]
Hehe :smile: 
Feel free to test it in `dev`, I'll close the issue when it lands into `master`. Thanks for the suggestion!
