### ISSUE TITLE
Show changed registers in context EVEN WITH show_registers_raw

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#127]
The highlighting to show that a reg has changed is nice.

Unfortunately if `show_registers_raw` is False, we just run `registers`, which has no concept of the registers having a previous state. It might ugly up the code but we might consider it worth it so we don't have to compromise.

**Comment by Grazfather** [comment]
We could do this, perhaps, by having `registers` be a method in the context command. With this `registers` on its own would _gain_ the highlighting.

**Comment by Grazfather** [comment]
Fixed in #147

**Comment by hugsy** [comment]
For tracking:
https://github.com/hugsy/gef/pull/147/commits/f72ec6ec32fe17559188910783962d3b42987efd
