### ISSUE TITLE
VMMAP Caching Problem

### ISSUE THREAD

**Issue by sashs** [hugsy/gef#131]
Hi,

I've noticed today when the virtual maps are changed during runtime (e.g. with a sbrk call), gef prints the old mappings. I think this is because of the lru_cache. I recommend not caching the mappings information. :)

regards
sash

**Comment by hugsy** [comment]
Hi @sashs,

Yes this problem is already fixed in a appropriate way in the `dev` branch. It should land soon to `master`.
Thanks for the feedback still.

**Comment by sashs** [comment]
Cool! :)
