### ISSUE TITLE
str_as_freeed error

### ISSUE THREAD

**Issue by zzoru** [hugsy/gef#133]
Typo in gef.py
https://github.com/hugsy/gef/blob/af620e816fdae6614e0628b7bf091b452de94db4/gef.py#L748
freeed -> freed

**Comment by hugsy** [comment]
Hi @zzoru ,

This was already fixed by @Grazfather in the `dev` branch and merged to `master` yesterday (see: https://github.com/hugsy/gef/blob/af620e816fdae6614e0628b7bf091b452de94db4/gef.py#L733).
You can `git pull` to see it fixed.

Cheers

**Comment by zzoru** [comment]
@Grazfather changed typo on https://github.com/hugsy/gef/blob/af620e816fdae6614e0628b7bf091b452de94db4/gef.py#L733
but, @Grazfather forgot fix function reference in https://github.com/hugsy/gef/blob/af620e816fdae6614e0628b7bf091b452de94db4/gef.py#L748

**Comment by hugsy** [comment]
AAAAHHH lol
Fixing now :laughing:

**Comment by hugsy** [comment]
@zzoru it should be fixed now, I will soon add a regression test for that.

Thank you

**Comment by Grazfather** [comment]
hey stop pointing fingers ;)
