### ISSUE TITLE
search-pattern not working for hexadecimal values because of bug in is_hex

### ISSUE THREAD

**Issue by jr64** [hugsy/gef#136]
The search-pattern command does not work as intended for hexadecimal values (e.g. ```search-pattern 0xdeadbeef```). I tracked the bug back to the is_hex function which always returns false because of the following condition:

```
all(c in string.hexdigits for c in pattern)
```

pattern is a string that starts with "0x" so this can never be true.

**Comment by hugsy** [comment]
This is a bad regression. Will fix ASAP.

**Comment by hugsy** [comment]
@jr64 Can you confirm the fix ?

**Comment by jr64** [comment]
@hugsy Working fine now, thanks for the quick fix!

I know this command is only meant to search for raw hex content, but imho it would be really handy if there were a way to automatically consider byte order. For instance, if I want to search for the stack canary, I have to manually reverse the bytes which is really annoying. 

e.g. 
```
gef➤  canary
[+] Found AT_RANDOM at 0x7fffffffe8a9, reading 8 bytes
[+] The canary of process 1536 is 0x2d91d808f8cf1000
gef➤  grep 0x2d91d808f8cf1000
[+] Searching '0x2d91d808f8cf1000' in memory
gef➤  grep 0x0010cff808d8912d
[+] Searching '0x0010cff808d8912d' in memory
0x7ffff7fea868 - 0x7ffff7fea868  →   ""
gef➤
```

**Comment by hugsy** [comment]
Good point @jr64 , for tracking purposes I'm going to close this issue as it is fixed.
Can you create another one with your suggestion?

**Comment by jr64** [comment]
@hugsy done, you can close this issue.
