### ISSUE TITLE
endianness support for pattern-search

### ISSUE THREAD

**Issue by jr64** [hugsy/gef#138]
Imho it would be really handy if there were a switch to convert byte order. Something like --word, --doubleword and --quadword. For instance, if I want to search for the stack canary, I have to manually reverse the bytes which is really annoying.

Example:
```
gef➤  canary
[+] Found AT_RANDOM at 0x7fffffffe8a9, reading 8 bytes
[+] The canary of process 1536 is 0x2d91d808f8cf1000
gef➤  grep 0x2d91d808f8cf1000
[+] Searching '0x2d91d808f8cf1000' in memory
gef➤  grep 0x0010cff808d8912d
[+] Searching '0x0010cff808d8912d' in memory
0x7ffff7fea868 - 0x7ffff7fea868  →   ""
gef➤
```

**Comment by hugsy** [comment]
This is a good idea, but I don't think there is a need for a switch actually: what I mean is, I can't see why someone would be searching for a big endian value on a little endian ELF (and vice versa).

I will simply update the search for hex to consider the current ELF endianness.

**Comment by hugsy** [comment]
That was easy :smile: 

![grep-hex](https://cloud.githubusercontent.com/assets/590234/24970648/ed69cb34-1f69-11e7-86f4-94a573a4fe66.png)

@jr64 : Can you please test and confirm that was what you had in mind?

**Comment by hugsy** [comment]
That's actually pretty neat like this, it allows to show the xrefs to an address :sunglasses: 

Awesome !

**Comment by jr64** [comment]
@hugsy Tested it out, works great!

Regarding the switch, I can see some cases where it would be useful:

Let's assume we are debugging on a 32 bit intel cpu. One might want to search for something like "`0xdeadbeef` followed by `0xdecafbad`. In memory this looks like `ef be ad de ad fb ca de` but if you do `grep 0xdeadbeefdecafbad` it will obviously not search for that. So for this case we need something like `grep -4 0xdeadbeefdecafbad` so grep knows to treat the data as double words.

Of course one could just search for `0xdecafbaddeadbeef` but that would again require some manual conversion. Might be confusing with longer data.

Another issue I see is with searching for magic header values. One might know that a file starting with a specific byte sequence is somewhere in memory and wants to look for that. In this case automatic endian conversion isn't exactly helpful. Something like `grep -1` could tell the command to keep the byte order.

**Comment by jr64** [comment]
Also I think the xref command is a great idea. I have no idea if it is in any way possible to implement something like this without completely killing performance, but I would absolutely love to have a command to search for a range of xrefs, something like `xref 0x07ffaaaa-0x07ffbbbb`. With this you could do stuff like search for pointers to a specific library or print all heap pointers on the stack. That would be really useful to me.

If you think it can be done I can open an issue.

**Comment by hugsy** [comment]
> Another issue I see is with searching for magic header values. One might know that a file starting with a specific byte sequence is somewhere in memory and wants to look for that. In this case automatic endian conversion isn't exactly helpful. Something like grep -1 could tell the command to keep the byte order.

That's a valid point. Didn't think of magic numbers. 

> Also I think the xref command is a great idea. I have no idea if it is in any way possible to implement something like this without completely killing performance, but I would absolutely love to have a command to search for a range of xrefs, something like xref `0x07ffaaaa-0x07ffbbbb`. With this you could do stuff like search for pointers to a specific library or print all heap pointers on the stack. That would be really useful to me.

Yeah, such search would be very costly. You can always `xref` for 0x07ffaa, that's already working, but on a range (say one page), I don't think it is a good idea perf wise. But WinDBG does it so it could be good to have. I'll give a try and come back to you on this.
