### ISSUE TITLE
hijack-fd: Support connecting to ip:port

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#139]
Instead of just trying to open a file, maybe check for a `:` in the second arg, and if so, make a `connect` call to it.

**Comment by hugsy** [comment]
![](http://thefw.com/files/2013/06/Minion-Meme.png)

**Comment by Grazfather** [comment]
If you could make `hijack-fd 0 localhost:8888` do this:

```c
close(0);
<create address>
socket(...)
connect()
```

I could spoof a webserver that an application I am testing is connecting to.

You might say "Just edit _/etc/hosts_" but I say, "That's too easy".

**Comment by hugsy** [comment]
If I understand correctly, you want GDB-Python to create a socket and pass it to the debugged process?? AFAIK you can only do on Unix using `recvmsg` and `sendmsg` syscalls, which complicated the thing quite a bit.

**Comment by Grazfather** [comment]
Not if the fd is _already a socket_.

It's a use case I had recently.

**Comment by Grazfather** [comment]
Fixed in #284.
