### ISSUE TITLE
Only CONDITIONAL jumps peek ahead. Make UNconditional peek also

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#145]
Noticed today that `jmp` and family don't peek ahead in `context_code`. I added an option to peek for `call`s in #144. It'll be a bit more work to add it to unconditional jumps.

**Comment by hugsy** [comment]
Can we close this?

**Comment by Grazfather** [comment]
Naw I think still this is worth working on.

The trick is in determining the address of the jumps for each arch. We should probably add a method to the arch itself that takes the context and the instruction and returns the jump address, it would probably clean up the conditional jump stuff too.

**Comment by Grazfather** [comment]
I think this is for later. One way we could do it, although I am not sure how slow it would be, is to use unicorn to emulate the instruction, step once, and see where it ends up.

**Comment by hugsy** [comment]
That would make `unicorn` a strict dependency on GEF, that's what pwndbg does and I really don't like it. Unicorn is a nightmare to setup on embedded devices.

**Comment by hugsy** [comment]
What are the constraints on it exactly? 

The way I see the implementation, we can solve it statically, without `unicorn` because we can only have:

 - `jump $reg`
 - `jump <address>` 

Which we can know all the time. Do you see any other cases?

**Comment by Grazfather** [comment]
Well it's that we have to figure it out for each case for each arch, which means each addressing mode.

I'm totally cool with doing something like the `peek_ret`: Just unset `branch_taken` if we can't figure out the address, and that way it just doesn't show a jump target (better than an incorrect one).

**Comment by Grazfather** [comment]
This might be an easy enough thing for a new contributor to take a crack at.
