### ISSUE TITLE
Regression - dereference won't print strings anymore

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#146]
Strings are not printed via dereference (silenced exception?):
![1](https://cloud.githubusercontent.com/assets/590234/25394688/93c4d04a-2993-11e7-81d1-da57a20d9ee1.png)

![2](https://cloud.githubusercontent.com/assets/590234/25394693/97b20d1c-2993-11e7-981b-1fa52f46117b.png)

Fix ASAP

**Comment by Grazfather** [comment]
Let me bisect.

**Comment by Grazfather** [comment]
This is the culprit.

```bash
commit 74d3c3af5968e3fb32abfb1a5102f2a38162e411
Author: hugsy <hugsy@blah.cat>
Date:   Mon Apr 17 14:09:06 2017 -0700

    added new caching function for type: __cached_lookup_type
```
