### ISSUE TITLE
Error in CentOS 7

### ISSUE THREAD

**Issue by dukebarman** [hugsy/gef#148]
OS: CentOS 7 with last updates
```
# gdb -v
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
# python --version
Python 2.7.5
```

Doesn't see other information from gef (for example, disasm) after this error:

```
------------------------------------------------------------------------------[ registers ]---

...
$ss      0x000000000000002b $ds      0x0000000000000000 $es      0x0000000000000000           
Python Exception <type 'exceptions.AttributeError'> 'gdb.Frame' object has no attribute 'read_
register':                                                                                    
Python Exception <class 'gdb.error'> Error occurred in Python command: 'gdb.Frame' object has 
no attribute 'read_register':  
```

I think problem in part of code for old versions of gdb

**Comment by hugsy** [comment]
We need the version of Python compiled with GDB: can you run
```
gdb -nx -ex 'python print (sys.version)' -ex quit
```

**Comment by dukebarman** [comment]
```
$ gdb -nx -ex 'python print (sys.version)' -ex quit
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

**Comment by hugsy** [comment]
Thanks for reporting @dukebarman , I'll setup an env and get back in touch.

**Comment by hugsy** [comment]
I can reproduce: CentOS 7 ships with a 2013 version of GDB -> meaning:
 * gdb.Frame doesn't exist
 * gdb.Breakpoint.temporary is not a valid attribute

**Comment by Grazfather** [comment]
Should we bump the minimum gdb version mentioned in the readme?

**Comment by hugsy** [comment]
I spent too long trying to make a retro-compatibility with GDB < 7.7.x which ends up making the code too dirty and lacking great features of "recent" GDB-Python.

So yes @Grazfather ,  we should bump the minimal version of GDB to 7.7.x minimum. I will update the README and documentation to reflect that today, and close this issue when done.

**Comment by hugsy** [comment]
- Dropped support for GDB < 7.7. 
- GEF does not cleanly when GDB is too old.
- Docs updated to reflect that.
