### ISSUE TITLE
Instruction parsing broken on AARCH64

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#149]
```c
#include <stdio.h>
int main()
{
    int(*f)(const char*) = puts;
    f("Hello, World");
}
```

Compile for AARCH64

```
gef➤  pi list(gef_disassemble(0x400590, 1))[2].mnemo
'blr\tx1'
```

**Comment by Grazfather** [comment]
It's because gdb dissasembles AARCH64 weird:

```
gef➤  pi gdb.selected_frame().architecture().disassemble(0x400590)
[{'asm': 'blr\tx1', 'length': 4, 'addr': 4195728}]
```

We test for a literal space, not all whitespace

**Comment by Grazfather** [comment]
Fixed in 95e8076

**Comment by Grazfather** [comment]
We can probably close this: Let me test tomorrow at work.

**Comment by hugsy** [comment]
I've tested the new `master` on my AARCH64 Qemu image, no problem observed. If we are good too, we can close this.
