### ISSUE TITLE
GEF as a library

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#152]
See how to use all `gef` as a lib from an external script: this would be useful for creating "one-time" GDB Python script for CTF and still enjoying all the goodness of the functions and environment already setup by `gef`.

Ideally, create a new command would be as easy as `import gdb, gef` then the new command declaration:

```python
#
# this is a theoritical prototype
# do not use, it doesn't work
#
import gdb
import gef

@gef.register_command
class NewCommand(gef.GenericCommand):
    """Dummy one-time command."""
    _cmdline_ = "mycmd"
    _syntax_  = "{:s}".format(_cmdline_)

    def __init__(self):
        super(NewCommand, self).__init__(complete=gdb.COMPLETE_SYMBOL, prefix=False)
        return

    @gef.only_if_gdb_running
    def do_invoke(self, argv):
        # here we can use other commands, or global variables from
        #  gef, like current_arch and all
        return
```

**Comment by Grazfather** [comment]
You can't even `import gdb` from outside of the python build into gdb :( So to run these scripts you'd have to run `gdx -ex...`

**Comment by hugsy** [comment]
I want to run them inside GDB, on top of `gef`. As I said, it would be like a one-time command, something written fast during a CTF that we don't intend to see builtin. So kind of registering an external `gef` script if you see what I mean.

**Comment by hugsy** [comment]
Actually, this is already here by design thanks to Python awesomeness. I'll document it very soon, this is really cool :sunglasses:

**Comment by hugsy** [comment]
This is pretty cool (I think).

Basically, all the functions / classes defined by `gef` live in the same Python VM of GDB and so share all `globals`. So here it is possible to write external commands super easily, such as this example:

```python
$ cat > /tmp/newcmdtest.py << EOF
import gdb # not required 

@register_command
class NewCommand(GenericCommand):
    """Dummy one-time command."""
    _cmdline_ = "newcmd"
    _syntax_  = "{:s}".format(_cmdline_)

    def __init__(self):
        super(NewCommand, self).__init__(complete=gdb.COMPLETE_SYMBOL, prefix=False)
        self.add_setting("plop", True, "big plop")
        return

    @only_if_gdb_running
    def do_invoke(self, argv):
        # do whatever things allowed by gef:
        print("arch = {}".format(current_arch) )
        print("pc = {:#x}".format(current_arch.pc))
        return

if __name__ == "__main__":
    NewCommand()
EOF
```
It can be loaded via GDB directly:
```
gef➤  load /tmp/newcmdtest.py
```
which produces (after commit d20e2ea)

![](http://i.imgur.com/0g4AeCb.png)

The new command settings and help are also merged into the current `gef` context:

![help](https://cloud.githubusercontent.com/assets/590234/25687928/32e839c2-302f-11e7-9e62-a9e683523210.png)

![setting](https://cloud.githubusercontent.com/assets/590234/25687946/60bbdda4-302f-11e7-8530-85bde90cca1f.png)

@Grazfather : please feel free to test; I think it opens a whole new aspect of the dev for new commands, for example creating another repositories of other commands a bit dodgy (where people can easily push stuff) and leave the big core solid, so `gef` becomes a bit less monolithic, keeps the advantages of offering good commands built-ins, quick install (no dependencies),  but can be extended super simply. I'd be super curious to have your opinion on that

**Comment by hugsy** [comment]
This was easier to do than expected thanks to Python awesomeness. 

Created https://github.com/hugsy/gef-scripts as a public repo for new GEF commands. If they are solid and documented enough, they'll be merged into `gef.py`.

This will land to `master` very shortly.

**Comment by hugsy** [comment]
Merged, closing.
