### ISSUE TITLE
context trace cannot disassemble at bogus rip

### ISSUE THREAD

**Issue by mokhdzanifaeq** [hugsy/gef#153]
i was playing with a [stripped binary](https://mega.nz/#!JEBSgbrD!gDZ3uOD8lgQw3zMnnyu7_MnOYj99HX0nao5iYqbaJFQ) when the following error occurs after `entry-break`

![error](https://i.imgur.com/eGGzVUH.jpg)

the error happened when gef was trying to disassemble the instruction at 0x1 (rip of previous frame). it also will set the rip to the bogus value after failing. my current workaround is by checking if rip exist in the sections before disassembling, but maybe you have another idea

![workaround](https://i.imgur.com/QCfHmh3.jpg)

![demo](https://i.imgur.com/nwoRp0v.jpg)

**Comment by Grazfather** [comment]
Good find. It sets RIP correctly because it bails out of the loop and doesn't correctly return to the original frame. I'll fix it.

**Comment by Grazfather** [comment]
Fixed in f9bb069.

Can you please pull (master) and verify?

**Comment by mokhdzanifaeq** [comment]
fixed :+1:

![fixed](https://i.imgur.com/EUBezzw.jpg)

**Comment by Grazfather** [comment]
Great! Thanks for the report.
