### ISSUE TITLE
ERR: Run heap command

### ISSUE THREAD

**Issue by HaToan** [hugsy/gef#156]
### Step 1: Describe your environment

  * Operating System:Ubuntu 14.04.2
  * Architecture: x86_64
  * GDB GNU   7.7.1 - python 3.4

### Step 2: Describe your problem

```
 gef➤  heap arena
 [!] Could not find Glibc main arena

 gef➤  heap bins
 [!] Failed to get `main_arena` symbol, heap commands may not work properly: No symbol table is loaded.  Use the "file" command.
 [*] Did you install `libc6-dbg`?
 [!] Invalid Glibc arena
 [!] Incorrect Glibc arenas
 [!] Incorrect Glibc arenas
 [!] Incorrect Glibc arenas
```

I installed library libc6-dbg "libc6-dbg is already the newest version"

Help me , fix error

**Comment by Grazfather** [comment]
Run `info proc mappings`. You may have libc-dbg installed, but I doubt it's the one that is loaded in the process. Run `p main_arena` and you'll get another error.

**Comment by hugsy** [comment]
Pretty sure you're debugging a x86 binary on your x64 system.
So you need to install `libc-dbg:i386`.
