### ISSUE TITLE
Syntax error in python script.

### ISSUE THREAD

**Issue by X3STeNLiTE** [hugsy/gef#159]
I'm installed by followed document instruction either install script and manually installation

  * Operating System:
CentOS 6.4
  * Architecture:
AMD64
  * GDB version (including the Python library version):
GDB 7.9.1 (installed from source)
Python 2.7.10 (installed from source)

```
  File "~/.gdbinit-gef.py", line 1333
    call_mnemos = {"bl", "blx"}
                       ^
SyntaxError: invalid syntax
```

I'm not python expert but If there's array declaration syntax shouldn't like this?

#### Steps to reproduce

  - gdb -q /path/to/program

#### Expected results

  * This error shouldn't appear.

#### Traces

![image](https://user-images.githubusercontent.com/9717561/27505075-121bec06-58c1-11e7-8d26-4e85f8c2d0de.png)

**Comment by hugsy** [comment]
That doesn't make any sense. On Python 2.7+ 
```
call_mnemos = {"bl", "blx"}
```
is **strictly** equivalent to
```
call_mnemos = set(["bl", "blx"])
```

![](https://i.imgur.com/utGzvh5.png)

There is no syntax error here.

@X3STeNLiTE Can you give me the result of:
```bash
$ gdb -nx -ex 'python print (sys.version)' -ex quit
```

**Comment by X3STeNLiTE** [comment]
Turns out it's using python 2.6.6

```
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

I compiled GDB 7.9.1 before I installed python 2.7.+ is that matter.

It's not GEF bug, i'm sorry

**Comment by hugsy** [comment]
Just for the record, GEF was tested on CentOS 6.4 with (compiled from source) GDB 7.9.1 with Python 2.7.7 and it works great.
