### ISSUE TITLE
Failed install retdec-python keystone-engine

### ISSUE THREAD

**Issue by lion-Da** [hugsy/gef#162]
### Step 1: Describe your environment

  * Operating System: Linux 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-1kali1 (2017-06-06) x86_64 GNU/Linux
  * Architecture: amd64
  * GDB version (including the Python library version):  GDB 7.12 using Python engine 2.7

### Step 2: Describe your problem
    when I use pip2 install keystone-engine retdec-python,some errors occur...

    keystone-engine : pip2 install keystone-engine successfully but not work in gdb . Funny i use pip2 install keystone, it works in gdb,but ropper doe not work.
    retdec-python: python 2.7 can not install. it requires Python >= 3.3 or PyPy3 >= 2.4
                             https://github.com/s3rvac/retdec-python

#### Observed Results
    retdec-python:
```
root@DaLion:~# pip2 install retdec-python
Collecting retdec-python
  Using cached retdec-python-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oV8we9/retdec-python/setup.py", line 37, in <module>
        version=get_project_version(),
      File "/tmp/pip-build-oV8we9/retdec-python/setup.py", line 30, in get_project_version
        read_file(os.path.join('retdec', '__init__.py'))
      File "/tmp/pip-build-oV8we9/retdec-python/setup.py", line 17, in read_file
        with open(file_path, encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oV8we9/retdec-python/
```
So I git the retdec-python source and modify the setup.py in line 17, I remove the code "encoding='utf-8'".  
I  use python setup.py build , python setup.py install Successfully.   But in gdb ,it dies as follow...
```
[*] Command `retdec` is missing, reason -> invalid syntax (service.py, line 24) 
```
    keystone-engine:  Firstly, i use pip2 install keystone-engine, it works and no error messages. But in gdb :
[*] Command `assemble` is missing, reason -> Missing `keystone-engine` package for Python2, install with: `pip2 install keystone-engine`.
[*] Command `set-permission` is missing, reason -> Missing `keystone-engine` package for Python2, install with: `pip2 install keystone-engine`.

I uninstall keystone-engine,and install keystone(pip2 install keystone) ,there is no error messages above,but ropper reports error:
```
[*] Command `ropper` is missing, reason -> 'module' object has no attribute 'KS_ARCH_X86'
```
if i install keystone-engine, ropper will not report error....
if I install both of them , it will give errors message same to keystone-engine install only.

**Comment by hugsy** [comment]
This is not a bug.

 1. `retdec-python` is not supported on Python 2. See the project page.
 1. `keystone` from PIP is a Web Framework. `keystone-engine` is the package from PIP to get the assembly features. If you can't install a package, refer to the project bug report, not here.

Thanks.
