### ISSUE TITLE
Set pagination vs height/width?

### ISSUE THREAD

**Issue by MannyC** [hugsy/gef#163]
gef seems to set the height and width of the screen to 0 [here](https://github.com/hugsy/gef/blob/master/gef.py#L7794 ), which effectively disables [pagination](https://sourceware.org/gdb/onlinedocs/gdb/Screen-Size.html).  

gdb also has a `pagination` setting, about which it says 

> Turning pagination off is the alternative to set height unlimited. 

I have found that the height/width get reset whenever I resize the terminal window, which re-enables pagination.  This wouldn't be an issue, but it seems that the gdb doesn't deal well with the control sequences used by gef, and it inserts a page break in the middle of gef's `context` output.  

Setting `pagination` to off fixes this, and pagination doesn't get turned back on when I resize the window

**Comment by hugsy** [comment]
Fixed by 72a1adb
Thank you!

**Comment by Grazfather** [comment]
Do we still need to set the width and height?

**Comment by hugsy** [comment]
No we don't. But the setting is done in several locations in `gef`, need to remove all of them.
Will do soon.

**Comment by hugsy** [comment]
They are removed locally, will push soon (with other updates).
