### ISSUE TITLE
Better subcommand missing message

### ISSUE THREAD

**Issue by Escapingbug** [hugsy/gef#165]
### Step 1: Describe your environment

  * Operating System: Manjaro linux 17.01
  * Architecture: x86_64
  * GDB version (including the Python library version): 8.0 with python 3.6

### Step 2: Describe your problem
When I use heap command without any subcommand, there is no message showed, I think it is better when we have some "subcommand missing" showing or even a help message on how to use this command.

I can make a pull request if this suits your guys interests. Since I'm not sure you think this is neccessary, I just make a issue first. :)
#### Steps to reproduce

  1. Just use "heap" without any subcommand, nothing showed

#### Observed Results

  * Nothing, well, literally nothing..

#### Expected results

  * A simple message to tell me that I used wrong command, I need to specify a subcommand, or a message from help command.

**Comment by hugsy** [comment]
Fixed:
![img](https://user-images.githubusercontent.com/590234/28905833-35608476-77c8-11e7-8fa3-2e7d174ac2b7.png)
