### ISSUE TITLE
Hide threads view if there is only one thread

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#170]
Similar to memory being hidden if there are no watches.

**Comment by Grazfather** [comment]
Would be super easy to do, the only concern is: Do we really want it? the benefit so showing the single thread is that it shows why it was stopped

**Comment by hugsy** [comment]
Hum, I would need more opinion on it tbh. In real life, I use GEF a lot for reversing some MT apps so I need the view, but I realize that in CTF it is usually not the case (mono-threaded).

The way I see it, the pane is quite small and doesn't disturb me when only one thread is used. And as you said, it is required to see the reason of breaking. But on the other hand, I have no objection to hide it.

Do you have any particular reason for it to be hidden by default ?

**Comment by Grazfather** [comment]
I am just trying to shorten the total number of lines printed by default, to minimize scrolling.

**Comment by hugsy** [comment]
Then we could simply change the default of `context.layout` to something like:
```
regs stack code args -source -threads -trace extra
```

Such display should be fine on any modern monitor.

**Comment by hugsy** [comment]
Actually, I think it should stay the way it is, even when there is only 1 thread, since it shows the reason why this one thread is being stopped. And I believe it is less confusing too (because explicit).
