### ISSUE TITLE
gef> heap chunk 0x602000 Python Exception <type 'exceptions.AttributeError'> class Color has no attribute 'GREEN':  Error occurred in Python command: class Color has no attribute 'GREEN'

### ISSUE THREAD

**Issue by skyroot** [hugsy/gef#173]
### Step 0: Preliminary (remove this part if all good)

  * Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * Did you check closed [issues](https://github.com/hugsy/gef/issues)?
  * Did you use the latest version of GEF from `master` branch?

### Step 1: Describe your environment

  * Operating System:
  * Architecture:
  * GDB version (including the Python library version):

### Step 2: Describe your problem
gef> heap chunk 0x602000
Python Exception <type 'exceptions.AttributeError'> class Color has no attribute 'GREEN': 
Error occurred in Python command: class Color has no attribute 'GREEN'

#### Steps to reproduce

  1.
  1.
  1.

#### Observed Results

  * What happened?  This could be a description, log output, etc.

#### Expected results

  * What did you expect to happen?

#### Traces

Feel free to include in this section screenshots, stack traces, or

```
the exact code here to reproduce the problem
```

By enabling `gef.debug` setting (`gef config gef.debug 1`), `gef` will display a
full stack trace if an exception occurs. It is a good idea to copy/paste it here
as it contains all useful information for being able to reproduce.

**ProTip:** Using GitHub, you can easily add files to your issues by a simple
Drag n'Drop.

**Comment by Grazfather** [comment]
FTR: It was an out of date version of GEF
