### ISSUE TITLE
GEF chokes on Go binaries

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#174]
Will fill in details after CTF

**Comment by hugsy** [comment]
Wanna test this with this super quick patch ? 
[Issue_#174.patch.txt](https://github.com/hugsy/gef/files/1589689/Issue_.174.patch.txt)

It seems to do the job: 
![](https://i.imgur.com/xCOAqIs.png)

**Comment by Grazfather** [comment]
Seems to work for me.

**Comment by hugsy** [comment]
Killer, I'll test and push it then.
