### ISSUE TITLE
Special character issue with gef prompt.

### ISSUE THREAD

**Issue by Roguebantha** [hugsy/gef#182]
On Ubuntu Bash on Windows, the gef prompt initialized in the gef gdbconfig file incorrectly parses to "gef" along with a special character (a box with a question mark inside) that couldn't be displayed on the system. I solved the problem by substituting the character for a "> " sign.

```
-  gef_prompt = "gef\u27a4  "
+ gef_prompt = "gef>  "
```

**Comment by Grazfather** [comment]
That's a problem with your font

**Comment by Roguebantha** [comment]
Hey Grazfather,

It's happened across two different computers, which is why I'm noting it, because it clearly doesn't work with the defaults for Ubuntu Bash on Windows.

**Comment by Grazfather** [comment]
![.](https://user-images.githubusercontent.com/497310/31839291-4c4e048c-b595-11e7-8f4c-99d3bb819d0f.png)

**Comment by Grazfather** [comment]
You never mentioned windows in the first post. If you find a nice arrow that works on ubuntu bash windows we could consider changing it.

**Comment by Roguebantha** [comment]
My dearest apologies, I certainly did not make that clear; the OP has now been edited.

As for fixing this issue on Bash on Windows, it looks like the default font does not support unicode characters at all.

However, perhaps the problem could be solved with a specific patch for Bash on Windows that switches to a simple "> " if on an unsupported platform. Two different thoughts; detecting whether unicode characters are supported (hard but thorough) or we could check whether we're in Bash on Windows (easy [check if /mnt/c/ exists] but mildly sloppy).

Of course, you're free to do whatever you're like (such as declaring it a feature) and I can keep patching it on my side lol :P

**Comment by Grazfather** [comment]
You have a point: Right now we choose whether or not we want to use unicode based on the version of python built into gdb. It would be better if we also checked for unicode support in the terminal, though I am not sure how best to do that.

**Comment by Roguebantha** [comment]
Indeed it's not incredibly simple...you can return the supported characters in the terminal itself using
`locale charmap`

In my case, this returns UTF-8...the arrow that is currently being used is UTF-16 yes? If so, that might be good enough to determine which character to use in a way that will work with bash.

If in fact the arrow IS UTF-8 (I don't think it is, but if it is) then that could make for a very tough call, as it sounds like the problem is beyond bash and in the UI that Windows wraps the terminal in.

Hopefully, the arrow is UTF-16, and checking if the terminal supports it with "locale charmap" is good enough.

**Comment by Roguebantha** [comment]
As a further note, I was previously wrong in saying that the terminal does not support unicode...it definitely supports UTF-8, as attempting to print known UTF-8 characters work fine. Definitely should be enough to use `locale charmap` then to determine support.

**Comment by hugsy** [comment]
I don't think there is much to do here.

Just to be clear: as said [in the docs](https://gef.readthedocs.io/en/master/config/) `gef` was only tested on UTF-8 charset on standard Linux distro. There is no UTF16 character or support, and there will probably never be. UTF8 is the de facto standard, and testing every single charset will be unmaintainable. I doubt `gdb` can work correctly on WSL (`ptrace()` cannot simply be emulate by LXCore), so Bash on Windows is not the priority.

To @Roguebantha : yes the arrow is a [UTF8 valid symbol](http://www.fileformat.info/info/unicode/char/27a4/index.htm)

**Comment by Roguebantha** [comment]
That is curious. It's odd that certain UTF8 characters are appearing for me, and others are not.

As for whether gdb can work on WSL, it actually works great and has no problems in my experience.

**Comment by Grazfather** [comment]
UTF8/UTF16 are not character sets, they are encodings. the `\uXXXX` syntax dictates the unicode code point _not_ the encoding, so then the issue is not utf8 vs utf16.

**Comment by Roguebantha** [comment]
Aah, thank you for clarifying that point.

Yeah it does appear to be a font problem for me as changing the font caused it to render correctly. In this case, I don't see an easy solution to this issue from the gef end :/
