### ISSUE TITLE
layout src has problem displaying prompt

### ISSUE THREAD

**Issue by Escapingbug** [hugsy/gef#194]
### Step 1: Describe your environment

  * Operating System: Manjaro linux 17.04
  * Architecture: x86_64
  * GDB version (including the Python library version): 8.0.1 python-3.6

#### Steps to reproduce

  1. gdb any file with debug info and source file
  2. run it, and use `lay src`
  3. you will see the raw escape sequence now

#### Observed Results
(ignored src window, only prompt result here)
   
native process 8009 In: main                                                    L3    PC: 0x5555555546c2 
^A^[[1;32m^Bgef➤  ^A^[[0m^B^A^[[1;32m^Bgef➤  ^A^[[0m^B

#### Guessed Reason
I don't know exactly how this works in gdb when you use `layout` command, but apparently no escape sequence handled here. Can we just disable all escape sequence output and turn on later when `layout src` like command is typed?

#### Expected result

  Display as usual, at least no raw escape sequence here

**Comment by Grazfather** [comment]
gef doesn't support the TUI.

**Comment by Escapingbug** [comment]
So we just need to ignore that?

**Comment by hugsy** [comment]
@Escapingbug 
I don't see the need of the TUI since `context` provides all info needed (especially since you can redirect its output to any file descriptor).
But if you have PR to submit, go ahead, we'll take a look.
