### ISSUE TITLE
Get "UnicodeEncodeError" when running gef on Raspberry Pi

### ISSUE THREAD

**Issue by mattherman** [hugsy/gef#195]
### Step 1: Describe your environment

  * Operating System: Raspbian
  * Architecture: ARM (`uname -m` gives "armv6l")
  * GDB version: GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
  * Python library version: 3.5.3 (default, Jan 19 2017, 14:11:04) \n[GCC 6.3.0 20170124]'

### Step 2: Describe your problem

Running `gdb` with `gef` installed results in the following error:
```
Python Exception <class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\u27a4' in position 12: ordinal not in range(128): 
```

#### Steps to reproduce

  1. Install `gef` on a Raspberry Pi Model B using the install script
  1. Run `gdb`

#### Observed Results

Once `gdb` starts up, the error is thrown. Attempting to run `gef` will also result in the error. Running `gef missing` appears to succeed as the missing package information is displayed, but the error is printed following that output.

I attempted to enable `gef.debug`, but the `gef config` command simply output the same error.

The error can be seen in the following terminal output:
```
pi@raspberrypi:~ $ gdb
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
[*] No debugging session active
GEF for linux ready, type `gef' to start, `gef config' to configure
64 commands loaded for GDB 7.12.0.20161007-git using Python engine 3.5
[*] 3 commands could not be loaded, run `gef missing` to know why.
Python Exception <class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\u27a4' in position 12: ordinal not in range(128): 
(gdb) 
```

#### Expected results

I expected to see the `gef>` prompt after starting gdb post-installation.

**Comment by hugsy** [comment]
Are you using UTF-8 as locale as explained in docs?

**Comment by mattherman** [comment]
I see that now:
>>> Note: If your GDB is compiled with Python3, GEF will assume that your environment locales are in UTF-8 (which is the standard). If you use on purpose another locales, you may expect Unicode exceptions preventing many commands to work as expected. Please set up your locales to UTF-8 to have  GEF running smoothly.

Where do I need to change that? Is that something I configure in my OS or `gdb`?

**Comment by mattherman** [comment]
The Debian wiki appears to point me to `/etc/local.gen`.

It looks like I may already have it set to utf-8: `en_GB.UTF-8 UTF-8`

**Comment by hugsy** [comment]
This is a configuration issue, not a bug from gef. Please read the docs carefully. You can also ask for help on the IRC.
Thanks

**Comment by Mod233** [comment]
@mattherman have you finished the problem...
I also meet the problem..
```bash
➜  ~ lolocale -a
C
C.UTF-8
POSIX
en_AG
en_AG.utf8
en_GB.utf8
en_US.utf8
➜  ~ cat /etc/default/locale 
#  File generated by update-locale
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
➜  ~ uname -a
Linux e358c4363737 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by Aeres-u99** [comment]
Setting the locale to en_US.UTF-8 helps and resolves the issue. As said, its the configurtion error.

**Comment by idersan** [comment]
`LC_ALL=en_US.UTF-8 gdb /path/to/your/binary`
this work for me

**Comment by maksimdrachov** [comment]
If like me, you don't get anywhere using en_US.UTF-8, make sure to check it is available:

```bash
locale -a # Check available
LC_ALL=C.UTF-8 gdb ./arm-embedded/max # This works in my case
```

<img width="965" alt="image" src="https://github.com/hugsy/gef/assets/39975120/9faf5dc5-f9d4-42f4-a149-40f177eb9aca">
