### ISSUE TITLE
Checksec is not able to recognize a no-PIE binary

### ISSUE THREAD

**Issue by Vitolog** [hugsy/gef#196]
### Step 1: Describe your environment

  * Operating System: Kali GNU/Linux Rolling
  * Architecture: x86_64
  * GDB version: GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
  * Python version: 3.6

### Step 2: Describe your problem

The checksec command is not able to recognize a no-PIE binary

#### Steps to reproduce

  1. Create an helloWorld.c
  2. Compile it with the following command `gcc -fno-pie -no-pie helloWorld.c -o helloWorld_noPIE`
  3. `readelf -h helloWorld_noPIE` :  the `Type`  field should be marked as `EXEC`
  4. `gdb helloWorld_noPIE` 

#### Observed Results

  * I obtain `PIE: Yes` if the `checksec` command is given 

#### Expected results

  * `PIE: No`

**Comment by hugsy** [comment]
Cannot reproduce, works as expected:
![gef](https://user-images.githubusercontent.com/590234/33896407-9796cc20-df17-11e7-9739-63f49692c6cf.png)

**Comment by Vitolog** [comment]
Below my output
![test](https://user-images.githubusercontent.com/15886528/33902349-07e9a594-df75-11e7-8b5d-3cb48d8b235f.jpg)

**Comment by hugsy** [comment]
Your locales aren't set to `en_UTF8` as explained in the docs, therefore the `checksec` command fails to retrieve the correct value given back by `readelf`.
