### ISSUE TITLE
Update links to raw.githubusercontent.com

### ISSUE THREAD

**Issue by integeruser** [hugsy/gef#208]
Hello,

not really an issue, but maybe you'd want to consider updating (e.g. in the README) links like `https://github.com/hugsy/gef/raw/master/gef.py` to `https://raw.githubusercontent.com/hugsy/gef/master/gef.py`:
```sh
fcagnin@kappa ~> curl https://github.com/hugsy/gef/raw/master/gef.py
<html><body>You are being <a href="https://raw.githubusercontent.com/hugsy/gef/master/gef.py">redirected</a>.</body></html>
```

**Comment by hugsy** [comment]
The example shows the the command line using `wget` which follows HTTP redirect. `curl` needs the `-L` switch for that.

**Comment by integeruser** [comment]
Sure, just wanted to point it out since maybe you were not aware of the redirection.

**Comment by hugsy** [comment]
I was :smile: That's why I use `wget` and not `curl` for the quick start (as I imagined most people would just copy/paste the command directly)

**Comment by integeruser** [comment]
It makes sense. I have the habit of using `curl` instead of `wget` because the latter is not present by default in some systems (e.g. macOS). Feel free to close the issue 🙂
