### ISSUE TITLE
Ability to display GDB messages after the gef context

### ISSUE THREAD

**Issue by wbowling** [hugsy/gef#209]
Currently if you hit a breakpoint, get a segfault, etc, the message from gdb is displayed above the gef context and can be easy to miss or be pushed offscreen.

Is it possible to have a config setting to show the messages below the context instead of above? If it's not possible due to where the gdb hook happens, something similar to pedas [Stopped reason](https://github.com/longld/peda/blob/master/peda.py#L4416) would be a good alternative

**Comment by hugsy** [comment]
If messages from the output are important to you, I suggest redirect the context to a different TTY. See https://gef.readthedocs.io/en/master/commands/context/#redirecting-context-output-to-another-ttyfile for more info.

**Comment by hugsy** [comment]
@wbowling Is there anything else you need to do/know ? Can we close that ? If not, you must be more clear about what you mean by "message from gdb" being above or below.

**Comment by wbowling** [comment]
I had the threads context hidden (can take up a lot of the screen for some apps) and there was no way to tell why gdb was halted (breakpoint, segfault, etc) or see the output from breakpoint commands.

It's not a bit deal, I just thought if it was easy to show the gdb output after the gef context instead of before it then it would be a convenient config setting to have.

**Comment by hugsy** [comment]
> I had the threads context hidden (can take up a lot of the screen for some apps) and there was no way to tell why gdb was halted (breakpoint, segfault, etc) or see the output from breakpoint commands.

So you can:

 1. if you hide the `threads` pane, simply use the command `info program` to see why the execution stopped
 1. You can easily hook that info to be displayed every time the context is, using `gef_on_stop_hook`
 1. You can always adjust the number of displayed lines of the backtrace using `gef config context.nb_lines_backtrace` Set it to 1 and it will take only line on your screen.

The reason for stopping the execution is a thread related information, and so has no place as part of the other panes (especially considering how easy it is to customize to your specific need). So I don't see a way for a code change, but you might be interested in playing the `context.*` configuration settings.

Cheers

**Comment by wbowling** [comment]
> If you hide the threads pane, simply use the command info program to see why the execution stopped
> You can easily hook that info to be displayed every time the context is, using gef_on_stop_hook

Ah nice I didn't know about that, that should work for what I was after.

If there are a lot of threads then `gef config context.nb_lines_backtrace` wont change the amount of space it takes up, eg when set to 1 and debugging apache (which is why I have it disabled 😁  ):

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1418260/36700968-97a8f2ae-1ba5-11e8-8623-2a931961552e.png">

**Comment by hugsy** [comment]
This might be a bug then, I will check on that...

What is your output is simply run 
```
backtrace 1
```
?

**Comment by hugsy** [comment]
I confirm the bug.

I will add asap a different option like you mentioned to limit the number of visible threads.

Thanks for reporting it.

**Comment by hugsy** [comment]
Hi @wbowling 

It is now implemented. You can filter the number of threads visible via the setting `context.nb_lines_threads`:
![](https://i.imgur.com/JvoCety.png)

I'll leave the ticket open for you to test.

Thanks!

**Comment by wbowling** [comment]
Great that works perfectly, thanks! :)
