### ISSUE TITLE
Request: Implement gdb-peda's find or searchmem

### ISSUE THREAD

**Issue by uafio** [hugsy/gef#21]
Hello hugsy,

Is it possible to port peda's find or searchmem, it really works well in finding bytes for either manual rop searching or ascii strings like "/bin/sh".

Thanks

**Comment by hugsy** [comment]
I usually use the `ropgadget` command for this:
```
gef➤  ropgadget string=Vuln..able
[+] Using binary: /home/chris/code/gef/tests/printf
Strings information
============================================================
0x000000000040079c : Vulnerable
```

Can you specify how PEDA `find` command is different?

**Comment by boaster** [comment]
gdb-peda$ find /bin/sh
Searching for '/bin/sh' in: None ranges
Found 1 results, display max 1 items:
libc : 0x7ffff7b91cdb --> 0x68732f6e69622f ('/bin/sh')
gdb-peda$ find /bin
Searching for '/bin' in: None ranges
Found 9 results, display max 9 items:
   libc : 0x7ffff7b91cdb --> 0x68732f6e69622f ('/bin/sh')
   libc : 0x7ffff7b9358f ("/bin:/usr/bin")
   libc : 0x7ffff7b93598 --> 0x2d2720006e69622f ('/bin')
   libc : 0x7ffff7b93a69 ("/bin/csh")
   libc : 0x7ffff7b94c7e ("/bindresvport.blacklist")
[stack] : 0x7fffffffeded ("/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games")
[stack] : 0x7fffffffee00 ("/bin:/sbin:/bin:/usr/games:/usr/local/games")
[stack] : 0x7fffffffee0b ("/bin:/usr/games:/usr/local/games")
[stack] : 0x7fffffffee4d ("/bin/zsh")
gdb-peda$ find AAAA
Searching for 'AAAA' in: None ranges
Not found
gdb-peda$ find /bin/sh libc
Searching for '/bin/sh' in: libc ranges
Found 1 results, display max 1 items:
libc : 0x7ffff7b91cdb --> 0x68732f6e69622f ('/bin/sh')
gdb-peda$ find /bin/sh ld
Searching for '/bin/sh' in: ld ranges
Not found
gdb-peda$

**Comment by hugsy** [comment]
Well again `gef` already offers this possibility via the `ropgadget` command:
```
gef➤  ropgadget binary=/lib/x86_64-linux-gnu/libc-2.22.so string=/bin/... offset=0x00007ffff7a37000
[+] Using binary: /lib/x86_64-linux-gnu/libc-2.22.so
Strings information
============================================================
0x00007ffff7bd58bb : /bin/sh\
0x00007ffff7bd79d5 : /bin/csh
```

But I see your point. I will try to implement a convenient command for that.

**Comment by boaster** [comment]
Yes it does, but where is this:
ropgadget binary=/lib/x86_64-linux-gnu/libc-2.22.so string=/bin/... offset=0x00007ffff7a37000
and where is this:
find /bin/sh

**Comment by boaster** [comment]
Thank you :)

**Comment by lieanu** [comment]
Hi, 

`searchmem` maybe more useful, for example the shardow memory map:

```asm
gdb-peda$ vmmap 
Start              End                Perm      Name
0x00400000         0x00401000         r-xp      /mnt/hgfs/lieanu/ctf/32c3/pwn/readme/readme.bin
0x00600000         0x00601000         rw-p      /mnt/hgfs/lieanu/ctf/32c3/pwn/readme/readme.bin
0x00002aaaaaaab000 0x00002aaaaaace000 r-xp      /lib/x86_64-linux-gnu/ld-2.19.so
0x00002aaaaaace000 0x00002aaaaaad0000 r--p      [vvar]
0x00002aaaaaad0000 0x00002aaaaaad2000 r-xp      [vdso]
0x00002aaaaaad2000 0x00002aaaaaad4000 rw-p      mapped
0x00002aaaaaaef000 0x00002aaaaaaf2000 rw-p      mapped
0x00002aaaaaccd000 0x00002aaaaacce000 r--p      /lib/x86_64-linux-gnu/ld-2.19.so
0x00002aaaaacce000 0x00002aaaaaccf000 rw-p      /lib/x86_64-linux-gnu/ld-2.19.so
0x00002aaaaaccf000 0x00002aaaaacd0000 rw-p      mapped
0x00002aaaaacd0000 0x00002aaaaae8b000 r-xp      /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaaae8b000 0x00002aaaab08a000 ---p      /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaab08a000 0x00002aaaab08e000 r--p      /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaab08e000 0x00002aaaab090000 rw-p      /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaab090000 0x00002aaaab095000 rw-p      mapped
0x00007ffffffde000 0x00007ffffffff000 rw-p      [stack]
0xffffffffff600000 0xffffffffff601000 r-xp      [vsyscall]
gdb-peda$ search
search     searchmem  
gdb-peda$ searchmem "Please overwrite the flag"
Searching for 'Please overwrite the flag' in: None ranges
Found 2 results, display max 2 items:
readme.bin : 0x400976 ("Please overwrite the flag: ") #shadow memory map which in DATA section
readme.bin : 0x600976 ("Please overwrite the flag: ")
```

And ROPgadget cannot do this.

**Comment by hugsy** [comment]
@lieanu This may be true, `ROPgadget` does not do this, but `gdb` does natively (https://sourceware.org/gdb/onlinedocs/gdb/Searching-Memory.html) that's why I never had to implement this command.

But @boaster had a point, it would be better to have a "simpler" command to grep in memory.

Thanks for your feedbacks :+1:

**Comment by hugsy** [comment]
You can test the new command `search-pattern` (alias `grep`) to do that:
![](https://i.imgur.com/enxEdQd.png)

**Comment by lieanu** [comment]
:+1: 

```asm
gef> grep "Please overwrite the flag"
[+] Searching 'Please overwrite the flag' in memory
0x400976-0x400991 ->  "Please overwrite the flag: " 
0x600976-0x600991 ->  "Please overwrite the flag: " 
gef> 
```

**Comment by boaster** [comment]
It works well, thanks
