### ISSUE TITLE
Does gef-remote support restarting process on remote host?

### ISSUE THREAD

**Issue by pgrohe** [hugsy/gef#214]
### Step 0: Preliminary (remove this part if all good)

  * Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
    Yes, read the docs for [gef-remote](https://gef.readthedocs.io/en/master/commands/gef-remote/).  It mentions a -E and -p option but does not present examples of their usage.
  * Did you check closed [issues](https://github.com/hugsy/gef/issues)?
    Found [this Merge request](https://github.com/hugsy/gef/pull/50) that discusses the issue.  It mentions a -f flag to gef-remote in the first comment but I cannot find any trace of that.

  * Did you use the latest version of GEF from `master` branch?
   Maybe a week or two old now.  I will test again on latest branch.  My 'issue' is more a question / documentation request.

### Step 1: Describe your environment

  * Operating System:  Ubuntu 17.10 (gdb client) / Ubuntu 14.04.5 (gdbserver)
  * Architecture: x64 (gdb client) / x32 (gdb server)
  * GDB version (including the Python library version):
   Believe it is 8.0.1, default version for 17.10 apt-get install of gdb.  Python version is 3.x

### Step 2: Describe your problem

I have been unable to figure out how to connect to a remote, specify the file I want to debug, debug through repeated executions without having to restart gdbserver on the remote.

#### Expected results

I would like to be able to use GEF to connect to a remote gdbserver and debug an executable through several executions without manually restarting gdbserver on the remote.

I don't have a whole lot of experience with gdbserver so I may just need some help understanding it & how to use it with GEF (gdbserver --multi, target extended-remote, set remote exec-file, etc....)

Documentation should include this use-case more clearly (happy to help with that once I have a better understanding).

**Comment by pgrohe** [comment]
Note that I've used gef-remote successfully in normal gdbserver mode, but the server exits on execution of the inferior.

I tried using gdbserver with the  --multi option but wasn't able to determine how I should be telling it which file to execute.  I believe I tried set remote exec-file and it told me file was not found (locally on my gdb client machine).  I will try to get a paste of a sample session this evening.

**Comment by pgrohe** [comment]
This [Stack Exchange answer](https://electronics.stackexchange.com/a/307191) lays out how this is done without GEF. 

What I'm not sure of is 

- with GEF do I need to start gdbserver with a filename to debug?  Seems like normally with --multi it's started without
- On the GEF client side, I need to start gdb without a file & then 'set remote-exec file' before connecting with gef-remote?
- When I do run the command gef-remote I need to use the -E flag for extended-remote connection?  Do I need the -p for a PID?  Cause if I started my gdbserver without an filename, there won't be one to reference.

**Comment by pgrohe** [comment]
Remote
```
mbe_test@mbe-testlab:~/mbe_dev/bin$ gdbserver --multi :1234 ./lab3C
Process ./lab3C created; pid = 1125
Listening on port 1234
Remote debugging from host 192.168.122.1
gdbserver: unable to open /proc file '/proc/1125/status'
gdbserver: unable to open /proc file '/proc/1125/status'
Cannot attach to lwp 1125: No such file or directory (2)
```

GDB Client
```
gef➤  gef-remote -p 1125 -E 192.168.122.55:1234
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
warning: Could not load vsyscall page because no executable was specified
0xb7fdf030 in ?? ()
[+] Connected to '192.168.122.55:1234'
[+] Attaching to 1125
[!] Command 'gef-remote' failed to execute properly, reason: Attaching to process 1125 failed

```

**Comment by pgrohe** [comment]
I think this might be my issue:
```
mbe_test@mbe-testlab:~$ gdbserver --version
GNU gdbserver (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "i686-linux-gnu"
mbe_test@mbe-testlab:~$ 
```

gdbserver version too old as [described here](https://sourceware.org/ml/gdb-patches/2016-03/msg00457.html) ?

**Comment by pgrohe** [comment]
To update, I've successfully achieved what I was hoping to do using the standard gdb commands.

The steps are:

1. Have a copy of the binary on both the gdb server and the gdb client machine
2. Start gdbserver with `gbdserver --multi 0.0.0.0:1234` . No exectuable provided
3. Launch gdb (with gef) without providing an exectuable as a command line arg
4. Connect to the gdbserver with target extended-remote <IP>:<Port>
5. On the gdb client's gdb CLI `set remote exec-file <path to the file on the gdb server machine>`
6. On the gdb client's gdb CLI file `<path to the file on gdb client machine>`
7. Run and re-run in gdb on client to your heart's content

I've been unable to replicate the above using gef-remote command

**Comment by hugsy** [comment]
Hi @pgrohe ,

This Issue section is for **bug** only, it's not a forum or a StackOverflow like forum. It's also not the right place for learning GEF, GDB and/or GDBServer. I suggest you use Freenode's ##gef and ##gdb (maybe others like ##re or ##asm) IRC channels for that, you'll get more replies.

There are a few discrepancies in the documentation of `gef-remote`, I intend to fix that. `gef-remote` command was just recently improved, so this might help you out, but to be honest I got lost in trying to understand what your issue was. So come to the IRC instead with clear question for others to understand, they might be able to help you out.

Cheers.
