### ISSUE TITLE
instruction length not being populated

### ISSUE THREAD

**Issue by bannsec** [hugsy/gef#215]
* Operating System: Debian 9
  * Architecture: x86_64
  * GDB version (including the Python library version): GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
  * python version (in gdb): 3

### Step 2: Describe your problem
instruction_length variable is being set to None, which is causing exceptions when it is used. In my case, it is being hit by the format string vulnerability checking routine (`FormatStringBreakpoint`, line 2958).

```
Python Exception <class 'TypeError'> unsupported operand type(s) for *: 'int' and 'NoneType': 
```

Binary is 32-bit running on my 64-bit OS.

#### Steps to reproduce

  1. Create a binary that utilizes printf
  1. Turn on Format String helper in gef
  1. Run it

#### Observed Results

  * Python Exception <class 'TypeError'> unsupported operand type(s) for *: 'int' and 'NoneType': 

#### Expected results

  * Expect no errors
  * Expect format string to continue after checking the params

**Comment by hugsy** [comment]
Hi @bannsec 

I cannot reproduce.
Can you be more explicit about your setup environment and binary?
Also provide the output with debug mode enabled (`gef config gef.debug 1`)?

Thanks

**Comment by bannsec** [comment]
oddly enough, i can't reproduce anymore either... definitely was behaving that way but now is not. i'll go ahead and close. reopen if i can reliably recreate.

**Comment by hugsy** [comment]
No problem, but if you do so, please provide the debug output. 

Cheers
