### ISSUE TITLE
heap bins problem

### ISSUE THREAD

**Issue by lhlsec** [hugsy/gef#217]
### Step 0: Preliminary (remove this part if all good)

  * Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * Did you check closed [issues](https://github.com/hugsy/gef/issues)?
  * Did you use the latest version of GEF from `master` branch?

### Step 1: Describe your environment

  * Operating System:Ubuntu 16.04
  * Architecture:x64
  * GDB version (including the Python library version):7.11.1

### Step 2: Describe your problem
I run the follow command

gef➤  heap bins

it show the problem as follows

[!] Command 'heap bins fast' failed to execute properly, reason: 'GlibcChunk' object has no attribute 'addr'

what should I do then?
#### Steps to reproduce

  1.
  1.
  1.

#### Observed Results

  * What happened?  This could be a description, log output, etc.

#### Expected results

  * What did you expect to happen?

#### Traces

Feel free to include in this section screenshots, stack traces, or

```
the exact code here to reproduce the problem
```

By enabling `gef.debug` setting (`gef config gef.debug 1`), `gef` will display a
full stack trace if an exception occurs. It is a good idea to copy/paste it here
as it contains all useful information for being able to reproduce.

**ProTip:** Using GitHub, you can easily add files to your issues by a simple
Drag n'Drop.

**Comment by hugsy** [comment]
> what should I do then?

Start by giving more details.

**Comment by hugsy** [comment]
Cleanup
