### ISSUE TITLE
GlibcChunk

### ISSUE THREAD

**Issue by Ycloub** [hugsy/gef#219]
Command 'heap bins fast' failed to execute properly, reason: 'GlibcChunk' object has no attribute 'addr'

**Comment by hugsy** [comment]
Yes I am aware of this bug, it is already fixed in `dev` and will be soon merged to `master`.

**Comment by hugsy** [comment]
Fixed by 0a3720cebae0f685c24905c1eb3856598c5cf537 (now in `master`), will be part of the next release. Closing the ticket.
