### ISSUE TITLE
Enhance heap command.

### ISSUE THREAD

**Issue by lieanu** [hugsy/gef#22]
Not a bug, just a proposal.
[https://github.com/rogerhu/gdb-heap](https://github.com/rogerhu/gdb-heap)
[https://github.com/cloudburst/libheap](https://github.com/rogerhu/gdb-heap)

**Comment by uafio** [comment]
This would be awesome :)

**Comment by sh3dow** [comment]
@lieanu you can add https://github.com/mcfunley/php-heap to the list 
[This is a gdb extension that can be used for examining the objects in memory in a running PHP process or core dump. It walks the low-level PHP memory structures to do this and should work without code modifications.]

**Comment by hugsy** [comment]
Yes this is a long overdue. I've been thinking about improving the `heap` command for quite some time.

**Comment by hugsy** [comment]
This should be a good start.

If you have more ideas on commands to implement, submit more details. Thanks again for the feedbacks !!
