### ISSUE TITLE
TODO for 2018.04

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#223]
List of all the (small) final items to complete before publishing the new release:

 - [x] Move `binja_gef.py` , `ida_gef.py`, `gef.sh`  and `.new_release.sh` to `scripts/`
 - [x] Edit the docs consequently

**Comment by Grazfather** [comment]
We really need to fix #224.

**Comment by hugsy** [comment]
Added to milestone, I'll work on it during the week (or weekend)

**Comment by hugsy** [comment]
Release time!
