### ISSUE TITLE
Move away from Travis-CI

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#226]
Possible alternatives:

  * https://codeship.com
  * https://drone.io ($$$ - no free offer)
  * ~~https://wercker.com~~ (down it seems)
  * https://www.gocd.org (In-House but would allows deploying agents on Qemu VMs)

**Comment by cclauss** [comment]
Why the move away from Travis?  Have you considered [Circle CI](https://circleci.com)?

**Comment by hugsy** [comment]
Because it's poorly suited for testing gef on multiple architecture and uses super old packages. Not sure I see the difference between CircleCI and TravisCI, can you test on non x86 architectures ? Or at least deploy easily VMs that do?

**Comment by cclauss** [comment]
If you can put onto https://hub.docker.com a Docker image that houses [the environment](https://hub.docker.com/u/vmware) that you want then both Travis CI and Circle CI can mount it and run the tests inside of it.  Pre-built images can have ready-to-run GDB linked into the Python of your pleasure and they will load in seconds.  Circle CI might be a bit faster and more modern than Travis CI but they are both approx equally capable.

**Comment by cclauss** [comment]
* https://circleci.com/docs/2.0/build
* https://docs.travis-ci.com/user/reference/overview Linux and Mac on x86

**Comment by hugsy** [comment]
I don't see pros for changing from Travis-CI to Circle-CI to make tests easier (looks 100% the same). And I don't see how Docker would help in any way. Can you clarify that?

**Comment by cclauss** [comment]
Docker can help because we can:
* build the GDB linked to Python 2 in a Docker image once and test with it 1000 times
* build the GDB linked to Python 3 in a Docker image once and test with it 1000 times
* test start up time takes seconds, not minutes

**Comment by cclauss** [comment]
Would running VMware inside of a Docker container help to simulate non-x86 environments?
* https://hub.docker.com/u/vmware

**Comment by Grazfather** [comment]
I am a fan of circle, but probably just because I've used it before.

One issue is that they run everything with docker, and I am not sure if they run them privileged. Without that, `ptrace` won't work.

**Comment by hugsy** [comment]
Did you test it for gef ?

**Comment by hugsy** [comment]
Can be closed with #324

**Comment by Grazfather** [comment]
Done!

**Comment by cclauss** [comment]
Eight undefined names in ./scripts/ida_gef.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/hugsy/gef on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./scripts/ida_gef.py:149:35: F821 undefined name 'CIC_ITEM'
        return idc.SetColor(addr, CIC_ITEM, color)
                                  ^
./scripts/ida_gef.py:170:54: F821 undefined name 'Structs'
        for (struct_idx, struct_sid, struct_name) in Structs():
                                                     ^
./scripts/ida_gef.py:184:41: F821 undefined name 'StructMembers'
        res = {struct_name: [x for x in StructMembers(self.GetStructByName(struct_name))]}
                                        ^
./scripts/ida_gef.py:195:18: F821 undefined name 'Structs'
        for s in Structs():
                 ^
./scripts/ida_gef.py:208:48: F821 undefined name 'CIC_ITEM'
            idc.SetColor(_current_instruction, CIC_ITEM, _current_instruction_color)
                                               ^
./scripts/ida_gef.py:213:38: F821 undefined name 'GetColor'
        _current_instruction_color = GetColor(_current_instruction, CIC_ITEM)
                                     ^
./scripts/ida_gef.py:213:69: F821 undefined name 'CIC_ITEM'
        _current_instruction_color = GetColor(_current_instruction, CIC_ITEM)
                                                                    ^
./scripts/ida_gef.py:214:44: F821 undefined name 'CIC_ITEM'
        idc.SetColor(_current_instruction, CIC_ITEM, 0x00ff00)
                                           ^
8     F821 undefined name 'CIC_ITEM'
8
```
