### ISSUE TITLE
A python exception.

### ISSUE THREAD

**Issue by lieanu** [hugsy/gef#23]
Hey,

I'm not sure if this is a bug.

MIPS binary remote debug.
![image](https://cloud.githubusercontent.com/assets/3104641/14291118/8bf89dde-fb94-11e5-8c28-49140e9060da.png)

**Comment by hugsy** [comment]
There are a lot of problem hard to solve with the regular `target` command from `gdb` so I have implemented another which should work better: see https://gef.readthedocs.org/en/latest/features/#gef-remote-debugging 

If it is still triggers exception, please provide more details.

**Comment by lieanu** [comment]
```shell
$ gdb -q dwarfdump
gef loaded, `gef help' to start, `gef config' to configure
35 commands loaded (17 sub-commands), using Python engine 2.7
Reading symbols from dwarfdump...done.
gef> b putchar
Breakpoint 1 at 0x401770
gef> r /bin/ps
Starting program: ..../dwarfdump /bin/ps
....
Breakpoint 1, putchar (c=c@entry=10) at putchar.c:26
26      putchar.c: No such file or directory.
gef> heap arenas 
[+] Listing active arena(s):
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Error occurred in Python command: Cannot convert value to int.
gef> heap bins
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Error occurred in Python command: Cannot convert value to int.: 
Error occurred in Python command: Error occurred in Python command: Cannot convert value to int.
```

[Binary Dowload HERE](https://github.com/lieanu/files/raw/master/binary/dwarfdump)

**Comment by sigma-d** [comment]
In function context_regs(), if str(new_value)=='void' then long(new_value) will cause this exception.

**Comment by hugsy** [comment]
@sigma-d `new_value` in `context_regs()` should never produce a string. Can you tell me how to reproduce? And also give me the output of your `info reg` command when this exception occurs? 

Thanks.

**Comment by sigma-d** [comment]
cmdline I used:
./openwrt/trunk/staging_dir/toolchain-mipsel_mips32_gcc-4.8-linaro_musl-1.1.11/bin/mipsel-openwrt-linux-musl-gdb --data-directory /usr/share/gdb ./openwrt-malta-le-vmlinux-initramfs.elf
./qemu-2.6.0-rc3/mipsel-softmmu/qemu-system-mipsel -gdb tcp::4321 -S -nographic -m 256 -kernel openwrt-malta-le-vmlinux-initramfs.elf

openwrt-malta-le-vmlinux-initramfs.elf can get from:
https://downloads.openwrt.org/snapshots/trunk/malta/generic/

gdb version:
GNU gdb (GDB) 7.8

It looks like this issue happens after context_regs() got a value "void"(type:gdb.Value) from register "$status"

**Comment by hugsy** [comment]
It looks related to #13 (i.e. OpenWRT support) ?

If so, OWRT support is a WIP so if you can submit a patch or PR that would break with the existing arch, I'll be happy to integrate it.
