### ISSUE TITLE
Add pep8 formatting checks to test

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#232]
We should slacken some of the rules, e.g. 120 chars per line instead of 80.

Didn't we at one point have a tweaked ruleset?

**Comment by Grazfather** [comment]
We have a _pylintrc_ in _tests/_.

**Comment by cclauss** [comment]
Why not just run __autopep8__ or __yapf__ on the entire codebase?

**Comment by Grazfather** [comment]
We don't love all the pep8 (e.g. 80 chars per line is crazy).

Once we've figured out a good side of rules to ignore, then maybe we could do that, but until then I think I want to manually figure out which set of rules make sense.

At that point, it's probably a good idea to turn that on locally, but we still need to test against pep8 in our ci.

**Comment by hugsy** [comment]
PEP8 is too restrictive, so this won't be done.
Plus another (better) issue is open for that (https://github.com/hugsy/gef/issues/313).
