### ISSUE TITLE
Can we use the popular 'six' module instead of custom code?

### ISSUE THREAD

**Issue by cclauss** [hugsy/gef#238]
https://github.com/hugsy/gef/blob/master/gef.py#L115-L124 contains a lot of custom code that is generally available in a more supported way in the popular [six module](http://six.readthedocs.io).

### Step 0: Preliminary (remove this part if all good)

  * Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * Did you check closed [issues](https://github.com/hugsy/gef/issues)?
  * Did you use the latest version of GEF from `master` branch?

### Step 1: Describe your environment

  * Operating System:
  * Architecture:
  * GDB version (including the Python library version):

#### Steps to reproduce

  1.
  1.
  1.

#### Observed Results

  * What happened?  This could be a description, log output, etc.

#### Expected results

  * What did you expect to happen?

#### Traces

Feel free to include in this section screenshots, stack traces, or

```
the exact code here to reproduce the problem
```

By enabling `gef.debug` setting (`gef config gef.debug 1`), `gef` will display a
full stack trace if an exception occurs. It is a good idea to copy/paste it here
as it contains all useful information for being able to reproduce.

**ProTip:** Using GitHub, you can easily add files to your issues by a simple
Drag n'Drop.

**Comment by Grazfather** [comment]
We don't want any external dependencies, so this will not happen.
