### ISSUE TITLE
Consider converting commands to use classmethods

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#239]
It seems most (all?) commands (derived from `GenericCommand`) don't need to keep state. We could prevent initializing them, convert all methods to `@classmethod` and call directly on the class object.

We'd want to see whether this speeds things up. It'll add many lines of code (with all the decorators) so I don't think we should care to do it unless there's a speed benefit.

**Comment by fibonascii** [comment]
@Grazfather At the moment all of gef is contained in gef.py so I do understand the concern for adding bloat to the codebase. However if we were to move a lot of these commands into class libraries, possibly even contained in a temperate repository we could potentially lower the number of lines of code in gef.py as well as implement this refactoring. Thoughts?

**Comment by Grazfather** [comment]
That'll never happen. One of the features of gef is one line grab and install.

**Comment by fibonascii** [comment]
Sorry I'm kind of confused. We pull down an installation script that setups up the whole repository right? If we moved the classes into modules they would get pulled down as well via that same online and in the code just import the module into gef.py

**Comment by fibonascii** [comment]
That being said, I'm gonna start trying to fill the initial request of the issue and setup the classmethods and do some profiling and see if it has any impact on performance positive or negative

**Comment by hugsy** [comment]
> Sorry I'm kind of confused. We pull down an installation script that sets up the whole repository right? If we moved the classes into modules they would get pulled down as well via that same one line and in the code just import the module into gef.py

None of the scripts are mandatory. `gef.py` no matter how you get it (via the script, `wget`, copy/paste) is everything for gef to work. 

For extra external features, use the `gef.extra_plugins_dir` setting.
