### ISSUE TITLE
[Performance] Lower display latency from IO by buffering function outputs

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#244]
Create a decorator to redirect output from `print` calls (stdout) into a buffer that can be fflushed on function exit.

```python
pi import profile; profile.run("myfunc(<args>)", sort="<mykey>")
```

**Comment by hugsy** [comment]
First gist with 3df0570

**Comment by Grazfather** [comment]
And you can do `profile.run("gdb.execute('context')")` etc. to profile commands as if they were typed in.

Though it won't accurately measure io. `timeit` (as you said) for that.
