### ISSUE TITLE
str.format() with an invalid string format specifier

### ISSUE THREAD

**Issue by cclauss** [hugsy/gef#245]
https://travis-ci.org/hugsy/gef/jobs/363039696#L619-L621  Fails in both Python 2 and Python 3.

["{cmd:<25s} -- {help:{w}s} {aliases:s}"](https://github.com/hugsy/gef/blob/master/gef.py#L8155) is not a valid string format specifier for str.format().

**Comment by Grazfather** [comment]
So it's only invalid if `w` is negative. Good find.
