### ISSUE TITLE
Still python exception.

### ISSUE THREAD

**Issue by lieanu** [hugsy/gef#25]
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1 + python2.7
![image](https://cloud.githubusercontent.com/assets/3104641/14895391/f514740a-0daa-11e6-8ae1-52af0464e620.png)

**Comment by hugsy** [comment]
Hi @lieanu ,

I appreciate all your bug reports. Please try to give me more information about your context (even a test C code or a binary) so I can try to reproduce it.

Thanks.

**Comment by lieanu** [comment]
```shell
$ gdb -q dwarfdump
gef loaded, `gef help' to start, `gef config' to configure
35 commands loaded (17 sub-commands), using Python engine 2.7
Reading symbols from dwarfdump...done.
gef> b putchar
Breakpoint 1 at 0x401770
gef> r /bin/ps
Starting program: ..../dwarfdump /bin/ps
....
Breakpoint 1, putchar (c=c@entry=10) at putchar.c:26
26      putchar.c: No such file or directory.
gef> heap arenas 
[+] Listing active arena(s):
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Error occurred in Python command: Cannot convert value to int.
gef> heap bins
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Error occurred in Python command: Cannot convert value to int.: 
Error occurred in Python command: Error occurred in Python command: Cannot convert value to int.
```

[Binary Dowload HERE](https://github.com/lieanu/files/raw/master/binary/dwarfdump)

**Comment by lieanu** [comment]
Sorry for the lack of [shared library](https://github.com/lieanu/files/raw/master/binary/libdwarf.so).

**Comment by hugsy** [comment]
Hi @lieanu ,

It should be fixed. Pull the latest version and try again.

**Comment by lieanu** [comment]
Awesome, It works now.
And another tiny problem, heap chunk will print some meaningless blank space.

![image](https://cloud.githubusercontent.com/assets/3104641/14934539/989919ba-0ee5-11e6-8ccc-4e7f55026181.png)

**Comment by hugsy** [comment]
Lol :-D it is fixed. Feel free to close this issue when you confirm it is fixed for you too  

Thanks for all your feedbacks:+1:

**Comment by lieanu** [comment]
Perfect now 👍
