### ISSUE TITLE
Where are the useful aliases like "dc", "dq" ?

### ISSUE THREAD

**Issue by Escapingbug** [hugsy/gef#252]
### Step 1: Describe your environment

  * Operating System: Manjaro linux
  * Architecture:x86_64
  * GDB version (including the Python library version): 8.1, python3.6

### Step 2: Describe your problem
Many aliases are gone? Most of them found to be useful to me, like "dc" or "dq". They are saving a lot
of time to type the long form.

#### Steps to reproduce

No commands found! Try them!

#### Observed Results

  * What happened?  This could be a description, log output, etc.

#### Expected results

  * What did you expect to happen?

#### Traces

Feel free to include in this section screenshots, stack traces, or

```
the exact code here to reproduce the problem
```

By enabling `gef.debug` setting (`gef config gef.debug 1`), `gef` will display a
full stack trace if an exception occurs. It is a good idea to copy/paste it here
as it contains all useful information for being able to reproduce.

**ProTip:** Using GitHub, you can easily add files to your issues by a simple
Drag n'Drop.

**Comment by hugsy** [comment]
All the WinDBG goodness were moved to a dedicated script: 
https://github.com/hugsy/gef-extras/blob/master/scripts/windbg.py#L204-L225

It also provides a lot of extra features that mimics the ones provided by WinDBG.

Note that if you only want the aliases, a quick way is using the `~/.gef.rc` file, in the `aliases` section, something like:

```
[aliases]
x = info functions
u = display/16i
da = display/s
dt = pcustom
dq = hexdump qword
dd = hexdump dword
dw = hexdump word
db = hexdump byte
eq = patch qword
ed = patch dword
ew = patch word
eb = patch byte
ea = patch string
dps = dereference
bp = break
bl = info breakpoints
bd = disable breakpoints
bc = delete breakpoints
be = enable breakpoints
tbp = tbreak
s = grep
pa = advance
kp = info stack
ptc = finish
uf = disassemble
```

Then either start gdb, or reload gef (`gef restore`).

Cheers.

**Comment by Escapingbug** [comment]
I see.
But I highly suggest we should mention all these in documentation. :)

**Comment by Grazfather** [comment]
I agree! Sorry about that, we certainly shouldn't have stolen aliases from you.

**Comment by hugsy** [comment]
@Escapingbug Good point :)
