### ISSUE TITLE
guess args for syscalls

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#257]
we should be able to determine the name of the syscall and the args, based on the abi.

If we assume linux (we shouldn't) we can put this in the arch.

`is_syscall`
`get_syscall_args`

are probably the only methods we need to add. `man syscall` to see the abis.
Only issue is that we don't know, unless we hardcode, which args are used, unless we backtrack to see which registers were written.

**Comment by daniellimws** [comment]
`is_syscall` will tell the name of the syscall, and `get_syscall_args` will give the arguments passed in?

**Comment by daniellimws** [comment]
This should be called on an `int 0x80`, `syscall` or whatever syscall equivalent for the architecture right?

On any other instructions when this is called we give some error message?

**Comment by Grazfather** [comment]
is_syscall will probably just return whether the current instruction is a syscall instruction. This depends on the architecture, and you'll have to write it for each one.

get_syscall_args will get the args, including the 'arg' which determines which syscall this is.

Not that this means we need to keep a table of syscall numbers for each arch! Maybe this should go into the scripts repo.

**Comment by disconnect3d** [comment]
> Not that this means we need to keep a table of syscall numbers for each arch! Maybe this should go into the scripts repo.

Feel free to steal those from pwndbg:
https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/constants/arm.py

;)

**Comment by daniellimws** [comment]
Can close this?

**Comment by Grazfather** [comment]
So right now it was created as a standalone command. What I think we want eventually is for this to be done _automatically_. Should be a simple change, but we'll need to check the config (for the table) and not crash. See how `context_call` checks the current instruction is a jump, a ret, or a call. We could add a call to `is-syscall` here (as a function, not a command), and if it is, automatically populate the `guessed args` part using `syscall-args`.

So let's keep this open for a bit until we have that done nicely.

**Comment by hugsy** [comment]
Or at first move all those commands to `gef-extras`, before we do a proper integration with `context_code`.

**Comment by hugsy** [comment]
Cleanup
