### ISSUE TITLE
Colorify output of memory dump

### ISSUE THREAD

**Issue by sectroyer** [hugsy/gef#264]
I read this article https://gef.readthedocs.io/en/latest/api/ and I think I know how to add custom command to gef that would do what I want. However I would love to simply overwrite built in gdb command. So would it be possible to that in such a way that, for example:
x/200xw $sp
would show output of this command but with heap/stack/code addresses colorified?

**Comment by hugsy** [comment]
No problem.

Since this is not an issue from GEF, I'm closing the issue. Feel free to ask questions on IRC (freenode, ##gef).

Cheers
