### ISSUE TITLE
Set arch fails due to locale?

### ISSUE THREAD

**Issue by sectroyer** [hugsy/gef#266]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
YES
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
YES
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?
YES

### Step 1: Describe your environment

  * Operating System: Linux TV4 3.10.30 #3 SMP PREEMPT armv7l GNU/Linux
  * Architecture: ARM Smart TV
  * GDB version (including the Python library version): GNU gdb (8.1 p1) 8.1, Python 2.7.1
### Step 2: Describe your problem
Need to put set_arch in random places.

Here: https://github.com/hugsy/gef/issues/263 you mention "wrong locale" could elaborate on that? I can provide more detailed reports just don't want to "spam" issues with stuff that is not needed 😞

**Comment by sectroyer** [comment]
Nope that doesn't help. My locale is same on both boxes, locale command outputs this:
LANG=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE=C
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
setting LC_ALL (either to pl_PL or en_US) like in the link you provided doesn't help. Also I am using python2. What fixes this issue is commenting single line gef source code:
    # Compat Py2/3 hacks
    range = xrange <------- commenting this solved my issue 😄

**Comment by sectroyer** [comment]
You can close this issue. I tested while checking colors issue with latest git and look "something" you did recently resolved it 👍 😄

**Comment by hugsy** [comment]
Ok, that's weird, I didn't change anything regarding the locales, but happy that it's solved.

Cheers.
