### ISSUE TITLE
Threads context tile is always printed

### ISSUE THREAD

**Issue by sectroyer** [hugsy/gef#267]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Linux TV4 3.10.30 #3 SMP PREEMPT armv7l GNU/Linux or
  * Architecture: ARM Smart TV or ARM Pandaboard ES
  * GDB version (including the Python library version): GNU gdb (8.1 p1) 8.1, Python 2.7.1 or GNU gdb (8.1 p1) 8.1, Python 2.7.14 

### Step 2: Describe your problem
I have set nb_lines_threads to 0 and saved config but         self.context_title("threads") for threads is still printed

#### Steps to reproduce
set nb_lines_threads to 0 and save config

#### Observed Results
threads context title is still printed

#### Expected results
with nb_lines_threads set to 0 there is no point in printing context title for context that is empty

**Comment by hugsy** [comment]
Thanks, there is indeed a bug there.

But in your case, if you want to simply not display the threads, you can simply set `-threads` to `gef config context.layout`.

Patch coming up soon...

**Comment by sectroyer** [comment]
I believe this is NOT completely fixed. I still have context thread title on latest git:
<img width="1279" alt="zrzut ekranu 2018-05-14 o 17 22 26" src="https://user-images.githubusercontent.com/6706818/40009001-120fb0a0-57a1-11e8-90a8-25036cd6a481.png">

**Comment by hugsy** [comment]
In the docs, it says that to remove an entire pane, you must edit `context.layout`.
This is working as expected.

**Comment by sectroyer** [comment]
Okay, I see. Tough I still think there is no point in printing empty panes 😃

**Comment by hugsy** [comment]
This way actually shows that the value of the setting is 0.

**Comment by Grazfather** [comment]
Isn't _not_ fixing this inconsistent with #274?

**Comment by hugsy** [comment]
Well, they now behave the exact same way.
