### ISSUE TITLE
Executed lines of code are not visible

### ISSUE THREAD

**Issue by sectroyer** [hugsy/gef#271]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
YES
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
YES
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?
YES

### Step 1: Describe your environment

  * Operating System: Linux TV4 3.10.30 #3 SMP PREEMPT armv7l GNU/Linux or
  * Architecture: ARM Smart TV or ARM Pandaboard ES
  * GDB version (including the Python library version): GNU gdb (8.1 p1) 8.1, Python 2.7.1 or GNU gdb (8.1 p1) 8.1, Python 2.7.14 

Same issue can be observed on www.root-me.org server.

### Step 2: Describe your problem
Executed lines are NOT visible because "grayify" function changes them to black.
#### Steps to reproduce

Starting gef on an ARM box with python 2.7 and stop on breakpoint. Alternatively same issue can be observed on www.root-me.org server.

#### Observed Results
Invisible previous lines of code.
#### Expected results
Seeing the lines
#### Screenshots
In my script I have fixed it by replacing grayify with bold white and seems to work well 😄  I attach screenshots from www.root-me.org

<img width="740" alt="zrzut ekranu 2018-05-09 o 21 18 36" src="https://user-images.githubusercontent.com/6706818/39834985-f89cd2ea-53ce-11e8-9fee-fb4e810f7e4c.png">

<img width="610" alt="zrzut ekranu 2018-05-09 o 21 18 47" src="https://user-images.githubusercontent.com/6706818/39834992-00be393c-53cf-11e8-962b-28139daf4bd0.png">

**Comment by Grazfather** [comment]
That's a problem with your terminal settings, not gef

**Comment by sectroyer** [comment]
What do you mean ? I haven't encountered this issue with ANY other applications and I use terminal apps everyday 😞 All options are set according to "best practices" so no idea what could be wrong 😢

**Comment by hugsy** [comment]
As @Grazfather  said, this is not a GEF issue.

Try this:
```
export TERM=xterm-256color
```
It may solve your issue.

Otherwise you can use [`colortest`](https://packages.ubuntu.com/trusty/utils/colortest) to visualize the palette supported by your terminal. 

Cheers

**Comment by sectroyer** [comment]
@hugsy That's exactly the setting my terminal has. I couldn't find source for colortest but I tried this bash script:
https://askubuntu.com/questions/821157/print-a-256-color-test-pattern-in-the-terminal

But it doesn't look like there is anything wrong with my terminal settings as I have exactly same output:
<img width="560" alt="zrzut ekranu 2018-05-10 o 18 15 22" src="https://user-images.githubusercontent.com/6706818/39880498-499f14f0-547e-11e8-83bd-0b2186beb148.png">

**Comment by Grazfather** [comment]
Try the sixteen colour palette.

**Comment by hugsy** [comment]
@Grazfather Actually, we can close this discussion by simply adding a color setting for previous, current and next instructions when being displayed. Colors in terminal are not really a universal thing unfortunately, so we can kill any future issue like by adding a simple colorizing setting. What do you think?

**Comment by sectroyer** [comment]
@hugsy I think adding an option to choose color is a good idea but still default color for executed lines of assembly should be changed to more "compatible" one. I checked gef and those color testing apps. You use this:
"gray"           : "\033[1;30m",
Which I haven't found in any other apps. Moreover ONLY for gray. Whereas colortest and other apps like that use setting in this format:
        "gray"           : "\033[1;38;5;240m",
Using that for default gray works for me perfectly. Anyway I am poor "at UI" so I would suggest changing default gef gray to something like that 👍 😄

**Comment by hugsy** [comment]
@sectroyer I will test this value for gray too. Can you indicate on which terminal you ran your tests?

**Comment by sectroyer** [comment]
I can confirm this setting works on both on my all ARM devices with latest GEF from git 👍 😄 I use it over SSH from Mac's Terminal app.

**Comment by hugsy** [comment]
I came to the same conclusion, changing the setting did not cause any issue, so it was merged to `master` by 47d921b.

Thanks @sectroyer for reporting the issue.

**Comment by sectroyer** [comment]
No problem, glad we figured it out. I can confirm with latest git all works well for me. Will check other issues I had and report properly remaining stuff.
