### ISSUE TITLE
Trace is always visible

### ISSUE THREAD

**Issue by sectroyer** [hugsy/gef#274]
Your issue will be closed unless you confirm the following:
  * [ ] Did you use the latest version of GEF from `master` branch?
YES
  * [ ] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
YES
  * [ ] Did you check [closed issues](https://github.com/hugsy/gef/issues)?
YES

### Step 1: Describe your environment

  * Operating System: Linux TV4 3.10.30 #3 SMP PREEMPT armv7l GNU/Linux or
  * Architecture: ARM Smart TV or ARM Pandaboard ES
  * GDB version (including the Python library version): GNU gdb (8.1 p1) 8.1, Python 2.7.1 or GNU gdb (8.1 p1) 8.1, Python 2.7.14 

Same issue can be observed on https://www.root-me.org
### Step 2: Describe your problem
trance lines are displayed even with context.nb_lines_backtrace set to 0

#### Steps to reproduce
set context.nb_lines_backtrace to 0
save config and restart gdb.  

#### Observed Results
trace is still displayed. 

#### Expected results
no tarce
 
#### Traces

<img width="1271" alt="zrzut ekranu 2018-05-14 o 17 09 54" src="https://user-images.githubusercontent.com/6706818/40006251-320da1f2-579a-11e8-855d-35cb5e49fadd.png">

**Comment by hugsy** [comment]
Fixed by 8401af7
