### ISSUE TITLE
gef reporting modules are missing

### ISSUE THREAD

**Issue by echobb8** [hugsy/gef#277]
### Step 1: Describe your environment

  * Operating System: Raspian (latest version) from raspberrypi.org
  * Architecture: ARM
  * GDB version (including the Python library version): 7.12+ and/or 8.1 (Tried both Python2.7.13 and Python3.5.3)

#### Steps to reproduce

  1. On a fresh install and upgrade of Raspbian (Raspberry Pi 3B v1.2), I first made sure to install the additional modules here (so I can enjoy the cool features!): `pip2 install --user capstone keystone-engine ropper unicorn` (Tried pip3 version with Python3.5.3)
    - Python 2.7.13; GDB 8.1 (same results with 7.12+ version of GDB)

 2. Quick install of gef: `wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh` and everything looks good.

#### Observed Results

`gdb` results in:

GEF for linux ready, type 'gef' to start, 'gef config' to configure
62 commands loaded for GDB 8.1 using Python engine 2.7
* 5 commands could not be loaded, run 'gef missing' to know why.
gef>

`gef> gef missing`

* Command 'capstone-disassemble' is missing, reason -> Missing 'capstone' package for Python2. Install with 'pip2 install capstone'.
* Command 'assemble' is missing, reason -> Missing 'keystone-engine' package for Python2, install with: 'pip2 install keystone-engine'.
* Command 'ropper' is missing, reason -> Missing 'ropper' package for Python2, install with: 'pip2 install ropper'.
* Command 'set-permission' is missing, reason -> Missing 'keystone-engine' package for Python2, install with: 'pip2 install keystone-engine'.
* Command 'unicorn-emulate' is missing, reason -> Missing 'capstone' package for Python2. Install with 'pip2 install capstone'.

Output of `db -q -nx -ex 'pi print (sys.version)' -ex quit` :

`2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]`

#### Expected results

  * That gef would load without "missing" modules because they are installed at:

`ls -ltr /home/pi/.local/lib/python2.7/site-packages/`
total 44
drwxr-xr-x 3 pi pi 4096 May 17 16:01 usr
drwxr-xr-x 2 pi pi 4096 May 17 16:01 capstone
drwxr-xr-x 2 pi pi 4096 May 17 16:01 capstone-3.0.4.dist-info
drwxr-xr-x 2 pi pi 4096 May 17 16:01 keystone
drwxr-xr-x 2 pi pi 4096 May 17 16:01 keystone_engine-0.9.1.post3.dist-info
drwxr-xr-x 2 pi pi 4096 May 17 16:01 filebytes
drwxr-xr-x 2 pi pi 4096 May 17 16:01 filebytes-0.9.15.dist-info
drwxr-xr-x 6 pi pi 4096 May 17 16:01 ropper
drwxr-xr-x 2 pi pi 4096 May 17 16:01 ropper-1.11.6.dist-info
drwxr-xr-x 4 pi pi 4096 May 17 16:01 unicorn
drwxr-xr-x 2 pi pi 4096 May 17 16:01 unicorn-1.0.1.dist-info

`/home/pi/.local/lib/python2.7/site-packages/` is included in my Python path.

Been trying to figure this one out for awhile now, but I'm lost. Any ideas?

**Comment by echobb8** [comment]
I've tried asking in the IRC channel, but didn't get any responses.

I followed the instructions, however, nothing is working. What "setup"
issue do you suspect this is? I opened an "issue" because I followed
everything as written, but the problem still persists.

**Comment by hugsy** [comment]
If GEF reports that modules are missing, it either means that:
- they are not installed
- there is an issue with the installation, which is my guess for your situation

If `capstone` is missing, then `ropper` will fail to load. Similarly, if `unicorn` and `keystone` are missing too, `set-permission` will fail.

I'd suggest you to check your installation. 

And regarding IRC, people come and go, we all have a life. Don't assure we're just sitting waiting for questions. I wanted to help you when I saw your question (~3 hours later) but you were already gone.

**Comment by blackvesna** [comment]
fixed by using (I'm using Anaconda Python):

`ln -s ~/anaconda3/lib/python3.8/site-packages/ ~/.local/lib/python3.8/site-packages`
