### ISSUE TITLE
Failed to load `unicorn-emulate'

### ISSUE THREAD

**Issue by ghrrr** [hugsy/gef#28]
gdb
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
[*] Failed to load `unicorn-emulate`: 'This command requires the following packages: `unicorn` and `capstone`.'
gef loaded, `gef help' to start, `gef config' to configure
36 commands loaded (17 sub-commands), using Python engine 2.7

-----
Kali-Linux 1.0.1
I've install the dependicies but the error still there.

**Comment by hugsy** [comment]
You seem to have gdb + python2.7 so make sure that you can actually load `unicorn` from python first: 
```bash
$ python2
>>> import unicorn
>>> import capstone
```

Sometimes `capstone` installs its library in `/usr/local/lib` which is not by default in the LD_LIBRARY_PATH. 
So try:
```bash
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib:<add here other locations to find the libs>
```

Cheers

**Comment by ghrrr** [comment]
Hi,
I've tried as your suggest..
import capstone >> successful

import unicorn >> can't import due to error
`ImportError: No module named unicorn`

`/usr/lib64/libunicorn.a
/usr/lib64/libunicorn.so
/usr/lib64/libunicorn.so.1`

then I tried,
'$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib:/usr/lib64'

nothing happen
trying to import unicorn, still import error.

Thanks

**Comment by hugsy** [comment]
Your problem is not an issue from `gef` but an installation issue from `unicorn`. 

I suggest you follow very carefully the compilation & installation procedure of the project. When your install of `unicorn` will be successful, you will be able to use `unicorn` in `gef`. If you find a bug in the install of `unicorn`, I suggest you to drop an issue on the project GitHub page.

Therefore I am closing the issue.
Good luck.
