### ISSUE TITLE
coredump when catching exec

### ISSUE THREAD

**Issue by zrlw** [hugsy/gef#291]
1. ENV
Operating System: SuSE Enterprise 12 SP 2
Architecture: x86-64
GNU gdb (GDB; SUSE Linux Enterprise 12) 7.11.1 
Python 2.7.9

2. Problem
coredump when catching exec

3. Steps to reproduce:
$ cat t.c
#include <stdio.h>
#include <string.h>
#include <unistd.h>
main()
{
  printf("my pid=%d, gdb attach me!\n", getpid());
  sleep(20);
  char* exec_args[]={"/usr/bin/ls", "ppp", NULL};
  execve(exec_args[0], exec_args, NULL);
}
$ gcc -g t.c -o t
$ ./t
my pid=12139, gdb attach me!

Start a new shell:
$ gdb
attach 12139 
Continuing.
process 12158 is executing new program: /usr/bin/ls
[New process 12158]

Thread 2.1 "ls" hit Catchpoint 1 (exec'd /usr/bin/ls), 0x00007f34959f3150 in _start () from /lib64/ld-linux-x86-64.so.2
[ Legend: Modified register | Code | Heap | Stack | String ]
-----------------------------------------------------------------------------------[ registers ]----
$rax   : 0xffffffffffffffda
$rbx   : 0x0000000000000000
$rcx   : 0x0000000000000000
$rdx   : 0x0000000000000000
$rsp   : 0x00007ffc97b33a90 -> 0x0000000000000002
$rbp   : 0x0000000000000000
$rsi   : 0x0000000000000000
$rdi   : 0x0000000000000000
$rip   : 0x00007f34959f3150 -> 0x00003618e8e78948
$r8    : 0x0000000000000000
$r9    : 0x0000000000000000
$r10   : 0x0000000000000000
$r11   : 0x0000000000000000
$r12   : 0x0000000000000000
$r13   : 0x0000000000000000
$r14   : 0x0000000000000000
$r15   : 0x0000000000000000
$eflags: [carry parity adjust zero sign trap INTERRUPT direction overflow resume virtualx86 identification]
$ss: 0x002b  $es: 0x0000  $gs: 0x0000  $cs: 0x0033  $fs: 0x0000  $ds: 0x0000  
---------------------------------------------------------------------------------------[ stack ]----
0x00007ffc97b33a90|+0x00: 0x0000000000000002    <-$rsp
0x00007ffc97b33a98|+0x08: 0x00007ffc97b34fdc -> "/usr/bin/ls"
0x00007ffc97b33aa0|+0x10: 0x00007ffc97b34fe8 -> 0x7273752f00707070 ("ppp"?)
0x00007ffc97b33aa8|+0x18: 0x0000000000000000
0x00007ffc97b33ab0|+0x20: 0x0000000000000000
0x00007ffc97b33ab8|+0x28: 0x0000000000000021 ("!"?)
0x00007ffc97b33ac0|+0x30: 0x00007ffc97bc3000 -> 0x00010102464c457f
0x00007ffc97b33ac8|+0x38: 0x0000000000000010
----------------------------------------------------------------------------[ code:i386:x86-64 ]----
   0x7f34959f3140 <update_get_addr+55> rex.XB or BYTE PTR [r11-0x3d], bl
   0x7f34959f3144                  nop    WORD PTR cs:[rax+rax*1+0x0]
   0x7f34959f314e                  xchg   ax, ax
->0x7f34959f3150 <_start+0>       mov    rdi, rsp
   0x7f34959f3153 <_start+3>       call   0x7f34959f6770 <_dl_start>
   0x7f34959f3158 <_dl_start_user+0> mov    r12, rax
   0x7f34959f315b <_dl_start_user+3> mov    eax, DWORD PTR [rip+0x21fc6f]        # 0x7f3495c12dd0 <_dl_skip_args>
   0x7f34959f3161 <_dl_start_user+9> pop    rdx
   0x7f34959f3162 <_dl_start_user+10> lea    rsp, [rsp+rax*8]
-------------------------------------------------------------------------------------[ threads ]----
Aborted (core dumped)

**Comment by zrlw** [comment]
gdb without gef no problem

**Comment by zrlw** [comment]
missing some code after gdb:
$ gdb
 attach 12139
catch exec
set follow-exec-mode new
c

**Comment by Grazfather** [comment]
I cannot repro this (on ubuntu).

Could you please share which commit you're on? Try the newest master, and perhaps try an older commit.

**Comment by zrlw** [comment]
i'm on the newest master (download yesterday), but i had to modify gef.py to accord with  SuSE:
 change 'raise OSError(bla bla bla...) from None' to 'raise OSError(bla bla bla...)', it seemed that SuSE don't known what is form None.

**Comment by zrlw** [comment]
line 404 is the same, here is my snippet:
start line 402: 
def is_in_text_segment(self):
        return (hasattr(self.info, "name") and ".text" in self.info.name) or \
            (hasattr(self.section, "path") and get_filepath() == self.section.path and self.section.is_executable())

**Comment by zrlw** [comment]
coredump also in directly gdb  mode. 
 $ cat t1.c
 #include <stdio.h>
 #include <string.h>
 #include <unistd.h>
 main()
 {
 char* exec_args[]={"/usr/bin/ls", "ppp", NULL};
 execve(exec_args[0], exec_args, NULL);
 }
$ gcc -g -o t1 t1.c
$ gdb t1
 gef> catch exec
 gef> set follow-exec-mode new
 gef> start
[+] Breaking at '{int ()} 0x4005dd <main>'
...
 gef>  c
Continuing.
process 4177 is executing new program: /usr/bin/ls
[New process 4177]

Thread 2.1 "ls" hit Catchpoint 1 (exec'd /usr/bin/ls), 0x00007ffff7ddd150 in _start () from /lib64/ld-linux-x86-64.so.2
[ Legend: Modified register | Code | Heap | Stack | String ]
---------------------------------------------------------------[ registers ]----
$rax   : 0xffffffffffffffda
$rbx   : 0x0000000000000000
$rcx   : 0x0000000000000000
$rdx   : 0x0000000000000000
$rsp   : 0x00007fffffffee60 -> 0x0000000000000002
$rbp   : 0x0000000000000000
$rsi   : 0x0000000000000000
$rdi   : 0x0000000000000000
$rip   : 0x00007ffff7ddd150 -> <_start+0> mov rdi, rsp
$r8    : 0x0000000000000000
$r9    : 0x0000000000000000
$r10   : 0x0000000000000000
$r11   : 0x0000000000000000
$r12   : 0x0000000000000000
$r13   : 0x0000000000000000
$r14   : 0x0000000000000000
$r15   : 0x0000000000000000
$eflags: [carry parity adjust zero sign trap INTERRUPT direction overflow resume virtualx86 identification]
$ss: 0x002b  $es: 0x0000  $gs: 0x0000  $cs: 0x0033  $fs: 0x0000  $ds: 0x0000  
-------------------------------------------------------------------[ stack ]----
0x00007fffffffee60|+0x00: 0x0000000000000002	<-$rsp
0x00007fffffffee68|+0x08: 0x00007fffffffefdc -> "/usr/bin/ls"
0x00007fffffffee70|+0x10: 0x00007fffffffefe8 -> 0x7273752f00707070 ("ppp"?)
0x00007fffffffee78|+0x18: 0x0000000000000000
0x00007fffffffee80|+0x20: 0x0000000000000000
0x00007fffffffee88|+0x28: 0x0000000000000021 ("!"?)
0x00007fffffffee90|+0x30: 0x00007ffff7ffa000 -> 0x00010102464c457f
0x00007fffffffee98|+0x38: 0x0000000000000010
--------------------------------------------------------[ code:i386:x86-64 ]----
   0x7ffff7ddd140 <update_get_addr+55> rex.XB or BYTE PTR [r11-0x3d], bl
   0x7ffff7ddd144                  nop    WORD PTR cs:[rax+rax*1+0x0]
   0x7ffff7ddd14e                  xchg   ax, ax
->0x7ffff7ddd150 <_start+0>       mov    rdi, rsp
   0x7ffff7ddd153 <_start+3>       call   0x7ffff7de0770 <_dl_start>
   0x7ffff7ddd158 <_dl_start_user+0> mov    r12, rax
   0x7ffff7ddd15b <_dl_start_user+3> mov    eax, DWORD PTR [rip+0x21fc6f]        # 0x7ffff7ffcdd0 <_dl_skip_args>
   0x7ffff7ddd161 <_dl_start_user+9> pop    rdx
   0x7ffff7ddd162 <_dl_start_user+10> lea    rsp, [rsp+rax*8]
-----------------------------------------------------------------[ threads ]----
Aborted (core dumped)

**Comment by d4em0n** [comment]
I can reproduce this. It's works when `context.enable=False`.
This is likely a bug from gdb itself. When gef shows context of threads, gdb will execute `info program` command then gdb throw errors.

**From terminal 1**
```
λ n0psledbyte /tmp → cat t.c
#include <stdio.h>
#include <string.h>
#include <unistd.h>
main()
{
printf("my pid=%d, gdb attach me!\n", getpid());
sleep(20);
char* exec_args[]={"/bin/ls", "ppp", NULL};
execve(exec_args[0], exec_args, NULL);
}
λ n0psledbyte /tmp → gcc -g t.c -o t
λ n0psledbyte /tmp → ./t
my pid=12874, gdb attach me!
```

**From terminal 2**
```
(gdb) attach 12874
Attaching to process 12874
Reading symbols from /tmp/t...done.
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/.build-id/81/f0c655ba37873c87f63dcfde83c139261e0c81.debug...done.
done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/.build-id/19/9c127b9a1d4184e3438eff5cb1f6fcd2ef027b.debug...done.
done.
0x00007f1f6f924404 in __GI___nanosleep (
    requested_time=requested_time@entry=0x7ffd49573bd0,
    remaining=remaining@entry=0x7ffd49573bd0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
28      ../sysdeps/unix/sysv/linux/nanosleep.c: No such file or directory.
(gdb) catch exec
Catchpoint 1 (exec)
(gdb) set follow-exec-mode new
(gdb) c
Continuing.
process 12874 is executing new program: /bin/ls
[New process 12874]

Thread 2.1 "ls" hit Catchpoint 1 (exec'd /bin/ls), 0x00007f8b9f7e1090 in _start ()
   from /lib64/ld-linux-x86-64.so.2
(gdb) info program
/build/gdb-uGdIdO/gdb-7.12/gdb/thread.c:982: internal-error: int is_thread_state(ptid_t, thread_state): Assertion `tp' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n)
```
I try this without gef, and execute `info program` manually then gdb error.

**GDB Version**
```
λ n0psledbyte /tmp → gdb --version
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
```

**Comment by zrlw** [comment]
@d4em0n   you are right!
set context.enable to false  just before execve(), then set back to true  after enter into new program.  wish gdb or gef do it automatically in the furture :)
before execve() call:
gef> gef config context.enable False
gef>  catch exec
gef>  set follow-exec-mode new
gef> c
Continuing.
rocess 8311 is executing new program: /usr/bin/ls
[New process 8311]
Thread 2.1 "ls" hit Catchpoint 1 (exec'd /usr/bin/ls), 0x00007ffff7ddd150 in _start () from /lib64/ld-linux-x86-64.so.2
Enter into new program:
gef>  gef config context.enable True  
gef> b __libc_start_main
Breakpoint 2 at 0x4004c0 (2 locations)
gef> c
Continuing.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[ Legend: Modified register | Code | Heap | Stack | String ]
-----------------------------------------------------------------------------------[ registers ]----
$rax   : 0x000000000000001c
...

**Comment by zrlw** [comment]
i created a bug report to SuSE:
https://bugzilla.suse.com/show_activity.cgi?id=1099595
should i close this issue?

**Comment by zrlw** [comment]
PR 23366 - "segfault during info prog at exec catchpoint with follow-exec-mode new"   https://sourceware.org/bugzilla/show_bug.cgi?id=23366
As Suse filed upstream, i close the issue.
