### ISSUE TITLE
tcachebin support request

### ISSUE THREAD

**Issue by Kyle-Kyle** [hugsy/gef#294]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

The title explains everything.

BTW, thanks for the awesome work.

**Comment by Grazfather** [comment]
Could you please explain why you'd like it, why it's useful, and how you'd like the interface to work?

**Comment by Kyle-Kyle** [comment]
`tcachebin` is a new heap mechanism introduced in glibc 2.26. It is intended to be something like `fastbin`(not really) and improve the performance of ptmalloc.
However, since it is still in the early experimental process, it is extremely insecure. It reminds me of the old days(when I haven't started pwnning). It still remains a very easy target even in 2.27 and possibly in 2.28(so far no hardening commits).

The reason why I'd like it is that sometimes I need to examine `tcachebin`. But currently gef does not support it.  I have to do it manually which is troublesome or switch other gdb enhancement tools which I don't like.

It is like `fastbin`, so I hope the interface could be just like how `fastbin` is like.

**Comment by hugsy** [comment]
FTR all structures/explanation can be found here: https://0x00sec.org/t/heap-safari-thread-local-caching/5054
Shouldn't be too hard to provide.

**Comment by Grazfather** [comment]
We should do this for 18.10
