### ISSUE TITLE
Support qemu with gef remote

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#298]
qemu running a binary of another arch doesn't support `remote get` in their gdb server implementation. This breaks everything.

When I run `gef-remote -q HOST:PORT` I noticed that the qemu stub finds the arch to be 'i386', which according to the elif chain is not supported.

```python
          elif arch.startswith("i386:intel"):
              current_elf.e_machine = Elf.X86_32
              current_arch = X86()
          elif arch.startswith("i386:x86-64"):
              current_elf.e_machine = Elf.X86_64
              current_elf.e_class = Elf.ELF_64_BITS
              current_arch = X86_64()
```

Looks like my version of `qemu-arm` doesn't support downloading files:

`Remote I/O error: Function not implemented`

**Comment by electricworry** [comment]
Do you have the same issue if you start gdb with the --se option to specify the file being debugged?

I'm doing userland and kernel debugging using QEMU, GDB, and GEF. I was having problems similar to yours, but this was resolved with --se.

Here's my typical workflow:

```
$ qemu-arm -g 1234 <target-binary>
$ gdb-multiarch --se=<target-binary> -ex 'target remote localhost:1234'
(gdb) continue
```

In the above scenario, GEF seems to work fine for me. Workflow for kernel debugging is a bit different:

```
$ qemu-system-arm -gdb tcp::1234 -kernel <path-to-zImage> -machine vexpress-a15
$ gdb-multiarch --se=<path-to-vmlinux> -ex 'target remote localhost:1234'
(gdb) continue
```

**Comment by YiChenChai** [comment]
I have faced the same problem as you. QEMU's gdbstub has no code that supports Host I/O packets. 

I have written a quick patch to add some basic file transfer capabilities to gdbstub in QEMU. It should be enough to enable functionalities that depend on /proc/self/maps to work (e.g. vmmap). 

Here it is: https://gist.github.com/YiChenChai/06382e49a4dcd49a1d64f240fa8c35df

**Comment by Kyle-Kyle** [comment]
If the target is kernel, the arch will be something like `i386:x86_64`. And in `set_arch` function, there is no entry for it in `arches`. I patched it with a very ugly way: 
~~~
        machine = current_elf.e_machine
        if machine == 64702:
            machine = 62
        current_arch = arches[machine]()
~~~
But I hope you could find a better way to resolve this issue.

**Comment by matan7890** [comment]
Hi guys,
Sorry for bumping an old stale question, but I still have this bug. I have this when debugging the the kernel on an android emulator. Is there a solution from the side of gef for this issue or is this solely a problem on the qemu side?

**Comment by hugsy** [comment]
Hi @matan7890 

I cannot know for your setup exactly but a lot has changed since this issue, in both gef and gdb. Which version are you using? If both are recent, it can be worth opening a new issue, and reference this one in it for tracking, so we can have a look with fresh eyes.
