### ISSUE TITLE
search-pattern fails when debugging kernel

### ISSUE THREAD

**Issue by alexdetrano** [hugsy/gef#300]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: I am running Linux Mint 18.3 64-bit 
  * Architecture: x86
  * GDB version (including the Python library version):  using gdb-multiarch, since my target is a raspberr pi 0w (arm processor)
 * Target: raspberry pi 0w (32-bit)

**gdb version**
root@alex-mint-vm /h/a/p/linux# gdb-multiarch --version
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1

**python version in gdb**
Python Version:
gef➤  python
>import sys
>print(sys.version)
>end
3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609]

### Step 2: Describe your problem
I am debugging the linux kernel using kgdb over a serial connection.  My target is a raspberry pi (arm processor), and the debugger is running on a 64-bit linux mint os 18.3.  is I cannot search for objects in memory using grep or search-pattern. I always get the message "cannot access memory at location 0x0"

#### Steps to reproduce

  grep for anything while debugging kernel.

#### Observed Results

```
gef➤  search-pattern /bin/sh
[+] Searching '/bin/sh' in memory
[!] Command 'search-pattern' failed to execute properly, reason: Cannot access memory at address 0x0
```

#### Expected results

  * What did you expect to happen?
Expect to see a memory address where the string is, or a result that says it could not be found.

**Comment by hugsy** [comment]
Use the command `gef config gef.debug true` and run the faulty command again. Paste us the output.

**Comment by alexdetrano** [comment]
```
gef➤  grep /bin/sh
[+] Searching '/bin/sh' in memory
[!] Command 'search-pattern' failed to execute properly, reason: Cannot access memory at address 0x0
gef➤  gef config gef.debug true
gef➤  grep /bin/sh
[+] Searching '/bin/sh' in memory

─────────────────────────────── Exception raised ───────────────────────────────
MemoryError: Cannot access memory at address 0x0
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/alex/.gdbinit-gef.py", line 2048, in read_memory()
    →     return gdb.selected_inferior().read_memory(addr, length).tobytes()
↳ File "/home/alex/.gdbinit-gef.py", line 4757, in search_pattern_by_address()
    →     mem = read_memory(chunk_addr, chunk_size)
↳ File "/home/alex/.gdbinit-gef.py", line 4789, in search_pattern()
    →     for loc in self.search_pattern_by_address(pattern, start, end):
↳ File "/home/alex/.gdbinit-gef.py", line 4820, in do_invoke()
    →     self.search_pattern(pattern, endian)
↳ File "/home/alex/.gdbinit-gef.py", line 2101, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/alex/.gdbinit-gef.py", line 3482, in invoke()
    →     self.do_invoke(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
  120  python
  121  import sys
  122  print(sys.version)
  123  end
  124  exit
  125  q
  126  q
  127  grep /bin/sh
  128  gef config gef.debug true
  129  grep /bin/sh
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 7.11.1
* Python: 3.5.2 - final
* OS: Linux - 4.10.0-38-generic (64bit) on LinuxMint 18.3 sylvia
────────────────────────────────────────────────────────────────────────────────
```

**Comment by hugsy** [comment]
Thanks, that's more useful. I didn't even know that gef was working with kgdb, that's cool.
I need to set up an env. to repro this bug, so it might take a bit. If you can manage to fix it yourself, feel free to drop a PR (and link to this issue).

**Comment by twwd** [comment]
Anything new on this?

**Comment by hugsy** [comment]
Not on my end, maintaining the same features in kernel land GEF has in user land is very challenging to say the least.
But I definitely welcome PRs on this as I'm sure many others must be interested.
