### ISSUE TITLE
Improve address parsing to allow evaluation of gdb expressions

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#305]
for example, `xinfo` calls `parse_address` which does `to_unsigned_long(gdb.parse_and_eval(address))` which does `return long(str(v), 16)`

We see that that works for ints:
```bash
gef➤  pi long(str(gdb.parse_and_eval("0x1000")), 16)
4096
```

But doesn't for symbols
```bash
gef➤  pi long(str(gdb.parse_and_eval("main")), 16)
Python Exception <class 'ValueError'> invalid literal for int() with base 16: '{<text variable, no debug info>} 0x56555a28 <main>':
Error while executing Python code.
gef➤  pi long(str(gdb.parse_and_eval("&main")), 16)
Python Exception <class 'ValueError'> invalid literal for int() with base 16: '0x56555a28 <main>':
Error while executing Python code.
```

If we skip the `str` part, and try a direct convert, it seems to work better:

```bash
gef➤  pi long(gdb.parse_and_eval("&main"))
1448434216
gef➤  pi long(gdb.parse_and_eval("0x1000"))
4096
```

SO: Why do we do this roundabout way through `str()`? I think we should try to evaluate the expression and then convert directly, but we'll have to be very careful we don't have any regressions.

**Comment by hugsy** [comment]
Ah this. There is a reason but can't remember it. If I do, I'll add a specific comment in the code.
Does it pass all the unit tests with your changes ? If so, you can move forward and push it.

**Comment by Grazfather** [comment]
I'll leave it there for a week or so and see if anything breaks!

All unit tests pass.

**Comment by hugsy** [comment]
I think this was fixed, closing.

**Comment by Grazfather** [comment]
Yes it was!
