### ISSUE TITLE
Feature Request: Support lldb as well as gdb

### ISSUE THREAD

**Issue by dlrobertson** [hugsy/gef#311]
## Request ##

LLVMs [lldb] is another popular command line debugger with similar features to gdb that also has a python API and init file. It would be cool if gef supported multiple backends which included both gdb and [lldb]. Not sure how similar the APIs are though.

## Open Questions ##

  - Would allowing users to use multiple backends (even if this only includes [lldb] and gdb) will this over complicate the code?

[lldb]: https://lldb.llvm.org/

**Comment by Grazfather** [comment]
This will probably never happen. I suggest you try out https://github.com/snare/voltron

**Comment by dlrobertson** [comment]
Np just wondered if it was on the radar

**Comment by sam-f0** [comment]
We have recently released [llef](https://github.com/foundryzero/llef ), which you may find useful for lldb support.
