### ISSUE TITLE
Add 'unknown arch' that is the default

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#316]
Instead of breaking everything when the arch cannot be detected, let's fall back to a dummy arch.

For things like printing registers, it can do something dumb and slow like just using `info regs` to generate a list.

[gdb-dashboard](https://github.com/cyrus-and/gdb-dashboard) does pretty well with random architectures. We should be able to do the same (leveraging gdb when we can't figure it out ourselves).

**Comment by hugsy** [comment]
Seems redundant with #84 which you opened in 2016 :stuck_out_tongue: Can we close this one ? Also are you working on it ?

**Comment by Grazfather** [comment]
well that is `current_elf` and this is `current_arch`.

My idea here is that basically if we can't id the arch then we use GDB's idea of the arch to get the regs and stuff. I probably have a change that half-does this somewhere.

I think it's a different issue entirely to get rid of our dependence on using `current_elf`. #469 is a step in the right direction there.
