### ISSUE TITLE
blank line to repeat is performing weirdly

### ISSUE THREAD

**Issue by Escapingbug** [hugsy/gef#319]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Archlinux
  * Architecture: x86_64
  * GDB version (including the Python library version): 8.2(3.7)

### Step 2: Describe your problem

steps and step-over commands ("si", "s", "ni", "n") are unable to repeat using blank line when context is working fine. I tried to debug it a little bit, found that when I deleted the line calling context in stop handler hook, everything will be fine. But no context of course. And also, context command itself is repeatable when  no debugging session active (so it will not be working, just complaining a bit). But once there is debugging session, it cannot be repeat.

And also, this seems to be related with gdb version.. My older version seems to be working fine..

#### Steps to reproduce

  1. open up gdb(gef)
  2. try debug something, and do "si"
  3. type blank line to repeeat

#### Observed Results

nothing is repeated

#### Expected results

"si" command repeated

#### Traces

Feel free to include in this section screenshots, stack traces, or

```
code to reproduce
```

If you enable `gef.debug` (`gef config gef.debug 1`), gef will display a
full stack trace when an exception occurs. It is a good idea to copy/paste it here
(and/or add a screen shot) as it contains useful information that will make it easier
to reproduce.

**Comment by hugsy** [comment]
Have you tried on your another setup ? I just tried `n` , `s` and `si` on Ubuntu and Debian with GEF from `master` and it behaves as expected.

**Comment by hugsy** [comment]
And tested on Fedora too btw.
And the version is always 8.1+ (from repo). 

Additionally GEF doesn't touch to the traditional commands like `n` , `si` etc. Are you sure you don't have those commands wrapped and the wrapper calls [`dont_repeat`](https://sourceware.org/gdb/onlinedocs/gdb/Commands-In-Python.html#index-Command_002edont_005frepeat) ?

**Comment by seb321** [comment]
It seems that there is a bug in GDB 8.2 (look at cyrus-and/gdb-dashboard#128). Issue was submitted to GDB ([link](https://sourceware.org/bugzilla/show_bug.cgi?id=23714))

**Comment by hugsy** [comment]
Cool! I'm closing this ticket as it is not a GEF issue.

Thanks for tracking that down.

Cheers.
