### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by Kaka201** [hugsy/gef#322]
$ python ~/.gdbinit-gef.py --update
Traceback (most recent call last):
  File "/home/kaka/.gdbinit-gef.py", line 186, in <module>
    sys.exit( update_gef(sys.argv) )
  File "/home/kaka/.gdbinit-gef.py", line 173, in update_gef
    gef_print("[-] No update")
NameError: global name 'gef_print' is not defined

**Comment by ril3y** [comment]
Oh good.  I am not the only one with this issue.  I fought with this last night.  Curious what version of gdb are you running this against?  I tried 8.2 built from source --with-python.

**Comment by Grazfather** [comment]
Good catch. For now I could just download it manually, but I am pushing a push, so subsequent updates should work. Sorry about this!
