### ISSUE TITLE
GDB can't find keystone-engine

### ISSUE THREAD

**Issue by BowenWang** [hugsy/gef#327]
Your issue will be closed unless you confirm the following:
  * [Yes] Did you use the latest version of GEF from `master` branch?
  * [Yes] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [Yes] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Debian 9.5
  * Architecture: x86_64
  * GDB version (including the Python library version): GDB version 7.12 compiled with Python version 3.5.3

### Step 2: Describe your problem
When I start gdb using gdb -q target_program, it shows that there are 2 commands could not be loaded because missing 'keystone-engine' package for Python3

I am pretty sure I have already installed all the required packages for both Python 2 and Python 3.

Do I need to install other packages?

#### Steps to reproduce

  1.

#### Observed Results

  * What happened?  This could be a description, log output, etc.

#### Expected results

  * What did you expect to happen?

#### Traces

Feel free to include in this section screenshots, stack traces, or

```
code to reproduce
```

If you enable `gef.debug` (`gef config gef.debug 1`), gef will display a
full stack trace when an exception occurs. It is a good idea to copy/paste it here
(and/or add a screen shot) as it contains useful information that will make it easier
to reproduce.

**Comment by hugsy** [comment]
This is not a GEF bug, but setup. Use the IRC channel for this kind of question.

You can always try to install the latest from keystone by running this script:
https://github.com/hugsy/stuff/blob/master/update-trinity.sh
