### ISSUE TITLE
consider tagging a git release

### ISSUE THREAD

**Issue by anthraxx** [hugsy/gef#33]
Hey, it would be awesome if you can start tagging git releases sometimes, this would also aid the way package maintainers could start packaging this :smile: 
Would love to soon see a tag :+1:

**Comment by hugsy** [comment]
Hey @anthraxx 

Until now, I've always pushed commits to gef "as-I-go" because I never realized it was worth packaging (it is only one script that can update itself `--update`).

I'll think of a way to provide good release system.

Thank for your feedback.

**Comment by anthraxx** [comment]
well even if its technically one script it can still be worth packaging it to make it even more easily available for users to install and search for it :smile: 
well the ```--update``` command would maybe not be optimal in such packaged environment it maybe a switch to disable that feature while packaging would be handy?

**Comment by hugsy** [comment]
On Mon, Jun 06, 2016 at 05:00:09PM -0700, Levente Polyak wrote:
> well even if its technically one script it can still be worth packaging it to make it even more easily available for users to install and search for it :smile:
> well the ```--update``` command would maybe not be optimal in such packaged environment it maybe a switch to disable that feature while packaging would be handy?
>

Yeah that can be done as well.

--
hugsy

"Computer science is no more about computers than astronomy is about telescopes." - E. Dijkstra

**Comment by Grazfather** [comment]
You could also extend the --update feature s/t it accepts a version string instead of always going to master.

**Comment by anthraxx** [comment]
bump :cat:

**Comment by hugsy** [comment]
Oh snap, I forgot that :flushed: ... The first one will be done right after #210 is merged to `master`. I will start making regular releases from then on.

**Comment by hugsy** [comment]
cc https://github.com/hugsy/gef/releases/tag/2018.02
