### ISSUE TITLE
Feature Request: Provide stdin input when using pie run

### ISSUE THREAD

**Issue by daniellimws** [hugsy/gef#330]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

***

Normally we can provide input to stdin inside GDB by using `run < input.txt`. The `pie` command currently lacks that, and it would definitely be helpful to have it.

**Comment by Grazfather** [comment]
Should't this work? See

https://github.com/hugsy/gef/blob/3c4bba6f1530cd8089289fc17647694126af4c4b/gef.py#L6724-L6726
