### ISSUE TITLE
Support for Horizontal Register screen?

### ISSUE THREAD

**Issue by DanielTimLee** [hugsy/gef#335]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Arch Linux
  * Architecture: x86
  * GDB version (including the Python library version): 8.2 / 3.6

#### Steps to reproduce

  1. Try to print the register screen as a horizontal view.

#### Observed Results

  * What happened?  This could be a description, log output, etc.

Register screen is showed as a vertical view.

#### Expected results

  * What did you expect to happen?
 Show Register Layout as Horizontal, not Vertical.

**Comment by DanielTimLee** [comment]
Oh. I didn't try that one.

If you don't mind, how about adding some more details to document? 

It just only mentions that command will dereference the register, 
Not directly tells you that it will change the layout of a register view.

(I was looking for a related resource, but couldn't find any of the info about the view directional)

https://github.com/hugsy/gef/blob/master/docs/commands/context.md#editing-context-layout

> Automatically dereference the registers in the regs section:
> - gef➤ gef config context.show_registers_raw 0

**Comment by Grazfather** [comment]
Fixed in 5debce7
