### ISSUE TITLE
Regenerate screenshots

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#348]
Some of the screenshots aren't very good, and they look inconsistent (taken at different points in time).

Let's take a whole new slew of them.

**Comment by Grazfather** [comment]
I just thought of something: We should write scripts to generate these.

e.g.

screen shot context: `gdb -nq -ex 'source gef.py' -ex 'start' -ex 'n3' default.out`

**Comment by hugsy** [comment]
Meh... It's not as if we change them every weekend.
Plus the screenshots for non-x86s are going to be tricky to generate (start vm , wait for boot, ssh, update gef, run gdb. etc. etc.)

Anyway, I'll do that this WE and update the docs in prep for 2018.10.
