### ISSUE TITLE
heap-analysis-helper: Can't distinguish calloc and malloc

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#359]
Not a big deal, but it hardcodes `malloc` in the info print, even if actually set on calloc
```
[+] Heap-Analysis - malloc(32)=0x602030
...
 →   20          void* p2 = calloc(0x20, 1);
```

Also, the functionality is not really tested at all.

**Comment by fibonascii** [comment]
So I made the change to the code and info statements are working properly but now it seems to be breaking on one of the tests 

`-__libc_malloc(16)=0x555555756010\n[+] Heap-Analysis
 - __libc_malloc(16)=0x555555756010\n[+] Heap-Analysis 
 - __libc_calloc(32)=0x555555756030\n[+] Heap-Analysis -`

`Traceback (most recent call last):
  File "tests/runtests.py", line 192, in test_cmd_heap_analysis
    self.assertIn("malloc(32)=", res) # Actually calloc
AssertionError: 'malloc(32)=' not found in "Reading symbols from tests/binaries/heap-analysis.out`

**Comment by Grazfather** [comment]
Fixed in #375

**Comment by semwai** [comment]
It seems relevant again
In addition, the wrong size is shown for calloc (only the first argument)

main.c:
```c
#include <stdlib.h>

void foo() {

}
int main() {
    void* ptr = calloc(10, 10);
    foo();
}
```
build:
```bash
gcc main.c -o main
```

script.gdb:
```sh
start
heap-analysis-helper
br foo
c
heap-analysis-helper show
```

gdb -x script.gdb

output:
```bash
[#0] Id 1, Name: "main", stopped 0x555555555151 in foo (), reason: BREAKPOINT
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
[#0] 0x555555555151 → foo()
[#1] 0x55555555517d → main()
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[*] This feature is under development, expect bugs and unstability...
[+] Tracked as in-use chunks:
✘  malloc(10) = 0x5555555592a0
[+] No free() chunk tracked
gef➤  
```

**Comment by hugsy** [comment]
Hi @semwai 

If you think that's a bug, file a new issue and refer this one. We'll check it out
