### ISSUE TITLE
bufferize makes gdb.execute(..., to_string=True) return nothing

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#362]
if `gdb.execute(..., to_string=True)` is called while in a command invocation, then it will return an empty string if the invoked command buffers its output. This means it only affects using `gdb.execute` on our own commands, not builtins.

This is bad for commands that actually need its output.

I am surprised this isn't breaking more things. We might have to disable buffering (again) for the release.

**Comment by hugsy** [comment]
Close after #364 is merged.

**Comment by Grazfather** [comment]
Close, though this may bite us later: We only use this either in cases where we don't want the output or when we are running builtins. In the first case, buffering doesn't matter, in the second, the command doesn't buffer anyway.
