### ISSUE TITLE
Figure out `dereference_as_long`

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#365]
`dereference_as_long` is weird. It dereferences an address, but then it returns the address itself, not the value at the address? What is the purpose of this, other than to determine that it is an address?

It seems to be only used for heap stuff.

A real `dereference_as_long` would be useful, but we actually already do that with `Address.dereference`. There's also `dereference` (not a member).

Let's make these make sense.

**Comment by hugsy** [comment]
Fixed by 41a2a34. Closing
