### ISSUE TITLE
Repeating command does not work anymore

### ISSUE THREAD

**Issue by oschoudhury** [hugsy/gef#369]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Arch Linux
  * Architecture: x86-64
  * GDB version (including the Python library version): 8.2

### Step 2: Describe your problem

I regularly use `n`/`s`/`ni`/`si` to step through the instruction space. I used to be able (and still am able to do it when removing gef from `~/.gdbinit`) to just hit enter and it used to repeat the last command. Now it just does nothing. As you can imagine writing `ni` and hit enter 20 times can get annoying and the gdb history gets filled with the repeated command too.

I see the same behaviour for `c`, but there I can still live with it repeating the command.

As I didn't use gdb in a while, I can't be sure when this started to happen but I believe it is related to https://github.com/hugsy/gef/pull/333

**Comment by hugsy** [comment]
This was already covered, it is not coming from GEF. See #319.

**Comment by oschoudhury** [comment]
Ah, somehow missed that when I browsed through the issue list.
