### ISSUE TITLE
Command failed to execute properly

### ISSUE THREAD

**Issue by yakamoz147** [hugsy/gef#372]
### environment:

  * Operating System/archictecture: 4.18.0-kali2-amd64
  * GDB version: 8.2.50.20181023-git
  * Used Python engine: 2.7

### problem:

After starting gef several commands dont work, eg.: "context" "pie breakpoint" etc

Error message is:
"[!] Command 'context' failed to execute properly, reason: 'NoneType' object has no attribute '__module__'"

the commands were still working one or two weeks ago...

it seems to be related to issue #203 and issue #278 

#### Steps to reproduce

  1. gdb -q
  2. context

#### Observed Results

gef> context
[*] No debugging session active
[!] Command 'context' failed to execute properly, reason: 'NoneType' object has no attribute '__module__'

#### Expected results

the usual 'context' output

#### Traces

gef> gef config gef.debug 1
gef> context
[*] No debugging session active

------------------------------- Exception raised -------------------------------
AttributeError: 'NoneType' object has no attribute '__module__'
----------------------------- Detailed stacktrace ------------------------------
\-> File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper()
   ->    setattr(wrapper, attr, getattr(wrapped, attr))
\-> File "/root/.gdbinit-gef.py", line 308, in bufferize()
   ->    @functools.wraps(f)
\-> File "/root/.gdbinit-gef.py", line 3610, in invoke()
   ->    bufferize(self.do_invoke(argv))
----------------------------- Last 10 GDB commands -----------------------------
  255  pie
  256  i r
  257  pie b main
  258  context
  259  python set_arch()
  260  gdb -q
  261  context
  262  config gef.debug 1
  263  gef config gef.debug 1
  264  context
----------------------------- Runtime environment ------------------------------
* GDB: 8.2.50.20181023-git
* Python: 2.7.15 - final
* OS: Linux - 4.18.0-kali2-amd64 (64bit) on Kali kali-rolling kali-rolling
--------------------------------------------------------------------------------

**Comment by Grazfather** [comment]
What commit are you on? This issue shouldn't exist on master, so you must just be on an old version of dev.

If you're playing with the dev branch always try to update to the top of dev before reporting bugs.

**Comment by wbowling** [comment]
@Grazfather the broken bufferize is on master https://github.com/hugsy/gef/blob/master/gef.py#L3610

**Comment by Grazfather** [comment]
Oh, if it was broken on master the fix should have been cherry picked to master immediately. We must have very few users using gdb + Python2.

**Comment by hugsy** [comment]
> What commit are you on? This issue shouldn't exist on master, so you must just be on an old version of dev.
> 

I agree, tested on 2 fresh VMs with GDB+Py2, couldn't reproduce. @yakamoz147 Please use the latest from `master` and retest.

**Comment by yakamoz147** [comment]
I was on master when posting the issue but since I anyway had my problems with kali I switched to a different distro now where gdb runs with python3 and there everything works fine. I will retest it on a kali machine one of these days when I have a couple of mins on my hand and post the result here.

**Comment by yakamoz147** [comment]
So I just set up a fresh VM with Kali and tried it again and now gdb ships with python3 and that solves the issue. Im not exactly sure why I was on py2 before and now it changed. Unfortunately I trashed the VM I was using before so I can't check up on it. Thanks for the help anyways!

**Comment by hugsy** [comment]
No worries, thanks for the report. Feel free to re-open if you can provide more details for us to reproduce your issue.

Cheers
