### ISSUE TITLE
rase TypeError("cant't mix strings and bytes in path components") from None

### ISSUE THREAD

**Issue by ericyin521** [hugsy/gef#382]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch? yes
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first? yes
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)? yes

### Step 1: Describe your environment

  * Operating System: manjaro
  * Architecture: x86_64
  * GDB version (including the Python library version):8.1.1

#### Steps to reproduce

  1.I install gef according to the guideline, actually i have resolve it , because i edit some original code ,so i think i should paste it here ,maybe someone have  the same issue.

#### Observed Results
File "/home/Myhomepath/.gdbinit-gef.py", line 9481, in <module>
    "python{}".format(PYENV_VERSION[:3]), "site-packages")
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None

#### resolution

![edit](https://user-images.githubusercontent.com/9777663/48042609-47888d00-e1bd-11e8-9c28-bbc220372589.png)

**Comment by ericyin521** [comment]
just as i said

**Comment by adrian-the-git** [comment]
This fix is incorrect. Calling `str` on a `bytes` object (as returned by `subprocess.check_output`) produces a  string (which prevents the exception from being raised) but that string will look like `"b'/home/Myhomepath/.pyenv'"` which will not produce a correct path. 

A correct fix would involve calling `.decode()` on the bytes object, or passing an encoding to `subprocess.check_output`.

To clarify, this bug prevents people from using gef if they're using gdb with python3 and have pyenv installed.

**Comment by Grazfather** [comment]
I missed this issue. @adrian-the-git could you look at #400? It should go the trick.

**Comment by Grazfather** [comment]
This was fixed. Thank you for testing @daniellimws
