### ISSUE TITLE
Context fowarding leads to: Turn the logging off and on to make the new setting effective.

### ISSUE THREAD

**Issue by reijin90** [hugsy/gef#383]
Your issue will be closed unless you confirm the following:
  * [ ] Did you use the latest version of GEF from `master` branch? ( I used the install script)
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Ubuntu 18 (Guest VM), Windows, WSL (Host)
  * Architecture: x86_64
  * GDB version (including the Python library version): GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Python 3.6

### Step 2: Describe your problem

Using SSH to a VM in two windows: where gef runs in one window and in the other I tried to get the `tty` which yields: `/dev/pts/0`.
I then used `gef config context.redirect /dev/pts/0` to redirect there. It worked for one redraw, but then fails:
```
[!] Command 'context' failed to execute properly, reason: Sign not allowed in string format specifier
[*] gdb is already running
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: Currently logging to /dev/pts/0.  Turn the logging off and on to make the new setting effective.
warning: Currently logging to /dev/pts/0.  Turn the logging off and on to make the new setting effective.

```
Now it only shows this error for every redrawing of the context: `warning: Currently logging to /dev/pts/0.  Turn the logging off and on to make the new setting effective. `
Strangely, the gef window now contains the context again eventhough the redirect is still active. 

Setting and unsetting the command did not work and I'm not a pro with Linux, so I don't understand what logging this error references. I was unable to find anything useful via Google.

**Comment by Grazfather** [comment]
Could you please enable debugging and show us the output?

`gef config gef.debug True`

**Comment by reijin90** [comment]
Weird, I've killed and restarted all my ssh sessions and now the context is being drawn. But: at first it didn't draw everything (only about half of the context) and showed this error:
`[!] Command 'context' failed to execute properly, reason: Sign not allowed in string format specifier`
Once I entered the debug mode, everything is getting drawn again, but always with the `warning: Currently logging to /dev/pts/0. Turn the logging off and on to make the new setting effective.`.

I'm not receiving any gef errors it seems. There is no debug output from gef.

**Comment by Grazfather** [comment]
No, you are seeing the error :)

```
─────────────────────────────── Exception raised ───────────────────────────────
ValueError: Sign not allowed in string format specifier
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/master/.gdbinit-gef.py", line 7046, in context_title()
    →     padd=HORIZONTAL_LINE),
↳ File "/home/master/.gdbinit-gef.py", line 7350, in context_source()
    →     self.context_title(title)
↳ File "/home/master/.gdbinit-gef.py", line 7022, in do_invoke()
    →     self.layout_mapping[section]()
↳ File "/home/master/.gdbinit-gef.py", line 2317, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/master/.gdbinit-gef.py", line 319, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "/home/master/.gdbinit-gef.py", line 3659, in invoke()
    →     bufferize(self.do_invoke)(argv)
```

What appears to be happening is that the `width` field is being calculated to a negative value

```python
>>> x = -3
>>> s = "{:{padd}<{width}} ".format("", width=x, padd=y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Sign not allowed in string format specifier
```

**Comment by reijin90** [comment]
> What appears to be happening is that the `width` field is being calculated to a negative value
> 
> ```python
> >>> x = -3
> >>> s = "{:{padd}<{width}} ".format("", width=x, padd=y)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ValueError: Sign not allowed in string format specifier
> ```

So this is probably related to my setup with ConEmu and WSL? 
Any idea how I can fix this?

PS.: I made a second edit regarding the warning scenario - not sure if they are actually related.

**Comment by Grazfather** [comment]
Yeah, I don't have a windows setup handy, but I think it has to do with `get_terminal_size` not returning the correct size.

If you want a work around you could probably get away with this change

```diff
@ gef.py:2719 @ def exit_handler(event):

def get_terminal_size():
     """Return the current terminal size."""
-    if is_debug():
-        return 600, 100
+    return 600, 100
 
     try:
         cmd = struct.unpack("hh", fcntl.ioctl(1, termios.TIOCGWINSZ, "1234"))
```

Notice how it already behaves differently in debug mode? I am actually surprised you managed to reproduce with it enabled.

**Comment by reijin90** [comment]
> Yeah, I don't have a windows setup handy, but I think it has to do with `get_terminal_size` not returning the correct size.
> 
> If you want a work around you could probably get away with this change
> 
> ```diff
> @ gef.py:2719 @ def exit_handler(event):
> 
> def get_terminal_size():
>      """Return the current terminal size."""
> -    if is_debug():
> -        return 600, 100
> +    return 600, 100
>  
>      try:
>          cmd = struct.unpack("hh", fcntl.ioctl(1, termios.TIOCGWINSZ, "1234"))
> ```
> 
> Notice how it already behaves differently in debug mode? I am actually surprised you managed to reproduce with it enabled.

I see, but since the error is still there in debug mode, there must be an additional issue here right? Afterall enabling debug should force the returned terminal size to the values above. And the warning still persists in both situations (debug enabled and disabled). 

Overall it seems I cannot use the redirect feature as it leads to issues for me, which is pretty sad...

**Comment by Grazfather** [comment]
You're right. I am surprised you could repro: `get_terminal_size` is called every time the context is displayed, so you shouldn't ever have that 'signed format specifier' error.

The warning I have no idea about, either. I will try to get it figured out on a windows machine.

**Comment by reijin90** [comment]
To catch at least the issue of a wrongly determined terminal size I propose this change to the get_terminal_size() function:
```
def get_terminal_size():
    """Return the current terminal size."""
    if is_debug():
        return 600, 100

    try:
        cmd = struct.unpack("hh", fcntl.ioctl(1, termios.TIOCGWINSZ, "1234"))
        tty_rows, tty_columns = int(cmd[0]), int(cmd[1])
        if tty_rows > 1 or tty_columns > 1:
            return tty_rows, tty_columns
        else: 
            raise OSError('TTY size is too small.')

    except OSError:
        return 600, 100
```

I did some digging too and could it be that trail_len just becomes bigger than the columns?
I also added this to my file:
```
        trail_len = len(m) + 6
        title = ""
        if trail_len > self.tty_columns:
            trail_len = self.tty_columns
        title += Color.colorify("{:{padd}<{width}} ".format("",
                                                            width=self.tty_columns - trail_len,
                                                            padd=HORIZONTAL_LINE),
```
Now I don't see the ValueError anymore. 
I can now see why it probably happens though. The filepath that is displayed is super long, which probably leads to trail_len being bigger than the columns value.

**Comment by Grazfather** [comment]
I edited your post to get the diff working (edit to see how).

I like your second, or we could just do
`width = max(0, self.tty_columns - trail_len`

**Comment by Grazfather** [comment]
So I found a Windows machine and installed WSL, and I can repro both issues. I can also repro the sign issue on linux with a small window.

>Currently logging to %s.  Turn the logging off and on to make the new setting effective.`

That's a GDB string, it's not GEF at all. See _cli-logging.c_.

I tried following its advice and just turned logging off and on again
```
set logging off
set logging on
ni
...
Segmentation fault (core dumped)
```

:(

This warrants further investigation, but it's GDB code, and not ours, luckily. I'll try to repro it without the involvement of gef.

**Comment by Grazfather** [comment]
I can actually reproduce this on gdb 8.0.1 on Ubuntu 17.20 _without Windows_ so that should make debugging much easier.

I cannot reproduce if I enter the commands manually, for some reason. @reijin90 could you try entering the logging commands manually and see if that works for you?

```
      gdb.execute("set logging overwrite")
      gdb.execute("set logging file {:s}".format(to_file))
      gdb.execute("set logging redirect on")
      gdb.execute("set logging on")
```

**Comment by Grazfather** [comment]
clear_screen works for me. It doesn't work for you because you circumvented the gef method of redirecting, so it just calls `shell clear` which doesn't use the logging file.

**Comment by reijin90** [comment]
> clear_screen works for me. It doesn't work for you because you circumvented the gef method of redirecting, so it just calls `shell clear` which doesn't use the logging file.

Ah, so this behaviour is reproduceable for you on the Ubuntu setup as well? Once you issue the commands manually, gef is unaware of the correct tty, right?

**Comment by freingruber** [comment]
Function disable_redirect_output() (in current dev branch line 1161).
Change the order of the two gdb.execute() calls to:
```
gdb.execute("set logging off")
gdb.execute("set logging redirect off")
```
 => The set logging redirect off command results in the message printed, if the order is changed the logging is turned off before it gets printed...

**Comment by Grazfather** [comment]
yes, it's because gef doesn't know the name of the tty.

@freingruber good find. I made PR #388.

@reijin90 can you possibly test this PR? Simply download the new _gef.py_.

```
wget -q -O "$HOME/.gdbinit-gef.py" https://github.com/hugsy/gef/raw/fix_redirect/gef.py
```

**Comment by reijin90** [comment]
> yes, it's because gef doesn't know the name of the tty.
> 
> @freingruber good find. I made PR #388.
> 
> @reijin90 can you possibly test this PR? Simply download the new _gef.py_.
> 
> ```
> wget -q -O "$HOME/.gdbinit-gef.py" https://github.com/hugsy/gef/raw/fix_redirect/gef.py
> ```

Hi! Sorry for my late response. The proposed code fixes the warning, but I still rely on the debug mode. Gef seems to receive a wrong size from my console emulator. It may be related to the redirect feature, as I don't need the debug mode when not using it.
