### ISSUE TITLE
Idea: always display ascii when hexdumping memory

### ISSUE THREAD

**Issue by degrigis** [hugsy/gef#396]
Not really an issue, I was just wondering why don't we display the ascii view even when users type `hexdump (qword|dword|word) address`? 

Something like this:

![hexdump_view](https://user-images.githubusercontent.com/4940271/48665433-0f0d6c80-ea63-11e8-8d99-466829f4a421.png)

I think it's always useful to have that information + the offsets in memory. Imho that's the best view that you can have in memory, what do you think?

**Comment by Grazfather** [comment]
Not a bad idea. How did you hack together that screen shot?

3 line change here: #397

**Comment by degrigis** [comment]
Cool! The code is ready, I just have to do a couple of things to be ready to submit a PR :-)

**Comment by Grazfather** [comment]
if yours is better (e.g. colourizes it) go ahead and make a PR :)

**Comment by degrigis** [comment]
Nah, no need to submit another PR though :-)

I will probably be back during the week with new exciting features and ideas!
