### ISSUE TITLE
checksec not working under Python3

### ISSUE THREAD

**Issue by truemongo** [hugsy/gef#4]
checksec command seems to fail when using GDB with Python3:

gef> checksec
[+] checksec for '/bin/ls'
Python Exception <class 'TypeError'> Type str doesn't support the buffer API: 
Error occurred in Python command: Type str doesn't support the buffer API

Thanks for this great tool!

**Comment by hugsy** [comment]
Thanks for the bug report.
I think it's OK now, can you try and let me know ?

**Comment by truemongo** [comment]
Thanks! Yea, that seemed to solve that problem.

I noticed now that gef doesnt show the same output as checksec.sh though:

gef> checksec 
[+] checksec for '/bin/ls'
Canary:                                           No
NX Support:                                       Yes
PIE Support:                                      Yes
RPATH:                                            No
RUNPATH:                                          No
Partial RelRO:                                    No
Full RelRO:                                       No

root@xxx# ~/checksec.sh --file /bin/ls
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE
Partial RELRO   Canary found      NX enabled    No PIE          No RPATH   No RUNPATH   /bin/ls

I think the checksec.sh output is the correct one, but I'd have to do some more testing to confirm.

**Comment by hugsy** [comment]
That's pretty weird, I get the same results (gef & checksec.sh identical output) on the Ubuntu VM (with Python3) Can you provide more details so I can try to reproduce ?

**Comment by truemongo** [comment]
Same environment here, Ubuntu with GDB+Python3.
Looking at the source I think the problem is the following, in do_check() method:

        ret = subprocess.check_output( cmd )
        ret = str( buf )

The 2nd line should probably be ret = str( ret ). That seems to fix the problem.

**Comment by hugsy** [comment]
Fixed now. Thanks again for reporting !
