### ISSUE TITLE
pcustom display invalid values

### ISSUE THREAD

**Issue by ManuSecsearch** [hugsy/gef#406]
Your issue will be closed unless you confirm the following:
  * [X] Did you use the latest version of GEF from `master` branch?
  * [X] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [X] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Ubuntu cosmic
  * Architecture: 64bits
  * GDB version (including the Python library version): GNU gdb (Ubuntu 8.2-0ubuntu1) 8.2 / Python 3.6.7

### Step 2: Describe your problem
fields value from pcustom are not matching the content of the memory

#### Steps to reproduce

Hard to reproduce as i'm working on specific environment but here is the output, import look for example at field named constant_2 at offset 0x27 where it shown value 255

Here is the struct detail 
gef➤  pcustom AHOleDirInfo
+0000 ptr_vtable_unicode_string c_ulong (0x8)
+0008 field_8 c_uint (0x4)
+000c field_C c_ulong (0x8)
+0014 field_14 c_ulong (0x8)
+001c field_1C c_ulong (0x8)
+0024 field_24 c_ubyte (0x1)
+0025 field_25 c_ubyte (0x1)
+0026 field_26 c_ubyte (0x1)
+0027 constant_2 c_ubyte (0x1)
+0028 DirectoryObjectType c_ushort (0x2)
...

#### Observed Results

gef➤  pcustom AHOleDirInfo $rdi
0x7fffffffc840+0x0000 ptr_vtable_unicode_string : 0x0000000000000000 (c_ulong)
0x7fffffffc840+0x0008 field_8 :         3984262931 (c_uint)
0x7fffffffc840+0x000c field_C :         0x00000000008ddff0 → 0x00007fffed841410 → 0x00007fffed7b6930 → <std::basic_ifstream<char,+0> mov rax, QWORD PTR [rip+0x8e221]        # 0x7fffed844b58 (c_ulong)
0x7fffffffc840+0x0014 field_14 :        0x0000000000000200 (c_ulong)
0x7fffffffc840+0x001c field_1C :        0x0200000000a8fc80 (c_ulong)
0x7fffffffc840+0x0024 field_24 :        208 (c_ubyte)
0x7fffffffc840+0x0025 field_25 :        215 (c_ubyte)
0x7fffffffc840+0x0026 field_26 :        255 (c_ubyte)
0x7fffffffc840+0x0027 constant_2 :      255 (c_ubyte)

...

but dumping it from memory show a total different value which is the correct one
gef➤  x/1b 0x7fffffffc867
0x7fffffffc867:	0x02

#### Expected results

See the value of 0x2 at the right offset instead of 255

**Comment by hugsy** [comment]
> Hard to reproduce as i'm working on specific environment but here is the output, import look for example at field named constant_2 at offset 0x27 where it shown value 255

That's a problem for us. If we can't repro, it's harder to see the bug by ourselves and fix it. Can you try to provide a tiny reproducible case?

**Comment by Grazfather** [comment]
I can reproduce this

```
gef➤  pcustom Bla $rsp
0x7fffffffe530+0x0000 ptr_vtable_unicode_string : 0x0000000000400550 → <__libc_csu_init+0> push r15 (c_ulong)
0x7fffffffe530+0x0008 field_8 :         4154644528 (c_uint)
0x7fffffffe530+0x000c field_C :         0x0000000000000000 (c_ulong)
gef➤  set *(int*)0x7fffffffe538 = 6
gef➤  pcustom Bla $rsp
0x7fffffffe530+0x0000 ptr_vtable_unicode_string : 0x0000000000400550 → <__libc_csu_init+0> push r15 (c_ulong)
0x7fffffffe530+0x0008 field_8 :         6 (c_uint)
0x7fffffffe530+0x000c field_C :         0x0000000000000000 (c_ulong)
gef➤  set *(int*)0x7fffffffe53c = 4
gef➤  pcustom Bla $rsp
0x7fffffffe530+0x0000 ptr_vtable_unicode_string : 0x0000000000400550 → <__libc_csu_init+0> push r15 (c_ulong)
0x7fffffffe530+0x0008 field_8 :         6 (c_uint)
0x7fffffffe530+0x000c field_C :         0x0000000000000000 (c_ulong)
```

**Comment by Grazfather** [comment]
It's an alignment issue

```
gef➤  pcustom Bla $rsp
0x0000000000000000     03 00 00 00 00 00 00 00 03 00 00 00 06 00 00 00    ................
0x0000000000000010     ef be ad de 00 00 00 00    ........
0x7fffffffe530+0x0000 ptr_vtable_unicode_string : 0x0000000000000003 (c_ulong)
0x7fffffffe530+0x0008 field_8 :         3 (c_uint)
0x7fffffffe530+0x000c field_C :         0x00000000deadbeef (c_ulong)
```

See how it's reporting 0xdeadbeef, even though it should be reporting 0xdeadbeef00000006

**Comment by Grazfather** [comment]
Filed #446 for the bug in Gef (it doesn't print the offset correctly if there is padding).

@ManuSecsearch , you can add `_pack_ = 1` to your `Structure` definition so that your field offsets actually match your naming.
