### ISSUE TITLE
ida-interact binja breakpoint calculation

### ISSUE THREAD

**Issue by Tiecoon** [hugsy/gef#408]
on the line https://github.com/hugsy/gef/blob/aacafb1ac175ebf0845614859dd6228c16b6623e/scripts/binja_gef.py#L63 
self.base being used in certain calculations seems to put breakpoints at the wrong spot
https://github.com/hugsy/gef/blob/aacafb1ac175ebf0845614859dd6228c16b6623e/scripts/binja_gef.py#L184
In my testing bp is the correct address and self.base is shifting it into another location.
I am not sure of the original intention of the base and wether removing it would be correct for all scenarios. It seems to be for changing the offset incase Binja loads it at another address due to it possibly being PIE, but currently seems broken.

Tested on x86_64 Arch linux, gdb 8.2, using https://github.com/hugsy/gef/pull/407
Binary Ninja 1.1.1350-dev Personal

**Comment by hugsy** [comment]
Hi,

Sorry for the delay in response, I'll be looking into that. I've been meaning to refresh this script mostly due to various changes in the Binja API.

Thanks for reporting the issue.

**Comment by hugsy** [comment]
This will take longer than I thought. There are a bunch of changes to provide for both IDA and Binja, this issue is just one of them, so I'll be removing this from the next release and create a dedicated project.

**Comment by iamvince** [comment]
It also has issue in ida sync as well, output:
[!] Command ‘ida-interact’ failed to execute properly, reason: <Fault 1: “type ‘of exceptions.AttributeError’>: Gef instance has no attribute ‘Sync’”> 

i did use 
# gef-remote -q <target:port>
Where port is set for qemu-arm

**Comment by Tiecoon** [comment]
I believe you want https://github.com/hugsy/gef/issues/403

it should be fixed in dev I'm not sure whether its been merged into master yet

**Comment by hugsy** [comment]
Cleanup
