### ISSUE TITLE
Printing context fails when source filename / path too long

### ISSUE THREAD

**Issue by Schaback** [hugsy/gef#409]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Arch Linux
  * Architecture: x64
  * GDB version (including the Python library version): GNU gdb (GDB) 8.2 / Python 3.7.1

### Step 2: Describe your problem
The "context" command fails at printing the section title for "source" when filenames become too long.
#### Steps to reproduce
  0. (Optional: open a small terminal)
  1. Create a ".cpp" file with a long name (longer than would fit on one line of your terminal)
  2. Build with debugging flags
  3. Open in GDB
  4. Set breackpoint anywhere
  5. Run

#### Observed Results

  * All sections up to "source" are printed successfully
  * Printing the title of "source" fails with:
`[!] Command 'context' failed to execute properly, reason: Sign not allowed in string format specifier`

#### Expected results

  * All sections print
  * The filename is truncated or displayed over multiple lines

#### Analysis

The error occurres here, I think:
https://github.com/hugsy/gef/blob/aacafb1ac175ebf0845614859dd6228c16b6623e/gef.py#L7157-L7159
Under the conditions described above `self.tty_columns - trail_len` becomes negative which Python doesn't like.

### Workaround

Replace `self.tty_columns - trail_len` with `max(self.tty_columns - trail_len, 0)`

**Comment by Grazfather** [comment]
Thank you. Good find.

**Comment by Grazfather** [comment]
<img width="477" alt="1__tmux" src="https://user-images.githubusercontent.com/497310/52516716-5596e100-2be4-11e9-8157-0a416726ce1a.png">

**Comment by Grazfather** [comment]
(force pushed the fix to 4da11d3)
