### ISSUE TITLE
The LRU cache in get_gef_setting cause gef to read stale values

### ISSUE THREAD

**Issue by extremecoders-re** [hugsy/gef#410]
* [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

$ uname -a
Linux extremecoders-re-emb-6474617 4.9.120-c9 #1 SMP Wed Aug 15 22:48:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ gdb --version
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
```
Python 2.7

### Step 2: Describe your problem

The lru cache in `get_gef_setting` causes it to read stale values. 

#### Steps to reproduce

1. Debug any binary.
	```
	$ gdb -q /bin/ls          
	GEF for linux ready, type `gef' to start, `gef config' to configure
	69 commands loaded for GDB 7.7.1 using Python engine 3.4
	[*] 4 commands could not be loaded, run `gef missing` to know why.
	Reading symbols from /bin/ls...(no debugging symbols found)...done.
	```

2. Generate a pattern of 8 bytes.
	```
	gef➤  pattern create 8
	[+] Generating a pattern of 8 bytes
	aaaaaaaa
	[+] Saved as '$_gef0'
	```
3. Now generate a pattern of 12 bytes
	```
	gef➤  pattern create 12
	[+] Generating a pattern of 8 bytes
	aaaaaaaa
	[+] Saved as '$_gef1'
	```

#### Observed Results

In both cases, it generates a pattern of 8 bytes.

#### Expected results

It should have generated a pattern of 12 bytes in the second case.

### Root cause

The `pattern create` command saves the current size in the `pattern.length` setting. 
https://github.com/hugsy/gef/blob/aacafb1ac175ebf0845614859dd6228c16b6623e/gef.py#L8472-L8477

This is later retrieved by the call to `get_gef_setting`
https://github.com/hugsy/gef/blob/aacafb1ac175ebf0845614859dd6228c16b6623e/gef.py#L8482-L8483

Since method `get_gef_setting` uses a cache, it returns the old value (8) and not the updated value (12).

https://github.com/hugsy/gef/blob/aacafb1ac175ebf0845614859dd6228c16b6623e/gef.py#L1168-L1177

### Possible Fix

Removing the LRU cache decorator from method `get_gef_setting` or flushing the cache by a call to `reset_all_caches` in the `set_gef_setting` fixes the issue.

It may also be possible to selectively evict the corresponding stale entry (like `pattern.length` here) from the cache rather than do a complete flush on every `set_gef_setting` call.

**Comment by daniellimws** [comment]
This also affects the `heap` series of commands as it uses the old addresses for `arena` from the previous execution.

**Comment by wiredghost** [comment]
add this line to set_gef_setting:
`getattr(sys.modules["__main__"], "get_gef_setting").cache_clear()`

**Comment by Grazfather** [comment]
Thank you for reporting this. I think the way to handle this is to reset the cache in `set_gef_setting`. Ideally it would be a separate cache for only gef settings (See #350)
