### ISSUE TITLE
Renaming functions / symbols / arguments / local variables

### ISSUE THREAD

**Issue by smarek** [hugsy/gef#415]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Linux x64
  * Architecture: x86 binaries, but not limited to those
  * GDB version (including the Python library version):GNU gdb (Debian 7.12-6) 7.12.0.20161007-git, Python 3.5

### Step 2: Describe your problem
reference:
https://reverseengineering.stackexchange.com/questions/20408/renaming-functions-symbols-in-gdb

Would it be possible for GEF to allow renaming local symbols, ie. in the way radare2 does allow that, so that the renamed would show in GEF visual?

This would be tremendously useful, when debugging / reversing binary, which has the symbols obfuscated, and to name arguments based on debugging / observation of data/code flow.

**Comment by hugsy** [comment]
How about just using GDB convenience variables ?

**Comment by smarek** [comment]
@hugsy could you please give out an example?

**Comment by hugsy** [comment]
Say you reverse a super useful function at 0x402a00 you can do

```
gef➤  set $SuperUsefulFunction= 0x402a00
gef➤  b *$SuperUsefulFunction
Breakpoint 1 at 0x402a00
``` 

Same goes for global variables, this doesn't make much sense on local ones.

**Comment by smarek** [comment]
@hugsy well sorry, this is not what I've asked for. Is it possible to rename (using GDB available commands)  function so that when debugging (step next break)  this function will appear under different name in all places (registers, stack, code, threads and trace) ?

I want to understand the code better while debugging, and defined convenience variables do not show in mentioned places

**Comment by hugsy** [comment]
That would require to edit (or even create for stripped binaries) DWARF symbols which could be a project on its own. GDB doesn't offer any API to do such things, so no GEF cannot.

A probably better way would be to debug in parallel with IDA (using [ida_gef](https://github.com/hugsy/gef/blob/dev/scripts/ida_gef.py) for instance) to synchronize the disassembly view of IDA with your debugging session in GDB. 

Other than that, I don't see any solution to what you try to do.

Cheers.

**Comment by smarek** [comment]
Ok, that is clear enough, thank you.

One idea, when using "gdb convenience variables", would it be possible to display the appropriate variable along the stack/registers/code/trace where it applies?
That wouldn't require edit of DWARF symbols, only GEF to load existing variables (or proxy when setting them) and display them in appropriate places.

**Comment by hugsy** [comment]
True but that would kill the perf. Top of that, the it would be crazy long to implement this on all the architectures GEF supports.

If you want to contribute, we gladly take PRs 😄
