### ISSUE TITLE
Disassemble only shows first 6 instructions

### ISSUE THREAD

**Issue by tapir** [hugsy/gef#421]
Your issue will be closed unless you confirm the following:
  * [X] Did you use the latest version of GEF from `master` branch?
  * [X] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [X] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Arch Linux
  * Architecture: amd64
  * GDB version (including the Python library version): 8.2.1

### Step 2: Describe your problem

According to documentation `cs some_func` disassembles the given function however it only prints the first 6 instructions of the given function whereas gdb disassemble will give you everything until `ret` or better it will allow you to specify a length like this `disassemble main, +128`.
I'm guessing the functionality is there and it's just not documented?

Thanks

**Comment by hugsy** [comment]
```
gef➤  help cs-dis
Alias for 'capstone-disassemble': Use capstone disassembly framework to disassemble code.
Syntax: capstone-disassemble [LOCATION] [[length=LENGTH] [option=VALUE]]
Example: capstone-disassemble $pc length=50
```

**Comment by Grazfather** [comment]
I pushed 1837b4d to dev to improve the docs
