### ISSUE TITLE
Heap command failed

### ISSUE THREAD

**Issue by zjgcjy** [hugsy/gef#423]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System:
    Manjaro 18.0.3 Illyria
  * Architecture:
    x86_64 Linux 4.19.23-1-MANJARO
  * GDB version (including the Python library version):
   gdb: 8.2.1
   glibc: 2.28
   python: 3.7

#### Steps to reproduce

just type heap command after the malloc() in source code.

![snipaste_2019-02-26_13-20-12](https://user-images.githubusercontent.com/27962618/53389177-4926cc80-39c9-11e9-8e44-ec7cd473b221.png)

#### Expected results

  * Does not find the glibc?
  * Does the glibc too new and cause something unknowned problem.
  * Does Arch linux cause this?
  * In pwndbg, heap command throws exception as gef, it shows `gdb.error: No struct type named malloc_state`

**Comment by hugsy** [comment]
You're missing the Glibc symbols. No problem with GEF, closing.
