### ISSUE TITLE
Feature request: xref-telescope

### ISSUE THREAD

**Issue by io12** [hugsy/gef#425]
We currently have an xref command to compute single xrefs and a telescope command to compute ref chains.

I'm envisioning a command that runs xref recursively, showing a tree visualization of cross-references to an address, with configurable depth (and infinite recursion detection).

It might have a usage of `xref-telescope addr [depth]`.

Gef could also use a library like asciitree to generate the visualization.

**Comment by hugsy** [comment]
I don't see the difference with the existing `xref` command to be honest.
Could you draft a prototype and PR it to the `gef-extras` repo for testing ?

**Comment by io12** [comment]
Ok I just submitted the PR. Should I close this issue now?

**Comment by hugsy** [comment]
Sweet, I'll have a look.

Thanks.
