### ISSUE TITLE
ASLR On/Off Doesn't work

### ISSUE THREAD

**Issue by x30r** [hugsy/gef#426]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System:
Distributor ID: Ubuntu
Description: Ubuntu 17.10
Release: 17.10
Kernel: 4.13.0-46-generic
  * Architecture: x86_64 x86_64 x86_64 GNU/Linux
  * GDB version (including the Python library version): GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1

### Step 2: Describe your problem
On, giving command `aslr off` or `aslr on` doesn't make any changes on using `sudo cat /proc/sys/kernel/randomize_va_space` command. 

#### Steps to reproduce

  1. Open 2 terminal tabs
  2. On 1st tab, `sudo cat /proc/sys/kernel/randomize_va_space` should result in **2**
  3. On 2nd tab, open gef and `aslr off`
  4. Go to tab 1 and again run `sudo cat /proc/sys/kernel/randomize_va_space`

#### Observed Results

  * The value of stack randomization does not change.

#### Expected results

  * Should turn off the aslr value and `sudo cat /proc/sys/kernel/randomize_va_space` should return 0 on `aslr off`

**Comment by hugsy** [comment]
This is not how it's supposed to work.

See the GDB setting `disable-randomization` for reference. The feature works as intended.
