### ISSUE TITLE
checksec shows inaccurate RELRO output

### ISSUE THREAD

**Issue by kernelm0de** [hugsy/gef#430]
Your issue will be closed unless you confirm the following:
  * [X] Did you use the latest version of GEF from `master` branch?
  * [X] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [X] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Ubuntu 18
  * Architecture: x64
  * GDB version (including the Python library version): 8.1.0.20180409

### Step 2: Describe your problem
GEF shows that the binary is full RelRO which is not the case.
#### Steps to reproduce

  1. Load the binary and run checksec

![gef](https://user-images.githubusercontent.com/30472260/54848360-155c6f80-4d07-11e9-9e31-bd3a9d64b3ea.PNG)

![csec](https://user-images.githubusercontent.com/30472260/54848369-1b525080-4d07-11e9-83e9-94517af8ded0.PNG)

Binary: 
[heap_0.zip](https://github.com/hugsy/gef/files/2998025/heap_0.zip)

**Comment by hugsy** [comment]
Fixed by #431
