### ISSUE TITLE
How to execute the previous command while press the Enter

### ISSUE THREAD

**Issue by rhirufxmbcyj** [hugsy/gef#432]
Is gef blocked this feature?
How to configure it to support this feature?
Thanks a million

**Comment by rhirufxmbcyj** [comment]
use gdb debug a program without gef,press the Enter can execute previous command
but with gef can not

**Comment by daniellimws** [comment]
Could you provide an example? Normally this does work.

**Comment by rhirufxmbcyj** [comment]
> 
> 
> Could you provide an example? Normally this does work.

thanks for your answer,below is gif

CentOS / 7.5 x86_64
GNU gdb (GDB) 8.2

![](https://note.youdao.com/yws/public/resource/adac6ad1a584a3d61eb5b9dbddb4c222/xmlnote/89BD7BB51F784D3E8573A7C83C0CADAB/6305)

**Comment by daniellimws** [comment]
@rhirufxmbcyj it's a regression on GDB 8.2. It should be fine with either gdb 8.1 or upgrade to gdb 8.2.1

Look at cyrus-and/gdb-dashboard#128 and #398

**Comment by rhirufxmbcyj** [comment]
that's true, it works
thanks again
