### ISSUE TITLE
cs.disasm type error related to bytearray vs bytes object

### ISSUE THREAD

**Issue by Roguebantha** [hugsy/gef#443]
### Step 1: Describe your environment

  * Ubuntu Linux
  * X86-64 cross debugging ARM
  * 7.1

### Step 2: Describe your problem
It appears on the cstool version that I am using, the bytearray type python object passed to cs_disasm in the unicorn-emulate auto-generated python code inside of the disassmble() function is not a valid format for the instructions. I was able to easily fix this myself by changing the following line:
for i in cs.disasm(code,addr):

to

for i in cs.disasm(bytes(code),addr):
#### Steps to reproduce

  Attempt to run unicorn-emulate -n1

#### Observed Results

  * A stack trace from ctypes, of the exception ctyptes.ArgumentError: argument 2:<class 'TypeError'>: wrong type

Additionally, I've noted that memory that claims it's readable, but is in fact NOT readable by gdb/ptrace (which I've discovered is occasionally true for reasons I know not why) causes unicorn-emulate to fail. It's not an ISSUE per se, but a simple enhancement might be to either ignore these memory regions, or zero-fill them

**Comment by Grazfather** [comment]
Can you provide a sample binary where `unicorn-emulate` doesn't work? What version of capstone are you using?
