### ISSUE TITLE
Cleanup code to become Python3 only

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#457]
Todo:

 - [x] Remove reference to Python2 compatibility layer
 - [x] Update unit tests
 - [x] Update documentation

**Comment by hugsy** [comment]
> Do you want to wait for EOY or should we start now? I'll be so happy to rip that shit out.

Wait the official EOL of Python2 yes.

**Comment by Grazfather** [comment]
We should start it in a side branch, I think, so that on Jan 1 we can merge it into dev and be done with it.

**Comment by hugsy** [comment]
Agreed, let's do that and start it.
Also we should remove some unused branches.
