### ISSUE TITLE
Loading gef breaks gdb's skip functionality

### ISSUE THREAD

**Issue by pzi1337** [hugsy/gef#461]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [X] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [X] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Debian Testing
  * Architecture: x86_64
  * GDB version (including the Python library version): gdb 8.3 / python 3.7.4

### Step 2: Describe your problem

When gef is loaded, gdb does no longer skip functions specified via [gdb's skip command](https://sourceware.org/gdb/onlinedocs/gdb/Skipping-Over-Functions-and-Files.html).

In the following, I, at first, ran `gdb -nh ./testx` (see code snippet below) and skipped the function boring (example taken from gdb manual) via `skip boring`. As expected, stepping through main, the function boring was skipped.
```
(gdb) skip boring 
Function boring will be skipped when stepping.
(gdb) b main 
Breakpoint 1 at 0x1197: file test.c, line 20.
(gdb) r
Starting program: /.../testx 

Breakpoint 1, main (argc=1, argv=0x7fffffffe398) at test.c:20
20		foo(boring());
(gdb) s
foo (a=42) at test.c:10
10		printf("a: %d\n", a);
```

Then I repeated exactly the same test running `gdb ./testx`, which without the `-nh` loads gef in its default configuration. Doing the same steps as with the `-nh`, gdb stepped into the boring function:
```
gef➤  s
boring () at test.c:5
5	int boring() {

```

#### Steps to reproduce

  1. Compile the snippet attached to this bug report (`gcc -g test.c -o testx`)
  2.  Start gdb while loading gef (e.g., `gdb ./testx`)
  3. `skip boring`
  4. `break main`
  5. `run`
  6. `step`

#### Observed Results

gef stepped into the function boring.

#### Expected results

gef should have skipped the function boring, due to the previously issued `skip boring`.

#### Traces

Example program causing the issue described above:
```
#include <stdlib.h>
#include <stdio.h>


int boring() {
	return 42;
}

void foo(int a) {
	printf("a: %d\n", a);
}


void bar(int b) {
	printf("b: %d\n", b);
}


int main(int argc, char *argv[]) {
	foo(boring());
	bar(boring());
	return EXIT_SUCCESS;
}
```

**Comment by daniellimws** [comment]
This is caused by https://github.com/hugsy/gef/blob/dev/gef.py#L9977

You can do `set step-mode off` to disable that setting and the skipping will work.

**Comment by Grazfather** [comment]
@pzi1337 it's fixed on the dev branch, if you'd like to test it out.

**Comment by pzi1337** [comment]
Thank you for the fast answer and fast fix.
Now, with step-mode set to off,  skipping works as expected.
