### ISSUE TITLE
request for set-permission for aarch64

### ISSUE THREAD

**Issue by jinyu00** [hugsy/gef#463]
I find that `set-permission` currently is not work in aarch64, does gef has any plan to support this for aarch64.

**Comment by hugsy** [comment]
Not really, but we do accept PRs.

**Comment by daniellimws** [comment]
You can try changing https://github.com/hugsy/gef/blob/391893c03966c65292dce9c9377298ecdac9bce6/gef.py#L1881-L1882 to 

```
    def mprotect_asm(cls, addr, size, perm):
        _NR_mprotect = 226 
        insns = [
            "str x8, [sp, -16]!",
            "str x0, [sp, -16]!",
            "str x1, [sp, -16]!",
            "str x2, [sp, -16]!",
            "mov x8, {:d}".format(_NR_mprotect),
            "mov x0, {:d}".format(addr),
            "mov x1, {:d}".format(size),
            "mov x2, {:d}".format(perm),
            "svc 0",
            "ldr x2, [sp], 16",
            "ldr x1, [sp], 16",
            "ldr x0, [sp], 16",
            "ldr x8, [sp], 16",]
        return "; ".join(insns)
```

Sorry I don't have an AARCH64 platform to test this now.

**Comment by hugsy** [comment]
It was a bit more complicated than your initial patch @daniellimws , but that was the correct gist.

![image](https://user-images.githubusercontent.com/590234/65394002-18c7c680-dd3d-11e9-869e-4f7c0ad7453b.png)

@jinyu00 Feel free to use it (only in `dev` branch for now)
