### ISSUE TITLE
Clarification about possible bug in GlibcHeapLargeBinsCommand about bins summary

### ISSUE THREAD

**Issue by gipi** [hugsy/gef#467]
I don't know if I'm missing something, but shouldn't be removed the equal to zero condition otherwise the first empty bin would stop the loop causing the summary to be incomplete?

https://github.com/hugsy/gef/blob/9798a2816d21da5a54b979e19c54446e08414ea9/gef.py#L6565-L6570

In case I can submit a patch to fix that.

**Comment by Grazfather** [comment]
Is this the same as #474?

**Comment by gipi** [comment]
probably.

I noticed also that the index of the bin is off by one with respect to the index that I obtain during the execution from GDB (not 100% sure though)

**Comment by hugsy** [comment]
This should have been fixed by now (in `dev` branch).
Closing for housekeeping, re-open if not.
