### ISSUE TITLE
Windbg Alias for "g"

### ISSUE THREAD

**Issue by zachriggle** [hugsy/gef#47]
The current `alias g=run` is different from the Windbg semantics, where `g` and `go` would rather mean `continue`.

I'm not sure if you intended it to be Windbg-compat, but it's next to it so maybe.

**Comment by hugsy** [comment]
Hi @zachriggle ,

Thanks for the feedback. I'm definitely trying to push a compat with WinDBG.

Funny you mention that, I was actually considering adding another a proper `go` equivalent, that would `continue` if the binary is already being debugged, or `run` if not, and also add the possibility to parse convenience variables from the command line (which afaik GDB `run` does not do).

Cheers.

**Comment by hugsy** [comment]
See d6be8e7
