### ISSUE TITLE
Update documentation pages that point to expired asciinema

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#473]
Some documentation pages have external references to an asciinema, which have expired.
As a consequence, the documentation on both pages shows a big ugly "This recording has been archived".

I quickly grep-ed the following pages:
- [x] [`is-syscall`](https://gef.readthedocs.io/en/dev/commands/is-syscall/) (@daniellimws)
- [x] [`syscall-args`](https://gef.readthedocs.io/en/dev/commands/syscall-args/) (@daniellimws)
- [x] [`hijack-fd`](https://gef.readthedocs.io/en/dev/commands/hijack-fd/)  (@hugsy )
- [x] [`set-permission`](https://gef.readthedocs.io/en/dev/commands/set-permission/)  (@hugsy )
- [x] [`pcustom`](https://gef.readthedocs.io/en/dev/commands/pcustom/)  (@rick2600  )

I can think of 2 options:
1. simply replace with screenshots, easy but doesn't really showcase the features;
2. create a YT video, you can point it to your own YT channel, or I can give you access to the GEF channel here : https://www.youtube.com/watch?v=KWG7prhH-ks&list=PLjAuO31Rg972WeMvdR_57Qu-aVM8T6DkQ. That's what I'll do for mine.

Can be done either way, but must be done.

**Comment by Grazfather** [comment]
We could record gifs, as well: https://github.com/faressoft/terminalizer or similar.

**Comment by daniellimws** [comment]
We're done here?

**Comment by hugsy** [comment]
We are! Thanks!
