### ISSUE TITLE
`heap bins` not working correctly with large bins in libc 2.29, ubuntu 19.04

### ISSUE THREAD

**Issue by farazsth98** [hugsy/gef#474]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Ubuntu 19.04
  * Architecture: x86_64
  * GDB version (including the Python library version): GDB 8.2.91.20190405-git, Python 3.7.3

### Step 2: Describe your problem

I was trying to understand Balsn CTF's LazyHouse walkthrough from HITCON 2019. Initially, a 0x500 sized chunk is freed. Following that, `heap bins` shows the chunk correctly inserted into the unsorted bin.

Next, a 0x600 sized chunk is added. This will send the 0x500 sized chunk into a large bin. However, when using `heap bins`, the large bin and unsorted bin are both shown as empty. I have manually checked the main arena in memory to ensure that the chunk does indeed exist in the large bin. `pwndbg` seems to work just fine too.

#### Steps to reproduce

  1. Copy the code shown below and compile it with `gcc test.c -o test`
  2. Run it in gdb, ctrl + C, and then type in `heap bins`
  3. The 0x500 sized chunk should be in a large bin as explained by the comments, however, `heap bins` will show the large bin as empty.

#### Observed Results

Large bin is empty even after a chunk is inserted into it.

#### Expected results

Large bin should contain the chunk inserted into it.

```c
#include <stdlib.h>

int main(void)
{
    char *a = malloc(0x500); // unsorted bin chunk
    char *b = malloc(0x80); // prevent consolidation with top

    free(a); // Send chunk a to unsorted bin
    char *c = malloc(0x600); // Send chunk a to large bin
    while(1);
}
```

**Comment by hugsy** [comment]
This has been fixed with #488, closing.
