### ISSUE TITLE
Why do we have to manually specify the PID when using gef-remote?

### ISSUE THREAD

**Issue by jr64** [hugsy/gef#48]
Hi, first of all thanks for making gef so awesome.

When looking through your source code I was wondering why you make the user specify the PID of the program to debug when using gef-remote.  Why not just use "gdb.selected_inferior().pid" like you do locally? A quick test I made showed that it seems to work.
 
Background: I thought about adding support for remotely specifying the program to debug (with "gdbserver --multi" and "set remote exec-file" ) but this obviously requires dynamic detection of the debugee PID as it isn't running yet at the time you instruct gdb to connect. I thought I'd better ask you if there is some kind of bug or undocumented behavior with selected_inferior before I start implementing it like this.

**Comment by hugsy** [comment]
Hi @jr64 ,

Thanks for the feedback, I'm glad you enjoy the tool.

That's an excellent question... I know I did it for a reason, I can't remember which one :disappointed: From the (re-)tests I'm doing now `gdb.selected_inferior().pid`  seems to work well as you described. I'm gonna do some extra tests and re-arrange the code if I cannot find a good reason that forces to manually specify the PID.

**Comment by jr64** [comment]
Great work! I've sent you a pull request (#50)  that adds support for remotely specifying the debugee and re-running the target when in extended-remote mode. I don't have much experience with scripting gdb so I hope it doesn't break anything.

**Comment by hugsy** [comment]
Hi there, 
I'll review your PR very shortly and thanks for contributing !

Cheers
