### ISSUE TITLE
Cannot write to tempdir on shared server

### ISSUE THREAD

**Issue by lzutao** [hugsy/gef#486]
_Originally posted by @hugsy in https://github.com/hugsy/gef/pull/480#issuecomment-555601125_

After some talks, we've come to agree that `~/.cache` is not a good candidate for storing user temporary content. The idea is that the content in `GEF_TEMP_DIR` is disposable, and `~/.cache` is never emptied (except if explicitly `rm`-ed by the user).

You did raise a good point related to the squatting in `/tmp`. A good way mitigate that would be to add some random value generated when gef starts like `/tmp/<random_string>`. This also would pose a problem for people who use gef a lot for remote sessions, as they will constantly have to re-download the content they already have (since a new /tmp location will be created every time they start gef).

What I would prefer is to simply let the user decide of the location via a `gef config` setting: leave `GEF_TEMP_DIR` assigned to `/tmp/gef` by default, but load the global setting in case like yours where people do not to use that location.

Feel free to update this PR if you want to implement that, or I can take care of this soon.

Thanks.

**Comment by hugsy** [comment]
5494cf0 should do it more cleanly: there is a new global option `gef.tempdir` that can be defined.  
@lzutao feel free to test it and give us feedback.

**Comment by hugsy** [comment]
No reply from @lzutao but closing because it was fixed.
