### ISSUE TITLE
Already install ropper in python3 but gef show Command ''roapper" is missing

### ISSUE THREAD

**Issue by xiaolitongxue666** [hugsy/gef#494]
Enviroment: Ubuntu 14.04
GDB:GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Python3:Python 3.7.3

pip3 install ropper
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Requirement already satisfied: ropper in /usr/local/lib/python3.7/site-packages/ropper-1.13.3-py3.7.egg (1.13.3)
Requirement already satisfied: filebytes>=0.10.0 in /usr/local/lib/python3.7/site-packages/filebytes-0.10.0-py3.7.egg (from ropper) (0.10.0)
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

when i exec command ropper , it all right
 ⚡ / ropper
(ropper)> 

But the gef still show missing ropper.

**Comment by hugsy** [comment]
https://gef.readthedocs.io/en/master/faq/#gef-says-missing-modules-but-im-sure-ive-installed-them-whats-up-with-that

**Comment by xiaolitongxue666** [comment]
> https://gef.readthedocs.io/en/master/faq/#gef-says-missing-modules-but-im-sure-ive-installed-them-whats-up-with-that

First, thanks for you replay, i readed you link ,and reinstall capstone unicorn keystone-engine ropper all of them install success .
When i type pip3 list shows like this:
Package    Version
---------- -------
capstone   3.0.4  
filebytes  0.10.0 
pip        19.0.3 
ropper     1.13.5 
setuptools 40.8.0 
unicorn    1.0.1  

But even i can see this list , when i run gdb gef is still shows :
gef➤  gef missing 
[*] Command `ropper` is missing, reason  →  Missing `ropper` package for Python3, install with: `pip3 install ropper`.

**Comment by hugsy** [comment]
Hi,

Use this script, which should fix your issue: https://github.com/hugsy/stuff/blob/master/update-trinity.sh

Note that this is a setup issue, not a bug from the tool. Feel free to come on the IRC channel to get further help but since it's not a bug, I won't be digging this any further.

Good luck.

**Comment by xiaolitongxue666** [comment]
> Hi,
> 
> Use this script, which should fix your issue: https://github.com/hugsy/stuff/blob/master/update-trinity.sh
> 
> Note that this is a setup issue, not a bug from the tool. Feel free to come on the IRC channel to get further help but since it's not a bug, I won't be digging this any further.
> 
> Good luck.

Thanks a lot , it works !!!! :+1:  you are the best .
