### ISSUE TITLE
ARM arch, context disassemble not correct showing ARM and THUMB modes

### ISSUE THREAD

**Issue by dmitrykok** [hugsy/gef#499]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Linux ioarm 4.14.54-grsec #11 SMP Wed Jul 11 17:32:01 CEST 2018 armv7l armv7l armv7l GNU/Linux
  * Architecture: armv7
  * GDB version (including the Python library version): 
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Python 3.6.8

### Step 2: Describe your problem
debugging on ARM - program started executing in THUMB instruction set when jumping between modes ARM/THUMB context disassemble always show as THUMB. Flags register shown correct when THUMB bit is on or off. 

actually I fixed it locally - my quick fix is to remove "@lru_cache()" attribute from "class ARM(Architecture).is_thumb()" function. ARM/THUMB mode switching occurs in run-time when jump/branch to address with low significant bit is 1 it switches to THUMB mode if bit is 0 ARM mode. Looks like this property is cached and that leads to wrong behavior.

line: 1720
```python
    # @lru_cache()
    def is_thumb(self):
        """Determine if the machine is currently in THUMB mode."""
        #print("class ARM is_thumb {}".format(get_register("$cpsr")))
        return bool(is_alive()) and bool(get_register("$cpsr") & (1<<5))
```

#### Steps to reproduce

  1. run debugger on ARM arch
  2. start executable in THUMB mode
  3. run code that switching between ARM and THUMB 
  4. context disassemble always show in THUMB (thumb bit in cpsr register show real mode also context flags show correct mode)

#### Observed Results

  context disassemble always show in THUMB when executable starts as THUMB even is running mode is ARM

#### Expected results

 show context disassemble in correct instruction set

**Comment by hugsy** [comment]
Hi @dmitrykok 

Can you provide a test case?
