### ISSUE TITLE
Command 'context' failed to execute properly, reason: Cannot locate object file for block.

### ISSUE THREAD

**Issue by 8-5-0** [hugsy/gef#508]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System / Distribution: docker ubuntu:18.04
  * Architecture: x86-64
  * GDB version (including the Python library version - can be found via `$ gdb -ex "pi import sys;print(sys.version)"`): 
3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0]

### Step 2: Describe your problem
gef context command cannot display calling state. The error message is "Command 'context' failed to execute properly, reason: Cannot locate object file for block."
```
     0x4011e9 <main+87>        call   0x4010a0 <exit@plt>
 →   0x4011ee <main+92>        call   0x4013ef <menu>
   ↳    0x4013ef <menu+0>         push   rbp
        0x4013f0 <menu+1>         mov    rbp, rsp
        0x4013f3 <menu+4>         lea    rdi, [rip+0xd00]        # 0x4020fa
        0x4013fa <menu+11>        call   0x401030 <puts@plt>
        0x4013ff <menu+16>        lea    rdi, [rip+0xd02]        # 0x402108
        0x401406 <menu+23>        call   0x401030 <puts@plt>
[!] Command 'context' failed to execute properly, reason: Cannot locate object file for block.
0x00000000004011ee in main ()
gef➤
```

#### Steps to reproduce

  1. gdb binary_file
  2. run until `call` instruction
#### Expected results
I searched the Internet, only find some gdb bug report related to my problem, maybe it's a gdb bug.

**Comment by daniellimws** [comment]
This command `gdb -ex "pi import sys;print(sys.version)"` gives the python version. Can you check your GDB version with `gdb --version`?

**Comment by 8-5-0** [comment]
gdb version is `GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git`

**Comment by daniellimws** [comment]
Can you share the binary so that we can reproduce and see what went wrong?

**Comment by 8-5-0** [comment]
I've tested `/bin/cat` and some other binary. The error message appeared no matter what binary I use.

**Comment by daniellimws** [comment]
Hmm, I am using the same version of GDB as you, but I'm not getting the error message with `/bin/cat`.

I'm also running Ubuntu 18.04 on Docker.

**Comment by daniellimws** [comment]
Oh I was on the `dev` branch, after changing to the `master` branch I get the error too. I'll check it out.

**Comment by daniellimws** [comment]
@hugsy The error is caused by the change here https://github.com/hugsy/gef/commit/cae071ef3248eba511491257e292e559f8eae8ac#diff-c1353c3dea65fb78135f4781a0dddab0L7472-R7472
Should we revert to the original version?
