### ISSUE TITLE
Add a new convenience variable $_libc

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#509]
From IRC:
```
2020-03-15 19:05:18     dwe     is there a way to set a breakpoint relatvie to the libc-base?
2020-03-15 19:05:47     dwe     *relative
```

The idea would be to expose a new convenience variable `$_libc` (internally similar to [`$_heap`](https://github.com/hugsy/gef/blob/dev/gef.py#L9217-L9236)) so we can do stuff like `pie br $_libc(0x1337)`

**Comment by daniellimws** [comment]
If anyone wants to work on this, can refer to #339

**Comment by Grazfather** [comment]
What's wrong with `$_base("libc")`

**Comment by hugsy** [comment]
> What's wrong with `$_base("libc")`

Nothing I just forgot about it.
😆

Instead of touching the code, I might just use this to document it. Thanks for the reminder...

**Comment by hugsy** [comment]
See https://gef.readthedocs.io/en/master/commands/functions/
