### ISSUE TITLE
Add `start` enhancement

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#51]
On stripped binaries, where `main` isn't defined, vanilla gdb and gef don't work. peda, however, gets it working. See [here](https://github.com/longld/peda/blob/master/peda.py#L3936). Can you add something similar?

**Comment by hugsy** [comment]
Use
`entry-break`

FYI this command existed in `gef` way before `peda` :smile:

**Comment by hugsy** [comment]
Now you also have the alias `start` for the same command.

Cheers,

**Comment by Grazfather** [comment]
Solid. That'll help since start is in my muscle memory :)
