### ISSUE TITLE
 arm-none-eabi-gdb-py can not run

### ISSUE THREAD

**Issue by SourceLink** [hugsy/gef#513]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x ] Did you use the latest version of GEF from `master` branch?
  * [x ] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [ x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System / Distribution: Linux Erazer 4.4.0-142-generic #168-Ubuntu
  * Architecture: x86_64
  * GDB version (including the Python library version):  
GNU gdb (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 8.3.0.20190709-git

### Step 2: Describe your problem

```
➜  arm-none-eabi-gdb-py 
GNU gdb (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 8.3.0.20190709-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
  File "/home/sourcelink/.gdbinit-gef.py", line 908
    pattern_libc_ver = re.compile(rb"glibc (\d+)\.(\d+)")
                                                       ^
SyntaxError: invalid syntax
```

Type "apropos word" to search for commands related to "word".
  File "/home/sourcelink/.gdbinit-gef.py", line 908
    pattern_libc_ver = re.compile(rb"glibc (\d+)\.(\d+)")

is pyhton version problem?

**Comment by yehorcc** [comment]
Same situation. I am on Debian Strech host, trying to use gef with arm-none-eabi-gdb-py or arm-none-eabi-gdb. Error is the same for both of them. Host gdb loads gef with no problems.
Output of arm-none-eabi-gdb 1.bin:

GNU gdb (7.12-6+9+b2) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
...
This GDB was configured as "--host=x86_64-linux-gnu --target=arm-none-eabi".
...
  File "/home/yehor/gef/gef.py", line 908
    pattern_libc_ver = re.compile(rb"glibc (\d+)\.(\d+)")
                                                       ^
SyntaxError: invalid syntax
Reading symbols from 1.bin...done.

**Comment by SourceLink** [comment]
> Same situation. I am on Debian Strech host, trying to use gef with arm-none-eabi-gdb-py or arm-none-eabi-gdb. Error is the same for both of them. Host gdb loads gef with no problems.
> Output of arm-none-eabi-gdb 1.bin:
> 
> GNU gdb (7.12-6+9+b2) 7.12.0.20161007-git
> Copyright (C) 2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
> ...
> This GDB was configured as "--host=x86_64-linux-gnu --target=arm-none-eabi".
> ...
> File "/home/yehor/gef/gef.py", line 908
> pattern_libc_ver = re.compile(rb"glibc (\d+).(\d+)")
> ^
> SyntaxError: invalid syntax
> Reading symbols from 1.bin...done.

arm-none-eabi-gdb-py it only supports python2.7, so should modified gdbinit-gef.py:

https://github.com/hugsy/gef-legacy

**Comment by hugsy** [comment]
> arm-none-eabi-gdb-py it only supports python2.7, so should modified gdbinit-gef.py:
> 
> https://github.com/hugsy/gef-legacy

Yeah, it looks like a Python2 related thing, and since last Jan. we don't support Python2 any longer I'm closing this issue.
Re-open with more information about your setup if you think it's a mistake.

**Comment by iddoeldor** [comment]
I have the same issue with py3.6

```
$ ldd $(which gdb) | grep python
        libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007f9c06c89000)
$
```
