### ISSUE TITLE
Context failed to execute properly on MIPS target (reason null)

### ISSUE THREAD

**Issue by pedrib** [hugsy/gef#514]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System / Distribution: Debian 10
  * Architecture: local: amd64; remote: mips
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`: 
```
8.2.1
3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0]
```

### Step 2: Describe your problem
When attaching to a remote MIPS router using gdb-multiarch and gef, I get the following message:
```
[!] Command 'context' failed to execute properly, reason: 
```
(reason is null)
This only happens when I attach gdbserver to an already running process; if I start the process with gdbserver, no such message appears and context is displayed correctly!

#### Steps to reproduce

  1. Start a process (cat) on the remote MIPS target
  2. Attach gdbserver to it (gdbserver --attach :29383 <PID>)
  3. Connect gdb-multiarch to it on the host side (target remote <IP>:29383)
  4. Watch context fail

#### Minimalist test case

*cat* binary attached

#### Observed Results

  * What happened?  This could be a description, log output, etc.
[!] Command 'context' failed to execute properly, reason:

#### Expected results

  * What did you expect to happen?
Full context is displayed

#### Traces

```

─────────────────────────────── Exception raised ───────────────────────────────
AssertionError:
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/bin/gef/gef.py", line 2478, in get_register()
    →     assert(regname[0] == '$')
↳ File "/bin/gef/gef.py", line 2295, in is_branch_taken()
    →     taken, reason = get_register(ops[0]) == 0, "{0[0]} == 0".format(ops)
↳ File "/bin/gef/gef.py", line 7384, in context_code()
    →     is_taken, reason = current_arch.is_branch_taken(insn)
↳ File "/bin/gef/gef.py", line 7235, in do_invoke()
    →     self.layout_mapping[section]()
↳ File "/bin/gef/gef.py", line 2403, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/bin/gef/gef.py", line 248, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "/bin/gef/gef.py", line 3803, in invoke()
    →     bufferize(self.do_invoke)(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
  252  q
  253  target remote 192.168.1.1:29383
  254  q
  255  target remote 192.168.1.1:29383
  256  q
  257  gef.debug
  258  gef debug
  259  gef.debug
  260  gef config gef.debug 1
  261  target remote 192.168.1.1:29383
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 8.2.1
* Python: 3.7.3 - final
* OS: Linux - 5.5.5 (x86_64)

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
────────────────────────────────────────────────────────────────────────────────
```

**Comment by pedrib** [comment]
[cat.zip](https://github.com/hugsy/gef/files/4401408/cat.zip)

**Comment by hugsy** [comment]
Use `gef-remote` instead of `target remote`

**Comment by pedrib** [comment]
Thanks, that solves it! Not sure if it's in the docs or not, or ideally if you can trigger the gef remote when the target remote command is involved for the noobs like me.

**Comment by pedrib** [comment]
@hugsy how do I disconnect from a remote target? If the target kills the connection and I try to use gef-remote I get this:
```
[!] You already are in remote session. Close it first before opening a new one...
```
