### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by mcgdb** [hugsy/gef#515]
**Is your feature request related to a problem? Please describe.**
I'm doing some development on the ESP32 with an FTDI debugger...Love the project and would like to see support for their weird core so I can keep using GEF's awesome features.

**Describe the solution you'd like**
Support for the Xtensa LX6 core(s).

**Describe alternatives you've considered**
I've looked around a bit at other GDB supplicants, but then again, none of them are GEF, so how good could they be?  :)

**Additional context**
I'd like to help if I can.  If adding support for another device is like adding a class or something similar to an existing example, then I'd be happy to help!

**Comment by Grazfather** [comment]
This would be cool, but like with the 68k PR we've had, we probably don't want it builtin to here. This would be great for gef-extras, where architectures could be imported.

**Comment by dale6998** [comment]
Thanks...Are there any docs or issues I can reference to add CPU support in to gef-extras?  I guess the 68k PR would be a good place to start..

**Comment by Grazfather** [comment]
We don't have support for it. I could maybe work on this. See #516

**Comment by Grazfather** [comment]
In the meantime, you can probably get pretty reasonable support working by making a dummy architecture that defines just the registers it needs.

**Comment by hugsy** [comment]
@dale6998 To correctly add a new arch (i.e. integrate, and test), we need solid ways (also free) to test GEF against it. Do you have such environment ready to share with us? A QEMU image with a "modern" Linux (i.e. not < 4.0) would be ideal.

**Comment by pannzh** [comment]
Instead of adding a new arch, is there a fallback "light mode" that collects and shows gdb register/disassembly/source info when single steping? It's also useful when doing on-chip debugging since showing full gef context may cause multiple flash r/w and take quite some time.

**Comment by daniellimws** [comment]
@pannzh You can configure what is shown in the `context` view, as shown in the [examples](https://gef.readthedocs.io/en/master/commands/context/#examples).

To show only the registers, you can do

```
gef➤ gef config context.layout "regs"
```

**Comment by pannzh** [comment]
@daniellimws What I mean is to create a dummy `Architecture` that supports all other unsupported CPUs such as ESP32/Xtensa, which shows basic context infomation(e.x initialize all_registers with gdb `info registers`). However I'm not sure whether it's trivial to achive within gef's codebase, or maybe it's just better to create another file like `gef-lite.py` ?

**Comment by Grazfather** [comment]
Looks like you mean #316.

Basically, without an arch found gef could use the reg list provided by gdb (gdb would still have to support it). that's how things like gdb-dashboard work with e.g. avr
