### ISSUE TITLE
Add support for 'pluggable' architectures

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#516]
I would be nice if we could add more esoteric architectures to `gef-extras` that would be loaded it.

1. Add support to manually set the arch
2. These plugins would have to register somehow
3. Probably have a callback that can 'check' if they are compatible with the current binary (like how loader plugin in ida/binja can check if they loaded binary is one they can load).

This would let us do a bunch:
1. Add m86k support (#453)
2. Add ESP32 support (#515)
3. Fix the xPSR issue with people who do ARM using a black magic probe. (#320)

**Comment by hugsy** [comment]
I think this should go in https://github.com/hugsy/gef/projects/3

I'm totally for it, but IIRC we already discussed about it, the hardest part is having recent working dev environment, and ways for (unit-)testing. Then it got to a stall. 

I remember spending way too long on the m68k to get a good qemu env, and got nowhere.
