### ISSUE TITLE
The install script should use "echo ... >>" instead of "echo ... >"

### ISSUE THREAD

**Issue by aj3423** [hugsy/gef#522]
Lots of content in .gdbinit was deleted by this install script...

**Comment by Grazfather** [comment]
We cannot guarantee it will work if there is other stuff in there. It's up to you to back up what's in gdbinit if you care.

**Comment by hugsy** [comment]
It doesn't deleted anything, you're free to revert it: https://github.com/hugsy/gef/blob/master/scripts/gef.sh#L3

**Comment by aj3423** [comment]
> It doesn't deleted anything, you're free to revert it: https://github.com/hugsy/gef/blob/master/scripts/gef.sh#L3

Got it. Thanks.
