### ISSUE TITLE
Enhance "pattern create" to have feature-parity with PEDA

### ISSUE THREAD

**Issue by ZacharyConlyn** [hugsy/gef#524]
**Is your feature request related to a problem? Please describe.**

PEDA has three advantages with pattern create over GEF in my opinion:

1) PEDA lets you specify the pattern size in hex with a leading `0x`

2) PEDA lets you save the pattern to a file. This makes it easy to do something like `run < pattern.txt` I don't know how to do `run < $_gef0`; is there an easy way to do that? If so, that would eliminate this issue. But the documentation showed how to create the variable, not how to use it easily.

3) PEDA lets you create a pattern without a specified target (i.e. you can type `file ./my_program` *after* you create the pattern, but GEF does not allow this)

**Describe the solution you'd like**

I would like to see GEF's pattern create to have the option to be redirected to a file and specified independent of a binary. A bit more thorough documentation on how to use the pattern in common ways might be helpful as well.

**Additional context**

Thanks for your consideration.

**Comment by hugsy** [comment]
Hi,

 * The first point can be done easily. 
 * For the point 2 , use `gef run $_gef0`
 * For the point 3: GEF `pattern` command is compatible with `pwntools`'s [`cyclic`](https://docs.pwntools.com/en/stable/util/cyclic.html). To create a pattern from the command line, use pwntools:
```bash
$ pwn cyclic 16
aaaabaaacaaadaaa   
```
Which you can redirect easily in a file. This can be also invoked from GEF:
```
gef➤  !pwn cyclic -n 8 32
```

Thanks for the comment.

**Comment by ZacharyConlyn** [comment]
`gef run $_gef0` Does not seem to work for me. That seems to be using $_gef0 as an argument, rather than redirecting standard in. Here is the difference:

`$ gdb-peda $(which wc)
gdb-peda$ run < pattern.txt 
Starting program: /usr/bin/wc < pattern.txt
  0   1 256
[Inferior 1 (process 5800) exited normally]
`

vs

`gef➤  gef run $_gef0
/usr/bin/wc: aaaaaaaabaaaaaaacaaaaaaadaaaaaaaeaaaaaaafaaaaaaagaaaaaaahaaaaaaaiaaaaaaajaaaaaaakaaaaaaalaaaaaaamaaaaaaanaaaaaaaoaaaaaaapaaaaaaaqaaaaaaaraaaaaaasaaaaaaataaaaaaauaaaaaaavaaaaaaawaaaaaaaxaaaaaaayaaaaaaazaaaaaabbaaaaaabcaaaaaabdaaaaaabeaaaaaabfaaaaaabgaaaaaab: File name too long
[Inferior 1 (process 5812) exited with code 01]
`

**Comment by hugsy** [comment]
What you are doing are 2 different things:

```
run < pattern.txt
```
reads from stdin the content of the file pattern.txt

```
gef run $_gef0
```
provides to `wc` the command line argument whose content is `$_gef0` (so a really long string, which way more than `MAX_PATH`). That's why `wc` returns `File name too long`. 

Again, that's 2 totally different things, which have nothing to do with GEF itself.

**Comment by ZacharyConlyn** [comment]
I get what is going on, but the thread was:

> 2. PEDA lets you save the pattern to a file. This makes it easy to do something like run < pattern.txt

Then you said:

> For the point 2 , use gef run $_gef0

Then I pointed out it doesn't do the same thing. And you agree. So it seems like the best way to recreate point 2 is ` !pwn cyclic -n 8 256 > pattern.txt` ?

**Comment by hugsy** [comment]
FWIW `run < pattern.txt` is **not** PEDA specific, but GDB

Glad you worked it out.

Your "point 1" was implemented in `dev`. Feel free to try it.
