### ISSUE TITLE
Port some features from dill to gef

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#534]
See https://github.com/De4dCr0w/green-dill/blob/master/dill.py (MIT license)

 - `ktask`, `kbase` should be trivial to implement using GEF's builtin primitives
 - `kstruct` can be made as a `pcustom` extra plugin

**Comment by Grazfather** [comment]
Does GEF work well enough for kernel debugging? We'd have to make sure that actually works before we work on kernel-specific commands.

That said, this functionality would be very nice to have.

**Comment by fibonascii** [comment]
Are ktask, kbase, and kstruct the only ones we want to convert? 

Or is that just an initial list of ones that are the priority/seemingly the easiest to move over?

**Comment by hugsy** [comment]
No particular order, they are just some of interest.

Also, now the `pcustom` also works recursively (in `dev` only for now) making it easy for complex structures to use this feature.

**Comment by hugsy** [comment]
Can be now tracked [here](https://github.com/hugsy/gef/projects/6). Closing
