### ISSUE TITLE
Feature request: Highlight flags in consideration when at a conditional

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#54]
This is something I suggest in PEDA, but since I like GEF more now I thought I'd suggest it here.

you show which flags are set nicely

```bash
Flags: [ carry  PARITY  adjust  zero  sign  trap  INTERRUPT  direction  overflow  resume  virtualx86  identification ]
...
0x7ffff77c2e95   <__libc_start_main+69>     je   0x7ffff77c2ea3 <__libc_start_main+83>            ←  $pc      Branch NOT taken
```

I think it'd be nice if there was some notation on which flags are in consideration for the current conditional:

```bash
Flags: [ carry  PARITY  adjust  __zero__  sign  trap  INTERRUPT  direction  overflow  resume  virtualx86  identification ]
```

Of course, how you show _how_ they interact might be a bit trickier (e.g. `G = !Z && SF == OF`) so perhaps it could go somewhere near the `Branch NOT taken`.

Now another nice feature would be an easy way to toggle flags. Maybe even a command to just _somehow_ toggle the jump (e.g. I don't care if you toggle `Z` or `SF` or `OF`, just avoid this jump!)

**Comment by hugsy** [comment]
Hi @Grazfather 

I am not sure I understand your feature request. You just want to show the reason why the branch is taken (or not)? Is that it?

Also, regarding your request on how to toggle flags, please check the command `edit-flags`.

Thanks.

**Comment by Grazfather** [comment]
Yeah like on an ISA I am new GEF might say that a branch is taken, and I can see which flags are set, but I can't tell WHICH of those flags were used to determine whether or not the branch is taken or not. in the example above, `PARITY` and `INTERRUPT` as set, but they are irrelevant. `ZERO` being highlighted (in another color) could indicate that.

**Comment by hugsy** [comment]
I understand better.

I'll think of a clean way to add that, but it should not too hard.

Cheers,

**Comment by Grazfather** [comment]
Solid! Looking forward to it.

**Comment by Grazfather** [comment]
<img width="203" alt="" src="https://cloud.githubusercontent.com/assets/497310/18237602/9136eb36-72e8-11e6-9f36-f2eab8511354.png">
Just noticed that snare/voltron already does it.

**Comment by hugsy** [comment]
It's done mate:
![](https://i.imgur.com/eDleoGV.png)

Was that what you were thinking about ?

**Comment by Grazfather** [comment]
Yeah. Looks fantastic!

**Comment by hugsy** [comment]
It's working on all archs except SPARC. I need to implement that too. I'll close the ticket when it's done then  :wink:

**Comment by Grazfather** [comment]
Solid, as long as it's in master.

**Comment by hugsy** [comment]
Yup, already there. You can already `git pull` it.

**Comment by hugsy** [comment]
SPARC is now implemented as well !! :clap: 
![](https://i.imgur.com/11gXPWC.png)

Closing the ticket! Thanks for the idea and feedbacks @Grazfather !
