### ISSUE TITLE
how do I search-pattern in a memory range?

### ISSUE THREAD

**Issue by ghost** [hugsy/gef#541]
grep xxxxx ? please give a example

thanks

**Comment by w0x12e** [comment]
why does it not list out the "Searching in a specific range" section in Command search-pattern doc panel?,I have clicked on the left side menu

**Comment by w0x12e** [comment]
![图片](https://user-images.githubusercontent.com/11622076/84333011-11916300-abc1-11ea-9532-7cc1993d9b42.png)
