### ISSUE TITLE
UnicodeEncodeError in Windows

### ISSUE THREAD

**Issue by noword** [hugsy/gef#545]
I run gdb with gef in Windows, and got this error message:
Python Exception <class 'UnicodeEncodeError'> 'charmap' codec can't encode character '\u27a4' in position 12: character maps to <undefined>:

It's same as https://github.com/hugsy/gef/issues/195, except I use a Windows

I change console charset to utf-8 with command 'chcp 65001', but still got same error.
I read some gdb source codes, and guess that  gdb read the system charset directly with the function 'host_charset'.

I have to patch gef with the code below. Use the ugly ascii chars as prompt when the console's locale is not utf-8, it's better than pop up some error message.

```
import locale
if locale.getdefaultlocale()[1].lower().startswith('utf'):
    LEFT_ARROW = " \u2190 "
    RIGHT_ARROW = " \u2192 "
    DOWN_ARROW = "\u21b3"
    HORIZONTAL_LINE = "\u2500"
    VERTICAL_LINE = "\u2502"
    CROSS = "\u2718 "
    TICK = "\u2713 "
    GEF_PROMPT = "gef\u27a4  "
    GEF_PROMPT_ON = "\001\033[1;32m\002{0:s}\001\033[0m\002".format(GEF_PROMPT)
    GEF_PROMPT_OFF = "\001\033[1;31m\002{0:s}\001\033[0m\002".format(GEF_PROMPT)
else:
    LEFT_ARROW = " < "
    RIGHT_ARROW = " > "
    DOWN_ARROW = "v"
    HORIZONTAL_LINE = "-"
    VERTICAL_LINE = "|"
    CROSS = "X "
    TICK = "O "
    GEF_PROMPT = "gef>  "
    GEF_PROMPT_ON = "\001\033[1;32m\002{0:s}\001\033[0m\002".format(GEF_PROMPT)
    GEF_PROMPT_OFF = "\001\033[1;31m\002{0:s}\001\033[0m\002".format(GEF_PROMPT)
```

**Comment by hugsy** [comment]
GEF is built around utf-8, other encodings are not supported. Your issue seems to come from the pty you use, not gdb or gef.

**Comment by hugsy** [comment]
Housekeeping.

**Comment by jgroman** [comment]
Just leaving a comment in case somebody comes here searching like I did. I had the same problem as @noword and managed to solve it by enabling Windows UTF-8 language support as described here: https://stackoverflow.com/questions/60262015/encoding-problem-atom-cant-print-utf-8-%C3%A4-%C3%B6-%C3%BC
