### ISSUE TITLE
Change color shown in built-in gdb

### ISSUE THREAD

**Issue by davidhcefx** [hugsy/gef#546]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when some of the colors (blue) are hardly visible on my terminal. (see figure)
As you can see, I have already changed the color of register name to "bold blue" according to the [doc](https://gef.readthedocs.io/en/master/commands/theme/). However, I cannot modify the color generated by native gdb.
![a](https://user-images.githubusercontent.com/23246033/85094652-e7bfe800-b221-11ea-8d76-8d058de0e459.png)

**Describe the solution you'd like**
Can you please help shed some lights on how gdb paint those colors? Since the vanilla gdb is supposed to be plain white, so something must be telling it to add those colors.

**Describe alternatives you've considered**
I have considered replacing all `"blue"` strings inside [gef.py](https://github.com/hugsy/gef/blob/dev/gef.py) with `COLOR_BLUE`. After that, I can simply set a global variable `COLOR_BLUE = "bold blue"` to change all instances. I think this might actually be a good solution for letting others to replace all color instances, rather than changing only a few colors by the `gef theme` command. (For instance, the three words in blue in the following figure aren't changeable unless doing this hack.) After all, perhaps someone also have the same problem as mine.
![c](https://user-images.githubusercontent.com/23246033/85095699-be548b80-b224-11ea-82d1-fd0dfd16cae0.png)

**Additional context**

**Comment by hugsy** [comment]
Colors are defined here: https://github.com/hugsy/gef/blob/dev/gef.py#L284

Feel free to add a color code that works for you and submit a Pull Request.

**Comment by davidhcefx** [comment]
I changed one of the color code there https://github.com/hugsy/gef/blob/dev/gef.py#L284, but the color shown by `x/10i $rip` still wasn't changed. It seems that the color code there is not related to gdb (?

**Comment by hugsy** [comment]
No it's not GEF nor GDB, it's your terminal. 
hugsy



On Thu, Jun 18, 2020 at 9:43 PM -0700, "davidhcefx" <notifications@github.com> wrote:















I changed one of the color code there https://github.com/hugsy/gef/blob/dev/gef.py#L284, but the color shown by x/10i $rip still wasn't changed. It seems that the color code there is not related to gdb (?

**Comment by Dvd848** [comment]
I believe you're looking for the following settings:
https://sourceware.org/gdb/current/onlinedocs/gdb/Output-Styling.html

Try adding the following setting to your `.gdbinit`:
```
set style address foreground cyan
```
