### ISSUE TITLE
Single-command installation

### ISSUE THREAD

**Issue by zachriggle** [hugsy/gef#547]
GEF is pretty great, but it's not always installed where I want to do debugging, and CTF environments often make the `$HOME` directory unwritable.

It turns out that you can install GEF with a single (but long) GDB command.

```
(gdb) pi import urllib.request, tempfile; gef = tempfile.NamedTemporaryFile(suffix='-gef.py'); url = urllib.request.urlopen('https://raw.githubusercontent.com/hugsy/gef/dev/gef.py'); fd=open(gef.name, 'wb+'); fd.write(url.read()); gdb.execute('source %s' % gef.name)
GEF for darwin ready, type `gef' to start, `gef config' to configure
84 commands loaded for GDB 9.2 using Python engine 3.8
[*] 4 commands could not be loaded, run `gef missing` to know why.
gef➤
```

It would be cool for you to make that information available in e.g. the README or something.

**Comment by hugsy** [comment]
One-liner added in the README and in the installation documentation.

Thanks for the suggestion!
