### ISSUE TITLE
On OS X : Python Exception <class 'OSError'> CPU type is currently not supported: i386:x86-64

### ISSUE THREAD

**Issue by SupremacistLevi** [hugsy/gef#550]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [ x ] Did you use the latest version of GEF from `master` branch?
  * [ x ] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [ x ] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System / Distribution: OS X Catalina
  * Architecture: Intel(R) Core(TM) i7-4980HQ CPU
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`: 
      9.2
      3.8.3 (default, Jul  8 2020, 14:27:55)
     [Clang 11.0.3 (clang-1103.0.32.62)]

### Step 2: Describe your problem
Hello. I am try to use gdb with gef on OS X, But When i try to excute one of Mach-O file,
It reports likes...

Reading symbols from ./test2...
Reading symbols from /Users/levi/work/test/test2.dSYM/Contents/Resources/DWARF/test2...
**_Python Exception <class 'OSError'> CPU type is currently not supported: i386:x86-64:
Python Exception <class 'OSError'> CPU type is currently not supported: i386:x86-64:_**

Could give me advices to solve this problem?

#### Steps to reproduce

  1. pull recently source of gef
  2. brew install gdb
  3. in ~/.gdbinit, source for gef.py
  4. run some test program with gdb.

**Comment by hugsy** [comment]
GEF is for Linux, not OSX
