### ISSUE TITLE
Various IDA improvements

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#552]
* Aliases (we shouldn't have to type `ida MakeName`. `ida N` (like the hotkey) would be nice
* Support for both > 7 and < 7 API
* Resolve symbols (e.g. allow naming something, and then using that name in Gef)
   ```bash
   gef> ida MakeName main mymain
   gef> ida MakeComm mymain "this is main"
   ^ This will fail because we can't resolve `mymain` in gdb. Maybe try to resolve in ida land?
   ```
* Reload script functionality?

**Comment by hugsy** [comment]
As much as I love having this feature, I hate IDA backward compat policy, forcing a bunch of `if` everywhere, that's why I'm more and more turning to binja now. So it's unlikely I'll work on it, so do you wanna take the lead on that @Grazfather ?

**Comment by Grazfather** [comment]
Yeah, I did some of this in #553. I think in a year or so we can drop support for the old API, as well, which will make things nicer.

**Comment by hugsy** [comment]
A friend threw an idea at me about this: if the decompiler is available, use it in the source pane. I'll work on that for binja, never played with the decompiler API on IDA but I assume it 's feasible as other projects (ret-sync for instance) already do that.
