### ISSUE TITLE
hexdump address parse error

### ISSUE THREAD

**Issue by nkbai** [hugsy/gef#558]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [ x] Did you use the latest version of GEF from `master` branch?
  * [ x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x ] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System / Distribution: Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
  * Architecture: arm32
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`: 

GNU gdb (GDB) 8.2 && python 3.5 

### Step 2: Describe your problem
```
gef➤  help hexdump
Display SIZE lines of hexdump from the memory location pointed by ADDRESS.
Syntax: hexdump [qword|dword|word|byte] [ADDRESS] [[L][SIZE]] [REVERSE]
Example: hexdump byte $rsp L16 REVERSE
gef➤  hexdump 0x412050
0x00412110 <tasks+0100>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x00412120 <tasks+0110>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x00412130 <tasks+0120>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x00412140 <tasks+0130>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
gef➤  hexdump 0x412110
0x00412210 <tasks+0200>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x00412220 <tasks+0210>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x00412230 <tasks+0220>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x00412240 <tasks+0230>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
gef➤  hexdump tasks
[!] Command 'hexdump' failed to execute properly, reason: 'tasks' has unknown type; cast it to its declared type
gef➤  hexdump 0x412010
0x00412190 <tasks+0180>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x004121a0 <tasks+0190>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x004121b0 <tasks+01a0>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x004121c0 <tasks+01b0>    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
gef➤  p tasks
'tasks' has unknown type; cast it to its declared type
gef➤  p &tasks
$1 = (<data variable, no debug info> *) 0x412010 <tasks>
```
#### Steps to reproduce

the address  following `hexdump`  seems parsed error

**Comment by Grazfather** [comment]
What commit are you on? I cannot reproduce.

**Comment by nkbai** [comment]
gef.py is the latest version: 87bc36902c619f8fad81c11b0128748b  .gdbinit-gef.py
gdb use gdb-8.2.tar.gz from gnu ftp :0783c6d86775c5aff06cccc8a3d7cad8  gdb-8.2.tar.gz
gdb build with:  ./configure  --with-python='/usr/bin/python3'

**Comment by hugsy** [comment]
Cannot reproduce either.

Also copy/paste from tty directly: `hexdump 0x412010` returns `[!] Incomplete command`

**Comment by nkbai** [comment]
it's ok for gdb-7.12 ,but not correct for gdb 8.2

**Comment by hugsy** [comment]
After reading, the syntax is incorrect: gef evaluates the address parameter the same way as gdb (see https://github.com/hugsy/gef/blob/dev/gef.py#L8214). Therefore, `hexdump byte tasks` would dereference `tasks` and print the content at that address. The proper syntax is `hexdump byte &tasks`. 

I've tested it and it works as expected even on gdb-9.1.
![image](https://user-images.githubusercontent.com/590234/90160636-e654fc80-dd46-11ea-9b07-dbdeae7cd137.png)

**Comment by hugsy** [comment]
Housekeeping.

**Comment by realyukii** [comment]
I get an error when using hexdump this way:
```
hexdump byte *($rsp+8)
[!] Command 'hexdump byte' failed to execute properly, reason: Attempt to dereference a generic pointer.
```
I tried to access it like this instruction does: `movq	8(%rsi), %rsi`

what is the correct way?
