### ISSUE TITLE
Heap analiser not showing after attaching to new process

### ISSUE THREAD

**Issue by DMaxter** [hugsy/gef#559]
Your issue will be closed unless you confirm the following:
  * [X] Did you use the latest version of GEF from `master` branch?
  * [X] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [X] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System / Distribution: Linux 5.8.1 / Arch Linux
  * Architecture: x86_64
  * GDB version : 9.2 / Python 3.8.5 / GCC 10.1.0

### Step 2: Describe your problem

When analysing the heap of a program, and then attaching to a new program,
when trying to analyse the chunks/bins I get an exception

#### Steps to reproduce

  1. Run gdb on a program (`gdb -p PID`)
  2. Analyse the heap (`heap bins` is fine)
  3. Attach to a new program / instance of the same program (`att PID`)
  4. Analyse the heap of the new program being debugged (`heap bins`)

#### Observed Results

  * What happened? 

```
gef➤  heap bins
──────────────────────────────────────── Tcachebins for arena 0x7f24bfb1ec40 ────────────────────────────────────────
───────────────────────────────────────── Fastbins for arena 0x7f24bfb1ec40 ─────────────────────────────────────────
Fastbins[idx=0, size=0x20] [!] Command 'heap bins fast' failed to execute properly, reason: 'NoneType' object has no attribute 'cast'
────────────────────────────────────── Unsorted Bin for arena '*0x7f24bfb1ec40' ──────────────────────────────────────
[!] Command 'heap bins unsorted' failed to execute properly, reason: 'NoneType' object has no attribute 'cast'
─────────────────────────────────────── Small Bins for arena '*0x7f24bfb1ec40' ───────────────────────────────────────
[!] Command 'heap bins small' failed to execute properly, reason: 'NoneType' object has no attribute 'cast'
─────────────────────────────────────── Large Bins for arena '*0x7f24bfb1ec40' ───────────────────────────────────────
[!] Command 'heap bins large' failed to execute properly, reason: 'NoneType' object has no attribute 'cast'
```

#### Expected results

  * What did you expect to happen?

Show the heap information (chunks in bins, chunks if ran with `heap chunks`)

#### Traces

Since the output is pretty big and it is the same stack trace in all bins, I only provide the stack trace for Unsorted Bin

```
──────────────────────────── Unsorted Bin for arena '*0x7f24bfb1ec40' ─────────────────────────────

─────────────────────────────── Exception raised ───────────────────────────────
AttributeError: 'NoneType' object has no attribute 'cast'
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/usr/share/gef/gef.py", line 690, in get_size_t_array()
    →     return dereference(addr).cast(size_t_array)
↳ File "/usr/share/gef/gef.py", line 669, in bins()
    →     return self.get_size_t_array(self.bins_addr, self.num_bins)
↳ File "/usr/share/gef/gef.py", line 693, in __getitem__()
    →     return getattr(self, item)
↳ File "/usr/share/gef/gef.py", line 717, in __getattr__()
    →     return self.__arena[item]
↳ File "/usr/share/gef/gef.py", line 742, in bin()
    →     fd = int(self.bins[idx])
↳ File "/usr/share/gef/gef.py", line 6367, in pprint_bin()
    →     fw, bk = arena.bin(index)
↳ File "/usr/share/gef/gef.py", line 6542, in do_invoke()
    →     nb_chunk = GlibcHeapBinsCommand.pprint_bin(arena_addr, 0, "unsorted_")
↳ File "/usr/share/gef/gef.py", line 2458, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/usr/share/gef/gef.py", line 244, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/usr/share/gef/gef.py", line 3857, in invoke()
    →     bufferize(self.do_invoke)(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
  253  heap bins
  254  att 66976
  255  att 67122
  256  heap bins
  257  heap bins
  258  att 67906
  259  heap bins
  260  heap bin tcache
  261  gef config gef.debug 1
  262  heap bins
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 9.2
* Python: 3.8.5 - final
* OS: Linux - 5.8.1-arch1-1 (x86_64)

LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
────────────────────────────────────────────────────────────────────────────────
```

**NOTE:** This error occurs even on the `dev` branch

**Comment by hugsy** [comment]
That's not a bug from GEF but a feature from GDB: `attach` doesn't for symbol tables reloading. You need to do it manually using `file` after (re-)attaching.

**Comment by DMaxter** [comment]
That's to load the symbols, or not?

**Comment by hugsy** [comment]
From the help:

```
gef ➤  help attach
Attach to a process or file outside of GDB.
This command attaches to another target, of the same type as your last
"target" command ("info files" will show your target stack).
The command may take as argument a process id or a device file.
For a process id, you must have permission to send the process a signal,
and it must have the same effective uid as the debugger.
When using "attach" with a process id, the debugger finds the
program running in the process, looking first in the current working
directory, or (if not found there) using the source file search path
(see the "directory" command).  You can also use the "file" command
to specify the program, and to load its symbol table.
```

```
gef ➤  help file
Use FILE as program to be debugged.
It is read for its symbols, for getting the contents of pure memory,
and it is the program executed when you use the `run' command.
If FILE cannot be found as specified, your execution directory path
($PATH) is searched for a command of that name.
No arg means to have no executable file and no symbols.
```

Just try running `file` after you ran `attach`, `heap bins` along with all the other functions will work.

**Comment by DMaxter** [comment]
It doesn't work, the behaviour is the same.
It gets the memory, the registers, the flags, the code, but not the heap

**Comment by hugsy** [comment]
@DMaxter I've re-tested it on Ubuntu 18 & 20: running `file` after attaching fixes the issue. If it doesn't for you, provide a complete (binary or C source + compilation flags) test case scenario so we can try to reproduce.

**Comment by DMaxter** [comment]
Turns out it is due to libc version. If I use my current libc (2.31) everything is fine, but if I patch the binary to use libc-2.27 (I'm using Ubuntu `GLIBC 2.27-3ubuntu1`) even the simplest program can't be analysed.

Source:
```C
#include <stdio.h>
#include <stdlib.h>

int main() {
    char * a = malloc(100);

    free(a);

    getchar();

    return 0;
}
```

Compilation: `gcc -no-pie file` (I only tested with `-no-pie` but it may not influence the observed behaviour)

**Comment by hugsy** [comment]
Then you must missing the `-dev` package for that libc, which prevent gdb from finding the `main_arena`.
I've just tested your C code on a libc 2.32 (2.23-0ubuntu11.2 to be precise), works like a charm.

**Comment by DMaxter** [comment]
From what I'm seeing, the address that is passed to `dereference` is not updated, i.e.
```$ gdb -p PID1
> heap arenas
0x7fb607ea8ca0
0x7fb607ea8ca8                                                                                                               
0x7fb607ea94b0                                                   
0x7fb607ea94b8                                                                                                              
0x7fb607ea94b0 ```

Those are some addresses that are given to `dereference` when the command runs

```> att PID2
> file bin
> heap arenas
0x7fb607ea8ca0
EXCEPTION ERROR
```

This error is due to the addresses of `libc`, that are used by `gef` are not updating, after the `attach`, raising a `gdb.MemoryError`. The address of `read` for example is `0x7fdc41eaf070`, as you can see, due to ASLR, is different from `0x7fb607ea8ca0` (not read, but the MSBs are different).

```> file libc-2.27.so
> heap arenas
0x7fb607ea8ca0
```

`file` does not change anything, I tried with and without it, always the same

**Comment by hugsy** [comment]
It may be, but as long as we can't reproduce it (and I still can't, `attach` works just fine) I don't see how we can help.

**Comment by DMaxter** [comment]
I found the issue:
When `heap` commands run, a the class `GlibcArena` is created and an address/symbol is given: `__gef_default_main_arena__`, which by default is `main_arena`.
On my current GLibc version (2.32 now), this symbol is always equal to `main_arena` between `heap` command runs, which I think is perfectly fine (and that's why the error doesn't occur).
On version 2.27, the symbol is initially `main_arena` and if I run `heap arenas` (for example), `__gef_default_main_arena__` becomes `*0xdeadbeef` (the address of main_arena, to be dereferenced).
When I attach a new program, since the address is not updated, it tries to access a memory location that does not belong to this program.

I was able to patch this by commenting the lines:
https://github.com/hugsy/gef/blob/d4925ebcb700d47ee9c1866c09cde1f1f41c1899/gef.py#L6350

https://github.com/hugsy/gef/blob/d4925ebcb700d47ee9c1866c09cde1f1f41c1899/gef.py#L607

Since I don't know the implications of changing this lines, I did not make a PR

**Comment by hugsy** [comment]
That's very interesting and helpful. What surprises me is that I don't face those issues running on ubuntu 20.04 (with libc 2.31) and ubuntu 18.04 (with 2.27).

Based on your description, I believe I have found a patch that may never harm. Can you please try it and let me know this one line patch as follow:

In `gef.py`, edit the function `reset_all_caches()` and simply add:
```python
def reset_all_caches():
    [...]   
    __gef_default_main_arena__  = "main_arena"
    return
```

This function is invoked when a new `objfile` is loaded (and therefore when attach is called), and will restore `__gef_default_main_arena__`  to its original default value.

Please let me know if it worked, I'll patch it upstream. Thanks for investigating.

**Comment by DMaxter** [comment]
You almost got it

```Python
def reset_all_caches():
    [...]   
    global __gef_default_main_arena__ 
    __gef_default_main_arena__  = "main_arena"
    return
```
Forgot to say it was a global variable, but it works like a charm
Thanks

**Comment by Grazfather** [comment]
Good debugging!
