### ISSUE TITLE
Feature: view stack with specified count & offset

### ISSUE THREAD

**Issue by samvdkris** [hugsy/gef#562]
I just switched from pwndbg to GEF and I am really liking it so far, but one feature I really miss is the ability to view more than just a few lines of the stack (without changing the number of lines in the config). pwndbg has, in addition to the context view, also a `stack` command (similarly to GEF's `ctx stack`), which also allows you to pass a count and an offset.

I couldn't find anything in GEF's docs on a command like this. The closest thing to this I've seen would be changing `context.nb_lines_stack`, running a `ctx stack` and changing `context.nb_lines_stack` back again, but that would be kind of a pain.

Perhaps this is already a thing and I missed it (or it's not mentioned in the documentation), but if not it would be awesome if someone with more experience than me could add this functionality.

**Comment by DMaxter** [comment]
You can use `telescope <number of linda>` if I'm not mistaken

**Comment by samvdkris** [comment]
Awesome, that was exactly what I was looking for! Thank you for the help and sorry for the issue on something that already exists :)
