### ISSUE TITLE
GEF not recognized in Cygwin Windows GDB Session

### ISSUE THREAD

**Issue by H0r53** [hugsy/gef#563]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

Windows 10 Enterprise / 10.0.17763
AMD64
GNU GDB (Cygwin 8.3.1-1)
**$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`:** 
(Cygwin 8.3.1-1) 8.3.1
3.6.10 (default, Jun 8 2020, 19:37:31)
[GCC 9.3.0]

I am attempting to setup a GDB/GEF/Python interface within a Windows environment. I understand GEF has a GDB requirement of >= 7.7, so Cygwin's GDB seems like my best bet. I'm using the latest stable version of Cygwin GDB. I've setup GEF multiple times on Linux machines and I never had issues. Basically, all I've had to do in the past was **source** the gef.py file and I'm good to go - GDB launches in GEF mode. However, in my Windows environment I'm finding that after sourcing gef.py nothing happens. There is no error thrown, the session just remains in default GDB mode. The basic steps to reproduce are:

1. Install Cygwin and GDB packages on a Windows 10 environment
2. Download the latest GEF source
3. Attempt to source gef.py within a gdb session (or in .gdbinit)
4. GEF mode is not initiated

The GEF documentation suggests that GEF is OS agnostic. Therefore, I've been under the impression that GEF should work on Windows provided GDB requirements are met. Does GEF indeed have Windows support? Is there an alternative to Cygwin? I tried MINGW but it only supports GDB up to 7.6 or so. I think GEF is a wonderful GDB extension and I need to analyze some Windows binaries dynamically, so if I could get this going I would be extremely happy. Thank you.

**Comment by hugsy** [comment]
Closing this issue as we are aware of this, and it's being worked on.
For details add comments to https://github.com/hugsy/gef/pull/536

Thanks,
