### ISSUE TITLE
Add `nextret` command

### ISSUE THREAD

**Issue by bad5ect0r** [hugsy/gef#564]
**Is your feature request related to a problem? Please describe.**
I would like to continue execution till it hits the next return instruction when developing ROP chains.

**Describe the solution you'd like**
A `nextret` instruction. Similar to what is offered in pwndbg.

**Describe alternatives you've considered**
Pwndbg offers this. I couldn't find a way to do this using gef and I would prefer to keep using gef.

**Comment by hugsy** [comment]
You might want to use this command: [`pt`](https://github.com/hugsy/gef-extras/blob/master/scripts/windbg.py#L109)
