### ISSUE TITLE
Interface "flickers", "flashes", goes black for a short while when refreshing

### ISSUE THREAD

**Issue by PaperTsar** [hugsy/gef#565]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

  * Operating System / Distribution: Parrot OS 4.10
  * Architecture: x64
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`: GDB 9.2, Python 3.8
  * I use tmux, i3 with compton, urxvt and zsh.

### Step 2: Describe your problem
Whenever the interface refreshes it first turns black for ~30ms which is definitely noticeable, makes it appear as if the screen is flashing, flickering. Really annoying since the interface flickers every time I enter step or stepi. 

#### Steps to reproduce

  1. Simply opening up any compiled binary.
  2. Type start.
  3. Type `stepi` and enter
  4. See as the interface flickers as it's refreshing

**Comment by Grazfather** [comment]
What branch/commit are you on?

There's an option to not clear the context every step (instead scrolling) which can make this better.

There might be a regression in the draw speed.

**Comment by PaperTsar** [comment]
> What branch/commit are you on?
> 
> There's an option to not clear the context every step (instead scrolling) which can make this better.
> 
> There might be a regression in the draw speed.

I used the latest release version of GEF. Installed with the SH script.

**Comment by PaperTsar** [comment]
@Grazfather `gef config context.clear_screen 0` seems to have fixed the problem.

**Comment by PaperTsar** [comment]
Could the issue be that collecting the information required to update the interface takes time and the screen is cleared before it's been collected? In this case, double buffering (if curses supports it) and clearing right before drawing would solve the issue.

**Comment by Grazfather** [comment]
Double buffering doesn't make sense since there aren't frames: There's a full redraw every time there's a new prompt.

It does look like we clear the screen before we draw. I think that this is probably necessary, because we can't guarantee that everything 'drawn' is actually written to the buffer (some is draw directly out).

If we could, then we could move the clear to later.

If you'd like to play with it, look at `do_invoke` in `ContextCommand` and try moving the `clear_screen` to after the `for section...`. Note that the buffer is flushed automatically when `do_invoke` returns.

**Comment by hugsy** [comment]
I've experienced this issue several times, especially on devices with low framebuffering rates (VMs with no graphic accel, embedded devices, etc.) To the best I could research at that time, this is not a GEF specific issue but a pty's. If it's the same bug, I could reproduce easily outside of gef just by clearing the screen.

@PaperTsar if you're in a VM, I'd suggest allocating some 2d resource which could fix this issue.

**Comment by Grazfather** [comment]
Yeah, your TTY and terminal absolutely make a difference, but that doesn't mean that we aren't clearing and then waiting to collect all the data. If we are able to move the clear until after running all the context sub funcs then we basically can make the problem _only_ the TTY and terminal. Right now it's those + all the work of querying regs, code, etc + building the output.

**Comment by PaperTsar** [comment]
@hugsy You are correct, I did ran gef in a VM. I also tried SSH-ing into the vm from the host and running gef from there which did not help.

**Comment by hugsy** [comment]
@PaperTsar if you manage to guide us to build a "good" reproduction environment, let us know. In my experience, just allocating more resources to the VM fixed the issue.

**Comment by PaperTsar** [comment]
The following reproduces it:
- Download the [official Parrot OS Ova for Virtualbox](https://download.parrot.sh/parrot/iso/4.10/Parrot-security-4.10_virtual.ova)
- Allocate 8G ram, 4 cpus, 256Mb of vram via `VBoxManage modifyvm "Name of VM" --vram 256`
- Install Gef
- Type `gdb some binary`, type start, type si, see it flicker

Would the following work? In ContextCommand each context_<...> (i.e context_regs, context_stack etc.) would instead of using gef_print(line) just do self.some_buffer.append(line) and then ContextCommand.do_invoke clears the screen and draws all the lines at once.

**Comment by Grazfather** [comment]
`get_print` already does buffering.

I already suggested that you move the clearing. Please try that.

**Comment by Grazfather** [comment]
```diff
diff --git a/gef.py b/gef.py
index 9352d8c..ae0a138 100644
--- a/gef.py
+++ b/gef.py
@@ -7491,9 +7491,6 @@ class ContextCommand(GenericCommand):
         if redirect and os.access(redirect, os.W_OK):
             enable_redirect_output(to_file=redirect)

-        if self.get_setting("clear_screen") and len(argv) == 0:
-            clear_screen(redirect)
-
         for section in current_layout:
             if section[0] == "-":
                 continue
@@ -7504,9 +7501,11 @@ class ContextCommand(GenericCommand):
                 # a MemoryError will happen when $pc is corrupted (invalid address)
                 err(str(e))

-
         self.context_title("")

+        if self.get_setting("clear_screen") and len(argv) == 0:
+            clear_screen(redirect)
+
         if redirect and os.access(redirect, os.W_OK):
             disable_redirect_output()
         return
```

**Comment by Grazfather** [comment]
You can also easily time how much time is spent in the sub context functions. For me it's only about 15ms

**Comment by kiprasmel** [comment]
@Grazfather 

I have the same issue and your patch https://github.com/hugsy/gef/issues/565#issuecomment-699071233 does indeed help! Instead of straight jumping, there's now a notion of scrolling. The screen still flickers and it's annoying, but now less.

**Comment by Grazfather** [comment]
I forgot about this. Pushing a PR
