### ISSUE TITLE
gef config not shown in gef help

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#57]
Others might be missing as well.

I might fix this tonight.

**Comment by hugsy** [comment]
`gef` is a GDB command. To see the sub-commands, just use the GDB `help` command:

```
gef➤  help gef
GEF main command: start with `gef help` 

List of gef subcommands:

gef config -- GEF configuration sub-command
gef help -- GEF help sub-command
gef missing -- GEF missing sub-command
gef restore -- GEF restore sub-command
gef save -- GEF save sub-command
```

**Comment by Grazfather** [comment]
Ah that's confusing. There's `gef help` and `help gef`.  This bug was alluding that `config` isn't mentioned in the first.

**Comment by hugsy** [comment]
Yes because it is only listing the commands provided by `gef`. If I was also listing the sub-commands it would be too long and confusing.

**Comment by Grazfather** [comment]
Fair enough. Sorry about that.

**Comment by hugsy** [comment]
:smile: 

Thanks for your feedbacks, always appreciated.
