### ISSUE TITLE
Support Cortex-M CPU

### ISSUE THREAD

**Issue by Leo1003** [hugsy/gef#571]
**Is your feature request related to a problem? Please describe.**
Since Cortex-M CPU doesn't have `$cpsr` register, instead, they use `$xPSR` as status register. Hence, the `ctx code` and `ctx args` commands would fail with the following message:
```text
─────────────────────────────── Exception raised ───────────────────────────────
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/leo/.gdbinit-gef.py", line 1667, in is_thumb()
    →     return is_alive() and get_register(self.flag_register) & (1<<5)
↳ File "/home/leo/.gdbinit-gef.py", line 1672, in pc()
    →     if self.is_thumb():
↳ File "/home/leo/.gdbinit-gef.py", line 7492, in context_code()
    →     pc = current_arch.pc
↳ File "/home/leo/.gdbinit-gef.py", line 7367, in do_invoke()
    →     self.layout_mapping[section]()
↳ File "/home/leo/.gdbinit-gef.py", line 2458, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/leo/.gdbinit-gef.py", line 248, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "/home/leo/.gdbinit-gef.py", line 3857, in invoke()
    →     bufferize(self.do_invoke)(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
  249  quit
  250  quit
  251  i r $xPSR
  252  q
  253  gef config gef.debug 1
  254  ctx code
  255  ctx args
  256  q
  257  gef config gef.debug 1
  258  ctx
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 9.2
* Python: 3.8.5 - final
* OS: Linux - 5.8.12-arch1-1 (x86_64)

LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
────────────────────────────────────────────────────────────────────────────────
```
Except this, the flag register in `ctx regs` is also missing due to the same issue.

**Describe the solution you'd like**
Detecting which flag register should we use, `$cpsr` or `$xPSR`(case sensitive), and their corresponding flags table.

**Describe alternatives you've considered**
Currently no.

**Additional context**
Some useful references:
- [Cortex-M3 Technical Reference Manual](https://developer.arm.com/documentation/ddi0337/e/programmer-s-model/registers/special-purpose-program-status-registers--xpsr-)
- [Keil CMSIS-Core (Cortex-M)](https://www.keil.com/pack/doc/cmsis/Core/html/group__Core__Register__gr.html#ga732e08184154f44a617963cc65ff95bd)

**Comment by hugsy** [comment]
Is there a qemu image somewhere with a ready to use Debian/Ubuntu environment for Cortex-M0 ?

**Comment by Grazfather** [comment]
M-series cortex don't support linux, so he must be using openocp or blackmagic probe.

@dawidcrivelli, @Leo1003 , could you please clarify what is acting as the GDB server in your setup?

**Comment by Leo1003** [comment]
> M-series cortex don't support linux, so he must be using openocp or blackmagic probe.
> 
> @dawidcrivelli, @Leo1003 , could you please clarify what is acting as the GDB server in your setup?

I use openocd as GDB server which attached to a STM32 L476 board.

> Is there a qemu image somewhere with a ready to use Debian/Ubuntu environment for Cortex-M0 ?

As far as I know, openocd currently only support Cortex-M3 & M4.

**Comment by Grazfather** [comment]
Thank you, Leo.

Looks like xPSR is a legit name, I guess that makes sense, since CPSR means 'current program status register', and M-series don't have user space and the normal concept of a process.

If I recall correctly, the BMP might name the register xpsr or XPSR. We should verify this.

I agree with @hugsy that we should solve this by making a new Architecture, maybe mARM or similar, which can inherit most, but set the registers differently.

If the BMP names the xpsr differently, well that sucks! We'll have to hack something in, like supporting aliases.

**Comment by mcgdb** [comment]
Hi,
I'd like to pick this up...Is there there any more context you can add to the idea of creating/inheriting from another class?
```I agree with @hugsy that we should solve this by making a new Architecture, maybe mARM or similar, which can inherit most, but set the registers differently.```

If you can give me a little direction, I think I can take it from there and get a PR submitted.
I'm sort of back in the same boat as before with #320....But, I'm a lot better at this now, so I'm glad to take a crack at it.

Thanks!

**Comment by hugsy** [comment]
> I'd like to pick this up...Is there there any more context you can add to the idea of creating/inheriting from another class? 

See https://github.com/hugsy/gef-extras/blob/main/archs/arm-cortex-m.py
