### ISSUE TITLE
Minor formatting issue with stack

### ISSUE THREAD

**Issue by adzienis** [hugsy/gef#572]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [ X] Did you use the latest version of GEF from `master` branch?
  * [ X] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [ X] Did you check [issues](https://github.com/hugsy/gef/issues) (including the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

  * Operating System / Distribution: Arch Linux
  * Architecture: x86
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`:  9.2, 3.8.5

### Step 2: Describe your problem
Honestly a tiny formatting issue that's just bugged me. This is basically a vanilla gef with `show_stack_raw` set to true. This is before with the latest commit, 9ac0173: 

![gef_before](https://user-images.githubusercontent.com/7027362/95150343-fccf7100-0755-11eb-8237-c21e574bc158.png)

Found the issue where there's a lack of padding in the "hexdump" function:

![gef_line](https://user-images.githubusercontent.com/7027362/95150507-4cae3800-0756-11eb-91b6-7da67fbc4b10.png)

Just need to change `{sym}` to `{sym:15}`, and everything looks fine:

![gef_after](https://user-images.githubusercontent.com/7027362/95150626-98f97800-0756-11eb-8781-2680042ba70c.png)

This is a pretty minor issue haha, so it'd be cool if it could get piggy backed to a commit, unless this is somehow expected.

#### Steps to reproduce

  1. Set `context.show_stack_raw` to `True`

#### Minimalist test case

Adding a test case goes a long way to help reproduce the issue. This can be done by either attaching a test binary, or providing a test case as a source code, **with** its compilation environment and options.
I can attach a binary if it really is necessary.

#### Observed Results

  * What happened?  This could be a description, log output, etc.
The output is not aligned.

#### Expected results

  * What did you expect to happen?
Aligned text.

#### Traces

Feel free to include in this section screenshots or stack traces.

If you enable `gef.debug` (`gef config gef.debug 1`), gef will display a
full stack trace when an exception occurs. It is a good idea to copy/paste it here
(and/or add a screen shot) as it contains useful information that will make it easier
to reproduce. 

**The more info is provided, the more likely your issue will be confirmed and handled**

**Comment by Grazfather** [comment]
The problem is that this only works for symbols that are a certain length. If `my_stack` had a longer name, then the stuff below would be indented, but not enough.

It would be better if we instead calculated the width of the widest symbol in the range, and then pad every line to that width.

**Comment by adzienis** [comment]
Yeah sure, I wrote a fix for that:

![gef_fix](https://user-images.githubusercontent.com/7027362/95238082-02b96680-07d7-11eb-8dc7-fbe921386a28.png)


I was also wondering too where gef formats the output for dereferencing an address:
![gef_2](https://user-images.githubusercontent.com/7027362/95237830-b110dc00-07d6-11eb-93ae-f06fd2410fa3.png)

I tried looking around in the codebase but couldn't find where it hooks to the gdb call or completely supplants it; since it works correctly here but not in `hexdump`. The alignment here is still off, but not as jagged as the other. 
Thanks for responding.

**Comment by daniellimws** [comment]
@adzienis Do you want to make a PR for your fix?

The alignment by `x` is done by GDB. It works even when gef is not loaded. But it is quite weird. When I ran `x/30gx` on my Ubuntu VM, it doesn't align nicely as seen in your image, but somehow it does align nicely on MacOS. I tried it on gdb 9.2 on both machines and they behaved differently.

**Comment by adzienis** [comment]
Yeah sure, I'll put one up soon. The GDB alignment is interesting.
