### ISSUE TITLE
call argument definition from libc

### ISSUE THREAD

**Issue by theguly** [hugsy/gef#576]
hello, i'm not a good coder and i feel not that easy to always remember args to every call while debugging on gdb. got tired of running man i thought it could be useful to have a better definition for call arguments, when possible.

currently gef shows a (pun not intended) too guessed arguments guessed context panel. for example, for a read call that should accept three arguments:
![Screenshot 2020-11-10 at 22 32 16](https://user-images.githubusercontent.com/1745802/98736103-aed90900-23a4-11eb-8c8d-f1ae41e772f8.png)

i wrote a quick hack to achieve my goal, tested and working on x86-32 and x86-64 basic samples, that adds a def type after register/position and value:
![Screenshot 2020-11-10 at 22 29 35](https://user-images.githubusercontent.com/1745802/98736838-a7662f80-23a5-11eb-89b4-7f732713d64b.png)

it works by checking against a dict loaded at runtime, a dict that holds libc functions and arguments, current call and print to output just known values.

i expect this feature would be configurable by a context settings for a couple of reasons.

if you think it could be interesting or useful i'll check my code against your standards (should be not so far) to send a PR.

**Comment by Grazfather** [comment]
pwndbg has a similar feature, and I have been interested in adding it to gef. Feel free to push a PR so that we can look.

The main concerns, I think, are how we make sure the function call is correct (how do you know it's glibc read?) and where we store this data.

**Comment by daniellimws** [comment]
Shall we store the function call data in gef-extras? Like the syscall data https://github.com/hugsy/gef-extras/tree/master/syscall-tables that I added last time.

**Comment by theguly** [comment]
well, i'm also far from being a reverse expert but i think you cannot be 100% sure that a function is from glibc.
i'm not speaking about "tampered" binaries, because only god knows what could be there, but for example static ones could be problematic too.

to keep it simple, during my tests i made the assumpion that _read@plt_ is from libc, and an eventual _read_ is not. i'll think more about this, i'm of course open to suggestion

i think data cannot be kept in main gef py, it would be a huge blob. i'd place in gef-extras like the syscall module to keep the env as clean as possible.

**Comment by theguly** [comment]
sent PR right now #577
some questions:
1) i used json and not namedtuple like syscall-args does because i'm used with json, of course i'm open to namedtuple if there is a reason
2) i placed two config argument in context, because this PR changes context. i'm not 100% happy, feel free to point me to the right place
3) maybe lazyness won, but i did not found a better place to load dictionary than new_objfile_handler(). that function runs more than once, it's not a big issue but it's not so clean. again, feel free to hit me and point me to a better place

i'm also attaching json dictionaries here
[x86_32.json.gz](https://github.com/hugsy/gef/files/5530140/x86_32.json.gz)
[x86_64.json.gz](https://github.com/hugsy/gef/files/5530141/x86_64.json.gz)

thanks

**Comment by Grazfather** [comment]
Done! Thanks a lot for your contribution!
