### ISSUE TITLE
RFI: using pattern create & pattern search with convenience variables.

### ISSUE THREAD

**Issue by rileyrg** [hugsy/gef#580]
Complete noob so please grant me some slack. I tried googling and couldn't find anything. 

The docs show how to create a pattern eg

`pattern create 128`

All good and I see something like:-

> [+] Generating a pattern of 128 bytes
> aaaabaaacaaadaaaeaaafaaagaaahaaaiaaajaaakaaalaaamaaanaaaoaaapaaaqaaaraaasaaataaauaaavaaawaaaxaaayaaazaabbaabcaabdaabeaabfaabgaab
> [+] Saved as '$_gef0'
> 

How do I use this "save"? My understanding is this is a convenience variable. But I can't see how to use this in a

`pattern search`

statement. My naive assumption of 

`pattern search $_gef0` 

doesn't work.

`print $_gef0`

does work.

Thanks and apologies in advance if this IS in the docs and I was too blind to see it!

**Comment by Grazfather** [comment]
GEF issues aren't the spot for help using GEF. irc/discord.
