### ISSUE TITLE
Restore CI to a descently usable state

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#586]
CI has become meaningless. Re-work on it:

 - [x] Get rid of Circle-CI
 - [x] Use Github Actions as main CI
 - [ ] ~~If Travis-CI non-x86 arch support finally works, use it. Otherwise~~ trash Travis.

**Comment by hugsy** [comment]
cc #472

**Comment by hugsy** [comment]
GH working fine from f97c80d

**Comment by hugsy** [comment]
__Note__: after 885c750  both ARM64 and PPC64LE support work on Travis-CI. They only fail due to exceeding the 10min window allocated for tests. What's killing it is the compile time of keystone/capstone/unicorn so we must study several options:

 - add some `if`/`else` in `tests/runtests.py` to *not* run the commands that use those packages on those archs
 - OR create some pre-compiled packages ready to use

Any other idea is welcome.

**Comment by Grazfather** [comment]
Can't we have them run AARCH64/PPC64LE versions of docker with the 'trinity' precompiled?

**Comment by hugsy** [comment]
I was looking for such thing but all I found was [this](https://docs.travis-ci.com/user/docker/) and not sure it applies for non-x86. And it'll be a pain to set up

**Comment by Grazfather** [comment]
Why would it be a pain?

Just try to maintain a base docker build for GEF for a few architectures.

That said, keystone & friends SHOULD be (host) architecture agnostic. It's not up to us to test how it runs on other systems. We can integration test it on x86 or x86_64 and for the other architectures test more basic functionality.

**Comment by hugsy** [comment]
> Just try to maintain a base docker build for GEF for a few architectures.
> 

That's the point, not sure how to handle this in a simple fashion. Any idea?

> That said, keystone & friends SHOULD be (host) architecture agnostic. It's not up to us to test how it runs on other systems. We can integration test it on x86 or x86_64 and for the other architectures test more basic functionality.

Are you suggesting to remove the test cases for the trinity?

**Comment by hugsy** [comment]
GH Actions is operational, might want to dig into https://github.com/multiarch/qemu-user-static for non x86 CI testing in GH Actions in the future.

Closing
