### ISSUE TITLE
Allow configuring color for past source context

### ISSUE THREAD

**Issue by mvastola** [hugsy/gef#599]
**Is your feature request related to a problem? Please describe.**
Arguably. I just started trying out `gef` and I like it. The only thing that's driving me crazy is the source code context color. It's hard coded to simply be gray, and when I debug I keep getting lost because my eyes just ignore the greyed out stuff.  I'd like to make it the same color as the following source lines. I can obviously eventually get used to it, but for now it's really disorienting coming from plain gdb . 

**Describe the solution you'd like**
A configuration option to specify the color the color of source code earlier on in your current function.

**Describe alternatives you've considered**
Considered monkeypatching the method in my `.gdbinit`, but that's bad for maintainability and too much work.

**Additional context**
Code at issue is right [here](https://github.com/hugsy/gef/blob/fc025c908cf345a80934ecc338b1143b370f8e7f/gef.py#L7698).

**Comment by Grazfather** [comment]
This is fair :) We can probably make this configurable.

**Comment by mvastola** [comment]
Thanks!!
