### ISSUE TITLE
 debug stripped file,"Cannot find bounds of current function"

### ISSUE THREAD

**Issue by qiannianshuangxue** [hugsy/gef#600]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [ √] Did you use the latest version of GEF from `master` branch?
  * [√] ] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [ √]] Did you check [issues](https://github.com/hugsy/gef/issues) (including the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

  * kylin OS
  * aarch64
  * EulerOS 8.3.1-11.ky10
3.7.4 (default, Oct 15 2020, 15:45:55) 
[GCC 7.3.0]

#### Steps to reproduce

  1.the gef can not debug stripped file very good, if i use n or e it report "Cannot find bounds of current function"  .

#### Minimalist test case

test code as follow
```c
// compile with gcc hello.c -o hello
//and exec strip hello
#include<stdio.h>
int main()
{
        int a=111;
        char b[122];
        read(0,b,120);
        printf("%s",b);
}
```

#### Observed Results

  * I can not use u or s to debug program

#### Expected results

  * I can debug the program with stripped.

**Comment by Grazfather** [comment]
Can you please provide the binary and reproduce the error again after running `gef config gef.debug true`

**Comment by hugsy** [comment]
This is unlikely related to GEF but more to GDB. Do you get this error when running GDB only (without GEF)?

**Comment by qiannianshuangxue** [comment]
> This is unlikely related to GEF but more to GDB. Do you get this error when running GDB only (without GEF)?

run gdb without GEF also have this problem,thank you.I will close the problem。

**Comment by qiannianshuangxue** [comment]
the problem can be solved by use si.
