### ISSUE TITLE
Add 'version' command

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#601]
Let's add a `version` command that dumps the version (git hash, branch, and whether there are local modifications).

This will be handy for bug reports

We can make it get dumped automatically when debug is enabled along with runtime environment

**Comment by hugsy** [comment]
I've looked into that, but how do you think we can manage the users using the "one-file" gef (as opposed to the git cloned one) ?

**Comment by Grazfather** [comment]
What if we make the download command append something to the file? e.g. something like

```bash
wget -q -O "$HOME/.gdbinit-gef.py" https://github.com/hugsy/gef/raw/master/gef.py
test -f "$HOME/.gdbinit" && mv "$HOME/.gdbinit" "$HOME/.gdbinit.old"
echo "source $HOME/.gdbinit-gef.py" > "$HOME/.gdbinit"

# Get the hash of the commit
ref=$(curl https://api.github.com/repos/hugsy/gef/git/ref/heads/master | grep '"sha"' | tr -s ' ' | cut -d ' ' -f 3 | tr -d ",")

echo "GEF_SHA=$ref" >> "$HOME/.gdbinit"

exit 0
```

Then the version command can use `GEF_SHA` since it'll be defined at the module level.

**Comment by hugsy** [comment]
Hum that would work, we could even use the ref as part of the filename (instead of the generic `gdbinit-gef.py`, something like `gef-$rev.py`), since we already collect the filename in [`show_last_exception()`](https://github.com/hugsy/gef/blob/dev/gef.py#L1007)

**Comment by Grazfather** [comment]
Right, but that makes is harder to find the previous version in order to save it to .old (e.g. what if there is more than one that matches the glob in the home dir.

Also, how do we overwrite this version if it's installed via git?

**Comment by hugsy** [comment]
> Right, but that makes is harder to find the previous version in order to save it to .old (e.g. what if there is more than one that matches the glob in the home dir.
> 

Not sure I understand, `.old` is the `gdbinit` not `gdbinit-gef.py`, what's the problem here? We can change the install script to 

```bash
# Backup gdbinit if any
test -f "$HOME/.gdbinit" && mv "$HOME/.gdbinit" "$HOME/.gdbinit.old"

# Get the hash of the commit
ref=$(curl https://api.github.com/repos/hugsy/gef/git/ref/heads/master | grep '"sha"' | tr -s ' ' | cut -d ' ' -f 3 | tr -d ",")

# Download the file
wget -q -O "$HOME/.gef-${ref}.py" https://github.com/hugsy/gef/raw/master/gef.py

# Create the new gdbinit
echo "source ~/.gef-${ref}.py" > "~/.gdbinit"

exit 0
```

> Also, how do we overwrite this version if it's installed via git?

Same here, I don't follow: if installed via git, the `version` command will simply get the **running** gef version, jump to the dir and get the current head sha1. What is it to overwrite ?

**Comment by Grazfather** [comment]
I meant for cleanup. I just don't want to pollute someone's home dir with ten different `gef-<hash>.py`, but I did mix up the .old part.

**Comment by hugsy** [comment]
I'm not sure how it's a problem - because I see it as an easy way to revert to a known working version quickly. But I see your point, then maybe we can simply add a test in the install script to check if there are existing `gef-*.py` file(s), and if so does the user want to delete them. Thoughts?

**Comment by hugsy** [comment]
What do you think of : 
 - if git installed:
![image](https://user-images.githubusercontent.com/590234/105109257-12507880-5a71-11eb-9f6a-c84f14cc2679.png)

 - if standalone:
 ![image](https://user-images.githubusercontent.com/590234/105109403-55125080-5a71-11eb-9eab-7847d57be309.png)

**Comment by hugsy** [comment]
`ver` is the shortcut for `version`

**Comment by Grazfather** [comment]
That's very nice!

Are you saying here that for the standalone we will NOT use the git sha at all?

**Comment by Grazfather** [comment]
Why does the screen shot show `[]` around the loaded commands for standalone but not with clone install?

**Comment by hugsy** [comment]
> Why does the screen shot show `[]` around the loaded commands for standalone but not with clone install?

Because I'm an idiot and used the wrong file

**Comment by Grazfather** [comment]
hahaha.

Also: For git, we should add a `(dirty)` or similar if there are local changes.

**Comment by hugsy** [comment]
> That's very nice!
> 
> Are you saying here that for the standalone we will NOT use the git sha at all?

On my local modif, it shows as the full path, that's why I suggested to use the path to show the git rev. But then I realized if someone just download directly the raw from GH, the info will be missing... Is there a way to calculate the sha1 throughout the git history?

**Comment by Grazfather** [comment]
we could script something to do this, but git won't necessarily keep file-sized chunks internally, so the git tree will have hashes that don't match.

You're trying to think of a way to get a git sha from a gef.py sha?

```
for commit in range @^10...@
    git checkout $commit
    shasum -a 1 gef.py
done
```

If we need to debug for someone I don't think that that's too bad.

**Comment by hugsy** [comment]
> If we need to debug for someone I don't think that that's too bad.

That's exactly what I had in mind. But that for loop looks expensive... I was hoping git had a hidden feature to help on that. So I guess I'll just stick to the rev in the filename, I've also adjusted the update command to reflect that. I'll polish it up and push it. I'm also going to use that I have a bit of time this WE to publish a new release, the last one is really outdated.

Cheers
