### ISSUE TITLE
Issue due to github's caching? installation via wget received older source code

### ISSUE THREAD

**Issue by kiprasmel** [hugsy/gef#605]
I was going to create a PR to allow selecting the previous code color in the source window. I edited the ~/.gdbinit-gef.py file I got from github via wget, and then I tried creating a pull request.

There were a lot of diffs I didn't create. I thus cloned the repo instead and realised that such feature is already implemented!

The problem is that I didn't receive it because I would guess github uses some CDN on the raw file and doesn't update it properly when the file gets updated and thus I got an older version?

Honestly not sure where to go with this I just wanted to let you know this happens. Perhaps github should fix it, or perhaps gef should use some sort of different installation method that ensures the source is up to date (e.g. cloning with git and just taking the source file, which is a shame that we'd have to do this, but I guess github is messing stuff up 🤷)

**Comment by Grazfather** [comment]
It's not due to caching, it's probably due to you using http://gef.blah.cat/sh which downloads the master branch, while the dev branch has many newer features.

**Comment by hugsy** [comment]
You might prefer  using http://gef.blah.cat/dev

**Comment by kiprasmel** [comment]
@Grazfather 
> It's not due to caching, it's probably due to you using http://gef.blah.cat/sh which downloads the master branch, while the dev branch has many newer features.

yeah I just `wget -O` from the master branch's raw gef.py file, which is the same as `http://gef.blah.cat/py`, so yes, it is the master branch.

@hugsy 

> You might prefer using http://gef.blah.cat/dev for the latest updates. However for a PR, you should go with the Git version.

Yep got it, that's exactly what I did for #606

---

so yeah I was supposed to use the dev branch - got it, thanks guys.
