### ISSUE TITLE
Curl call on gef.sh should allow redirects.

### ISSUE THREAD

**Issue by frite** [hugsy/gef#609]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

  * Operating System / Distribution: OSX/Ubuntu
  * Architecture: x86_64 on MacOSX/ arm64 on ubuntu. 
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`: 

```
9.2
3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
```

#### Steps to reproduce

  1. `sh gef.sh` or follow the instructions. 

#### Minimalist test case
Following the instructions and after executing `gef.sh` to install, the contents of `gef.py` are the following.
```
$ cat ~/.gef-60fd341ba076942faac96fd6118ca927998ec0d9.py
<html><body>You are being <a href="https://raw.githubusercontent.com/hugsy/gef/master/gef.py">redirected</a>.</body></html>
```

#### Observed Results

  ```
$ cat ~/.gef-60fd341ba076942faac96fd6118ca927998ec0d9.py
<html><body>You are being <a href="https://raw.githubusercontent.com/hugsy/gef/master/gef.py">redirected</a>.</body></html>
```

#### Expected results

I should get the contents of gef.py 

This is a minor bug wrt. the installation script. I think the `-L` flag should be set in `curl` to follow redirects.

**Comment by frite** [comment]
Given the tiny scope of this fix, I went ahead and created  PR https://github.com/hugsy/gef/pull/610 to patch this.

**Comment by hugsy** [comment]
Closing
