### ISSUE TITLE
Show code at target of jump

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#61]
If a jump is to be taken, it would be nice if the code context view could disassemble at the jump target.

**Comment by Grazfather** [comment]
Hacked it in a bit:
<img width="531" alt="1__tmux" src="https://cloud.githubusercontent.com/assets/497310/18337075/466a4f74-7542-11e6-8603-6e67e24c14ed.png">

**Comment by hugsy** [comment]
Looking forward to see your PR for that :smile:

**Comment by hugsy** [comment]
Just don't forget to test all supported architectures (ARM, MIPS, PowerPC and SPARC).

**Comment by Grazfather** [comment]
That's what will take the most time. Right now it's x86 and only when it isn't something like `jmp eax` Do you know if that's something capstone can resolve?

**Comment by hugsy** [comment]
You can use `gdb.parse_and_eval` for that (see [docs](https://sourceware.org/gdb/onlinedocs/gdb/Basic-Python.html#Basic-Python)). Capstone is a disassembler, it cannot evaluate the operand values.

**Comment by Grazfather** [comment]
Sweet that'll probably be easiest. TY.

**Comment by hugsy** [comment]
No worries. The Python API for GDB documentation is actually quite complete, so you should be able to find all you need in there. It's just not that easy to search into it in a useful manner, but Google FTW

**Comment by Grazfather** [comment]
Finally got to look at this more, but it's going to be tricky. `parse_and_eval` can help me evaluate a target, but I'll have to recognize registers and use the correct syntax. I haven't used unicorn but if it's super lightweight maybe we could simulate the next instruction once we know its the jump and read the target pc?

Also we'll need a `is_branch` since we want this to work for _all_ jumps, not just conditionals.

**Comment by hugsy** [comment]
`parse_and_eval` can evaluate registers as well.
I can have a look at you already did, did you push it to Github ?

**Comment by Grazfather** [comment]
Just pushed. I swear I normally wouldn't push code this ugly!
https://github.com/hugsy/gef/compare/master...Grazfather:show_target?expand=1

**Comment by hugsy** [comment]
Ok I get your idea. I'll branch it, but it will take bit of effort to have it work on all architectures.

As always mate, thanks for the feedbacks!

**Comment by hugsy** [comment]
Current state after a669961 (dev)

  * [x] x86-32 / x86-64
  * [x] arm
  * [x] mips
  * [x] powerpc
  * [ ] sparc

![](https://i.imgur.com/f2E4ipt.png)

**Comment by hugsy** [comment]
Pushed to `master`.
