### ISSUE TITLE
Instant Setup Bash Script Miscoding 

### ISSUE THREAD

**Issue by GetRektBoy724** [hugsy/gef#611]
one of my friend want to run the GEF instant setup,and had a problem
`sh: 6: test: unexpected operator`
after i look on the script,yep there is a problem
on the line 6,probably the devs want to detect the first argument if it contain the word "dev",if its there,it change the branch to "dev"
maybe you guys can fix it ;)

**Comment by hugsy** [comment]
We cannot reproduce this bug.

Can you detail a step-by-step of how you encountered it ?

Thanks

**Comment by GetRektBoy724** [comment]
i just run
`$ sh -c "$(curl -fsSL http://gef.blah.cat/sh)"` and i got the error

**Comment by GetRektBoy724** [comment]
the better code of that is 
```
if [[ $1 = "dev" ]]; then
    branch="dev"
fi

**Comment by hugsy** [comment]
I see, the problem is somewhere else because the doc is wrong: the scripts we provide are bash scripts, and the docs shouldn't show `sh -c ....` but `bash -c ...`.

Thank you, the doc will be updated soon.

**Comment by GetRektBoy724** [comment]
ok :D

Pada tanggal Rab, 24 Feb 2021 pukul 03.47 crazy rabbidz <
notifications@github.com> menulis:
