### ISSUE TITLE
Remote 'g' packet reply is too long (expected 312 bytes, got 328 bytes): 

### ISSUE THREAD

**Issue by a309371807** [hugsy/gef#619]
gef➤  target remote localhost:11678
Remote debugging using localhost:11678
Reading /data/local/tmp/hello from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
Reading /data/local/tmp/hello from remote target...
Reading symbols from target:/data/local/tmp/hello...
Remote 'g' packet reply is too long (expected 312 bytes, got 328 bytes): 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fbfeff0000000084c778f7100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by hugsy** [comment]
1. Prefer `gef-remote`
2. GDB needs to know the target binary architecture, otherwise it's guessing (usually wrong)
3. If still not working, follow correctly the [issue template](https://github.com/hugsy/gef/issues/new?assignees=&labels=triage&template=bug_report.md&title=)

**Comment by ooooldbaby** [comment]
在最新的版本中仍旧出现这个问题，我在arm64上进行调试
gdb 13.1
我应该怎么修改呢
