### ISSUE TITLE
[Regression] Memory caching doesn't refresh memory as intended

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#624]
Your issue will be closed unless you confirm the following (insert `x` in the
brackets if done/agreed):

* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Ubuntu 20.04 LTS 
* Architecture: amd64
* GEF version (including the Python library version) run `version` in GEF: `GDB 9.2 using Python engine 3.8 `

### Step 2: Describe your problem

Performance improvement by caching the memory from commit 7124587c489ed83825463408afef89a2f9eb24a4 have proven not to work as intended, as it fails to correctly refresh the memory when the change comes from the code itself and not the debugger.

#### Steps to reproduce

1. compile test case below
2. `gdb -ex run ./a.out` 
3. on first trap hit , see the memory values behind cached
4. `continue`
5. on second trap hit , the new values are **not** being refreshed 

#### Minimalist test case

```c
// compile with gcc  ./a.c
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

void main()
{
    char a[16] = "foobar\0";
    char* b = a;
    printf("a -> %p\n", a);
    b += 5*8;
    uint64_t* c = b;
    __asm__("int3"); // create a first set of memory values that will be cached
    printf("rip -> %p\n", b);
    printf("fake RIP overwrite = %llx\n", *c);
    *c = 0x4141414141414141;
    __asm__("int3"); // when hit, the stack frame shows the old cached value
}
```

#### Observed Results

* What happened? This could be a description, log output, etc.

![image](https://user-images.githubusercontent.com/590234/111918179-20a31c80-8a41-11eb-89a2-cbdc9a84bb25.png)

#### Expected results

* What did you expect to happen?

The stack should show 0x4141414141414141

Note that `reset-cache` has no effect here, still showing the wrong value.

However, if we manually edit memory (e.g. using `patch byte`), the on-changed memory hook is taken, and the correct value shown. When the code changes the memory "itself", changes are not applied.

**Comment by Grazfather** [comment]
Issue was that `reset-caches` doesn't find methods and can't clear their cache. I fixed it by pulling `dereference_from` into a function, which was easy since it was already a `@staticmethod`
