### ISSUE TITLE
"Heap arenas" command prints "'MallocStateStruct' object has no attribute 'n'"

### ISSUE THREAD

**Issue by irontigran** [hugsy/gef#629]
Your issue will be closed unless you confirm the following (insert `x` in the
brackets if done/agreed):

* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Fedora 8.3-7.fc30
* Architecture: 5.6.13-100.fc30.x86_64 (x86_64)
* GEF version (including the Python library version): rev:eed448b232177287cebc725b7139b30b815dfacc (Git - clean) Python 3.7

#### Steps to reproduce

1. Compile the test binary `default.out` from gef repo:
```bash
cd tests/binaries; make default.out; mv /tmp/default.out .
```

2. Start binary and try to print arenas:
```bash
gdb default.out
gef> start
gef> heap arenas
[!] Command 'heap arenas' failed to execute properly, reason: 'MallocStateStruct' object has no attribute 'n'
```

#### Observed Results

* gef printed an error message

#### Expected results

* gef to list all the arenas in the program

#### Traces
```
─────────────────────────────── Exception raised ───────────────────────────────
AttributeError: 'MallocStateStruct' object has no attribute 'n'
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/user/gef/gef.py", line 714, in __getitem__()
    →     return getattr(self, item)
↳ File "/home/user/gef/gef.py", line 744, in __getattr__()
    →     return self.__arena[item]
↳ File "/home/user/gef/gef.py", line 782, in __str__()
    →     return fmt.format(self.__addr, self.top, self.last_remainder, self.n, self.nfree, self.sysmem)
↳ File "/home/user/gef/gef.py", line 6523, in do_invoke()
    →     gef_print("{}".format(arena))
↳ File "/home/user/gef/gef.py", line 2537, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/user/gef/gef.py", line 247, in wrapper()
    →     rv = f(*args, **kwargs)
↳ File "/home/user/gef/gef.py", line 4079, in invoke()
    →     bufferize(self.do_invoke)(argv)
```

`git bisect` pretty quickly tracked the breaking commit to 97548f0 minor changes for heap structure. In the `GlibcArena` class, it looks like the attempt to access `self.n` in `__str__` is intercepted by the `__getattr__` function.

**Comment by hugsy** [comment]
Good catch!

There's a small logic error, I'll fix quickly.
