### ISSUE TITLE
Support adding/removing aliases through the `aliases` command

### ISSUE THREAD

**Issue by daniellimws** [hugsy/gef#636]
**Is your feature request related to a problem? Please describe.**
Currently we can add our own aliases to gef in .gef.rc, and can list them out with the `aliases` command. It would be convenient to also be able to add the aliases through a gef command, instead of modifying the .gef.rc file manually.

**Describe the solution you'd like**
Commands to add/remove aliases. E.g. support `aliases add|rm|list` instead of just `aliases`.

**Comment by hoefler02** [comment]
I gave it a shot [here](https://github.com/hoefler02/gef/blob/aliases/gef.py). It works fine but is a little messy. I just need to clean it up a bit and figure out how to refresh gef after the `aliases rm` command. The command works properly (and edits `~/.gef.rc`) but currently GDB needs to be relaunched for the alias to stop working.

**Comment by hugsy** [comment]
Nice effort @hoefler02 Try to take a look at how you can use subcommands (`list`, `rm`, `add`,etc.) directly in GDB so you can use the TAB completion.

Also AFAIK GDB doesn't offer a way to remove aliases at runtime.

**Comment by hugsy** [comment]
I will be preparing a release today, so I have removed the milestone for this issue as it is not blocking.

**Comment by hoefler02** [comment]
Sounds good. I have been busy lately but have a solution almost ready.
