### ISSUE TITLE
gdb10.2 has an error with the gef plugin

### ISSUE THREAD

**Issue by 1094093288** [hugsy/gef#647]
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
  File "~/.gdbinit-gef.py", line 965
    pattern_libc_ver = re.compile(rb"glibc (\d+)\.(\d+)")
                                                       ^
SyntaxError: invalid syntax

What is the cause of this？

**Comment by Grazfather** [comment]
I am guessing your GDB is using python2 and not python3

**Comment by 1094093288** [comment]
Thanks, in the end, only use the parameter ‘--with-python=/usr/bin/python3.5’ to compile successfully and use it normally.
I also want to ask a question: How to upgrade the gdb version of gdb-multiarch? His gdb version is not consistent with the compiled gdb version
➜ ~$ gdb-multiarch -v
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/&gt;.
For help, type "help".
Type "apropos word" to search for commands related to "word".


➜ ~$ gdb -v
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hugsy/gef] gdb10.2 has an error with the gef plugin (#647)





 
I am guessing your GDB is using python2 and not python3

**Comment by Grazfather** [comment]
I am not sure how you are building your gdb, but I think you can just use `--enable-targets=all` on your normal build.

**Comment by 1094093288** [comment]
Thank you. According to your suggestion, my problem is solved. You can debug the program of mips architecture without using gdb-multiarch.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 晚上9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hugsy/gef] gdb10.2 has an error with the gef plugin (#647)





 
I am not sure how you are building your gdb, but I think you can just use --enable-targets=all on your normal build.

**Comment by Grazfather** [comment]
I'm glad it worked out for you.

**Comment by 1094093288** [comment]
Hello, I want to ask a question：
I want to use gdb to debug mips architecture programs, but the compiled gdb does not support stack, vmmap and other instructions. After using the gef plug-in, the vmmap instruction shows the following exceptions:
&nbsp; &nbsp; &nbsp;0x400868 <main+24&gt;&nbsp; &nbsp; &nbsp; &nbsp; sw&nbsp; &nbsp; &nbsp;gp, 16(sp)
&nbsp; &nbsp; &nbsp;0x40086c <main+28&gt;&nbsp; &nbsp; &nbsp; &nbsp; sw&nbsp; &nbsp; &nbsp;a0, 536(s8)
&nbsp; &nbsp; &nbsp;0x400870 <main+32&gt;&nbsp; &nbsp; &nbsp; &nbsp; sw&nbsp; &nbsp; &nbsp;a1, 540(s8)
&nbsp;→&nbsp; &nbsp;0x400874 <main+36&gt;&nbsp; &nbsp; &nbsp; &nbsp; lui&nbsp; &nbsp; v0, 0x40
&nbsp; &nbsp; &nbsp;0x400878 <main+40&gt;&nbsp; &nbsp; &nbsp; &nbsp; lhu&nbsp; &nbsp; v0, 3084(v0)
&nbsp; &nbsp; &nbsp;0x40087c <main+44&gt;&nbsp; &nbsp; &nbsp; &nbsp; sh&nbsp; &nbsp; &nbsp;v0, 24(s8)
&nbsp; &nbsp; &nbsp;0x400880 <main+48&gt;&nbsp; &nbsp; &nbsp; &nbsp; addiu&nbsp; v0, s8, 26
&nbsp; &nbsp; &nbsp;0x400884 <main+52&gt;&nbsp; &nbsp; &nbsp; &nbsp; li&nbsp; &nbsp; &nbsp;v1, 498
&nbsp; &nbsp; &nbsp;0x400888 <main+56&gt;&nbsp; &nbsp; &nbsp; &nbsp; move&nbsp; &nbsp;a2, v1
──────────────────────────────────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, stopped 0x400874 in main (), reason: BREAKPOINT
──────────────────────────────────────────────────────────────────────────────────────────────── trace ────
[#0] 0x400874 → main()
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
gef➤&nbsp; vmmap
[ Legend:&nbsp; Code | Heap | Stack ]
Start&nbsp; &nbsp; &nbsp; End&nbsp; &nbsp; &nbsp; &nbsp; Offset&nbsp; &nbsp; &nbsp;Perm Path
0x00000000 0xffffffff 0x00000000 rwx /root/Desktop/pwn-test/mips-pwn/stack_bof_2
gef➤&nbsp; stack
Undefined command: "stack".&nbsp; Try "help".



The vmmap command cannot display libc, and the stack command cannot be used；What is going on?


gdb version：10.2&nbsp; &nbsp; --with-python=python3.5&nbsp; --enable-targets=all






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 晚上10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hugsy/gef] gdb10.2 has an error with the gef plugin (#647)





 
I'm glad it worked out for you.

**Comment by Grazfather** [comment]
please ask questions on our discord

**Comment by BlackBird-BB** [comment]
A similar question just happened on me. I'm wondering how to let gdb use python3 interpret script instead of python2 on Ubuntu1604.
