### ISSUE TITLE
Output context to different TTY

### ISSUE THREAD

**Issue by pwntester** [hugsy/gef#65]
Hi,

Thanks ofr GEF, it is really useful. There is one minor thing that I think can make it even better. Would it be possible to output the Context info toa different TTY like gdb-dashboard does:
https://github.com/cyrus-and/gdb-dashboard#dashboard--output-file

This helps keep an eye on the context while printing different variables or areas of memory

Thanks!
A

**Comment by hugsy** [comment]
Hi @pwntester !

Thanks for the feedback! I'm not very familiar with gdb-dashboard, but by the look of it, it should be really easy to integrate. I'll work on that.

**Comment by hugsy** [comment]
Hey mate,

It was ridiculously easy :smile: 

Simply type:
```
gef➤ gef config context.redirect /dev/pts/WHATEVER_OTHER_TTY
```

To make it cleaner, I would also suggest to set the `clear_screen` setting:
```
gef➤ gef config context.clear_screen true
```
And you'll  get something like:
![](https://i.imgur.com/YgiLmqg.png)
Let me know how it works for you :wink:

**Comment by hugsy** [comment]
Yeah, all the functions were already implemented, just needed to wrap things together :smile: 

Glad it worked, and thanks for the feedbacks !
