### ISSUE TITLE
cannot open remote path /proc/7349/maps

### ISSUE THREAD

**Issue by threadroc** [hugsy/gef#655]
virtualbox ubuntu16.04
gdb version 9.1
gdbserver version 7.11 android-arm

error:
Python Exception <class 'OSError'> cannot open remote path /proc/30760/maps: 
Python Exception <class 'gdb.error'> Error occurred in Python: cannot open remote path /proc/30760/maps: 
Python Exception <class 'gdb.error'> Error occurred in Python: Error occurred in Python: cannot open remote path /proc/30760/maps

What is the reason?

**Comment by hugsy** [comment]
This is a useless bug report for us to help you. Closing. If you want to file another one follow the template.
