### ISSUE TITLE
Undefined command: "uf".  Try "help".

### ISSUE THREAD

**Issue by IamLucif3r** [hugsy/gef#657]
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Linux parrot 5.10.0
* Architecture: Debian
* GEF version (including the Python library version) run `version` in GEF. 
GEF: (Standalone)
GDB: 10.1.90.20210103-git
GDB-Python: 3.9

### Step 2: Describe your problem
- Undefined command: "uf".  Try "help".
When I try to use command ``` uf _start ``` an error occurs saying:
  - Undefined command: "uf".  Try "help".
#### Steps to reproduce

1. Type ``` uf _start ``` in gef

#### Minimalist test case

```c
// compile with gcc -fPIE -pic -o my_issue.out my_issue.c
int main(){ return 0; }
```

#### Observed Results

* What happened? This could be a description, log output, etc.

#### Expected results

* What did you expect to happen?
Dump of assembler code for _start function

**Comment by hugsy** [comment]
`uf` is a WinDbg command, it was moved to `gef-extras` (https://github.com/hugsy/gef-extras/blob/master/scripts/windbg.py)
