### ISSUE TITLE
Switch Debruijn pattern to use 4 byte period

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#658]
1. Better compatibility with `pwntools`
2. You can search with a smaller segment
3. You still get a ton of data before 'repeats'

**Comment by hugsy** [comment]
This will be handled directly in `dev-argparse`: set the default to 4 bytes and add a command line option `-n`

**Comment by Grazfather** [comment]
Great. Let's close this ticket after that PR is merged and we test its compatibility with pwntools.
