### ISSUE TITLE
UnicornEmulateCommand: "python" should be "python3"

### ISSUE THREAD

**Issue by theguy147** [hugsy/gef#677]
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Ubuntu 20.04
* Architecture: x86_64
* GEF version (including the Python library version) run `version` in GEF:
```
GEF: (Standalone)
SHA1(/home/theguy/.gdbinit-gef.py): 1bcadc4a2cb35354163c45a19316392f6f982108
GDB: 10.2
GDB-Python: 3.9
```

### Step 2: Describe your problem

in `UnicornEmulateCommand()` gef tries to find the python executable like this `which("python")` whereas it would be better to search with `which("python3")` like done in the `if __name__ == "__main__"` section.

Distros like Ubuntu 20.04 e.g. don't have a `python` executable if only `python3` is installed and other Distros that do usually just symlink `python` to `python3`. So using `python3` should work on every Distro.

#### Steps to reproduce

1. Use Distro where only `python3` is available (like ubuntu 20.04 without python2 installed))
2. `gdb -q ${which ls}"
3. `emu 10`

#### Observed Results

```
[!] Command 'unicorn-emulate' failed to execute properly, reason: Missing file `python`
```

#### Expected results

Something like:

```
[+] Starting emulation: 0x55555555a7d0  →  0x55555555a7f8
[...]
```

**Comment by hugsy** [comment]
This is a local configuration option to each Linux, not a gef issue.
It can be fixed by creating a simple symlink or using `update-alternatives`. Now that Python2 has been deprecated, Python in GEF means Python3.

**Comment by theguy147** [comment]
Exactly my point! So why is there an inconsistency in `gef.py` for this?

**Comment by theguy147** [comment]
Another option would be to use the recommendation from `PEP394`: use `sys.executable` instead of `which("python")`

**Comment by hugsy** [comment]
> Another option would be to use the recommendation from `PEP394`: use `sys.executable` instead of `which("python")`
> 
> ```
> When reinvoking the interpreter from a Python script, querying sys.executable to avoid hardcoded assumptions regarding the interpreter location remains the preferred approach.
> ```

That's a valid point, we may prefer turn into that approach actually.

**Comment by theguy147** [comment]
Unfortunately I just noticed that `gdb` behaves very oddly in regards to the used `python` interpreter and breaks the promise made by `sys.executable` (as a hack `gdb` changes its python path at compile-time in [these lines)](https://github.com/bminor/binutils-gdb/blob/fec458f0fc42012c12cc3a2fb5116ade70a59f38/gdb/python/python.c#L1722-L1757)

The result is that `sys.executable` points to the location the system-wide python interpreter was at the time of compilation. With package managers like `apt` providing pre-compiled versions this might differ from the local python interpreter.

Therefore the `PEP394` recommendation is not always possible here. 

I see two possible solutions to this issue:
- use of a little bit hacky fix as well: set `sys.executable = which("python3")` once at the beginning and then always use `sys.executable`. The hacky part is the manipulation of that value while the advantage would be to only have one place in the code where this kind of hardcoded assumption is made.
- use the PEP recommendation all the way through but add a check at the beginning to determine if the interpreter at `sys.executable` can be found and provide a clear error message if that is not the case so the user can fix his/her Linux configuration. This solution is probably cleaner and in complete compliance with the recommendations.

**Comment by hugsy** [comment]
Actually we already defined `pythonbin` initialized very early during the startup process (see https://github.com/hugsy/gef/blob/dev/gef.py#L10701) which does use `python3`. Can you update your PR to use that value then? That'll be good enough for now

**Comment by theguy147** [comment]
ok. I did so and also changed `pythonbin` to `PYTHONBIN` to clarify that it is a constant.
