### ISSUE TITLE
Improve gef speed

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#68]
@Grazfather reported some slow performances on `gef`.

Check on that

**Comment by hugsy** [comment]
Several commits will come that drastically improve `gef` speed.

Some notes from personal benchmarks:
  * Python3 is slower that Python2
  * GDB+Python3 is **much** slower than GDB+Python3 
For example, using `timeit` for Python3
```
gef> pi
>>> timeit.timeit('gdb.execute("x/1i $pc", to_string=True)', number=1000, setup="import gdb") 
0.09101070600445382
```
The same snippet on GDB+Python2 gives a result of 0.029072046279907227.

**Comment by hugsy** [comment]
**TODO**: According to tests using `timeit`, `str.format()` is **always** faster than `fmtstr % (params,)`. 
Replace all instances with `str.format()`.

**Comment by hugsy** [comment]
Done with
de074fd
dcbf3a6
5bb1733
b997d97

**Comment by Grazfather** [comment]
c43acfe79

**Comment by Grazfather** [comment]
We should do some comparisons with master today vs master back then! It feels much quicker to me now.

**Comment by hugsy** [comment]
Agreed, even when use on QEMU :smile: 
But let's continue making it faster.

**Comment by hugsy** [comment]
I did some tests today, to check if GEF is really faster, so here are some numbers.

Compared to GEF between current HEAD (ffa903f110537e5d99eb477a5c5e344828685f27) and one year ago (eb6e5ddf1a4acb1cc13f7e318625e251f4cf0673) (time is the average in seconds on 100 executions on my core i7 - only on GDB+Py3):

| Command | HEAD        | eb6e5ddf1a4acb1cc13f7e318625e251f4cf0673 |
| ------------- |:-------------:|-----:|
| `start` + `context` | 0.34s        | 0.41s | 
| `start` + 100 x `xinfo $pc` (test new cache) | 0.46s | 0.51s | 
| `start` + `dereference $sp 10` |  0.35s | 0.42s | 

I think it's pretty safe to say that GEF is massively faster than what it was, especially on the commands/functions very regularly used (I'm particularly happy about the cache :sunglasses: ). 

So this issue is complete :+1: , thanks @Grazfather !

Closing it...
