### ISSUE TITLE
Issue with memory watch (fail to show)

### ISSUE THREAD

**Issue by arvyanh** [hugsy/gef#681]
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 10.2
* Python: 3.8.10 - final
* OS: Linux - 5.8.0-59-generic (x86_64)
──────────────────────────────────────────────

#### Steps to reproduce

1. open executable
2. watch a memory

#### Minimalist test case

```c

     11      int* heap = malloc(sizeof(int)*1024);
     12
             // i=0x0
 →   13      for(int i = 0; i < 1024; i++){
     14          heap[i] = i;
     15      }
     16
```

#### Observed Results

* What happened? This could be a description, log output, etc.
No memory dump are showed, and shows a hexdump error
```
...
───────────────────────────────────────────────────────────────────────── memory:0x5555555592a0 ────
usage: hexdump qword [-h] [--reverse] [--size SIZE] [address]
hexdump qword: error: unrecognized arguments: 16

─────────────────────────────── Exception raised ───────────────────────────────
RuntimeWarning:
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/arvyanh/script/misc/gdb-dash/gef-git/gef.py", line 2603, in FakeExit()
    →     raise RuntimeWarning
↳ File "/usr/lib/python3.8/argparse.py", line 2520, in exit()
    →     _sys.exit(status)
↳ File "/usr/lib/python3.8/argparse.py", line 2533, in error()
    →     self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
↳ File "/usr/lib/python3.8/argparse.py", line 1783, in parse_args()
    →     self.error(msg % ' '.join(argv))
↳ File "/home/arvyanh/script/misc/gdb-dash/gef-git/gef.py", line 2653, in wrapper()
    →     parsed_args = parser.parse_args(*(args[1:]))
↳ File "/home/arvyanh/script/misc/gdb-dash/gef-git/gef.py", line 2557, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/arvyanh/script/misc/gdb-dash/gef-git/gef.py", line 239, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/arvyanh/script/misc/gdb-dash/gef-git/gef.py", line 4201, in invoke()
    →     bufferize(self.do_invoke)(argv)
```

**reverts to a early version seems to solve the issue**: (I choose a random version earlier e.g.  6b82ee6 Jan 9, 2021)

The online test version also seems to work

#### Expected results

* What did you expect to happen?
memory show correctly.

#### Traces
all the info above are from debug mode

**Comment by theguy147** [comment]
can confirm that `memory watch` does not currently work (for me). A quick `git bisect` shows me that it doesn't work anymore since commit e38f7dde4a390d217f82032bc49898a6e313a6f4.

**Comment by theguy147** [comment]
There is some mess with the syntax of the `hexdump` command since that commit. 

`memory watch` calls `hexdump [WORD_LENGTH] [LOCATION] [SIZE]` for non-pointers. But this syntax doesn't work anymore since that commit. Now it should be (?) `hexdump [WORD_LENGTH] [LOCATION]  [--size SIZE]`.

Also the `_syntax_` and `_example_` for `HexdumpCommand` don't match (and or seemingly both currently wrong in regards to SIZE).

**Comment by theguy147** [comment]
I guess a test for the `memory watch` command should be implemented once the expected syntax has been defined.

**Comment by hugsy** [comment]
> I guess a test for the `memory watch` command should be implemented once the expected syntax has been defined.

100% - and to be honest I thought it was 😁

**Comment by theguy147** [comment]
@arvyanh Can you update GEF and see if your issue has been solved?

**Comment by arvyanh** [comment]
> @arvyanh Can you update GEF and see if your issue has been solved?

Yes, I think its working now
