### ISSUE TITLE
Add git blob hash to `version` command

### ISSUE THREAD

**Issue by theguy147** [hugsy/gef#682]
### Description

When looking at issues it is sometimes helpful to understand on which commit the person has been when the problem occurred. Therefore the `version` command already includes a `SHA1` file hash. Unfortunately this file hash cannot be used easily to search through the `git` revisions of `gef.py` even though git uses `SHA1` to hash every file and stores that information in a easy-to-search way. The problem is that `git` prepends a `blob header` to each file before hashing.

### Current Situation

Currently the only way to find the commit the person was on is as follows (and takes longer to execute which each new commit):
1. Find every commit that affected the file:
```bash
git log --all --pretty=format:%H gef.py
```
2. checkout every one of those commits (hopefully using a script and not by hand)
3. create the `SHA1` hash:
```bash
sha1sum gef.py
```
4. compare that one to the one you are searching and return the commit if they match

### Suggested solution

Additionally to the `SHA1` add a `blob hash` to the `version` command. This is easily done by prepending `blob <size string>\0` before hashing.

Now finding the matching commits is as easy and quick as executing
```bash
git log --oneline --find-object <blob hash>
```

EDIT: I am aware that ideally everybody posting an issue is on the current `dev` branch but as you very well know that is not always the case. Also I am happy to create a PR for this if accepted so nobody else has to put (minimal) effort into this issue but me.

**Comment by hugsy** [comment]
That's perfectly reasonable: yeah if you can PR it, I'll review and merge quickly so we have a better way to find the versions of gef affect with a specific issue.

PS: @theguy147 are you on the discord channel ? If so what is your handle (DM me if you don't wanna have it public)?

**Comment by Grazfather** [comment]
I don't understand this. The first line out from `version` is the git commit hash.

```
gef➤  version
GEF: rev:0ad5f9976cb09071ff83456e1c285e80f9e02b6a (Git - clean)
SHA1(/home/graziano.misuraca/code/gef/gef.py): 3a1557190297912278671d27454d3d1fcda619e5
GDB: 8.1.0.20180409-git
GDB-Python: 3.6
```

**Comment by Grazfather** [comment]
I don't understand this. The first line out from version is the git commit hash.

```
gef➤  version
GEF: rev:0ad5f9976cb09071ff83456e1c285e80f9e02b6a (Git - clean)
SHA1(/home/graz/code/gef/gef.py): 3a1557190297912278671d27454d3d1fcda619e5
GDB: 8.1.0.20180409-git
GDB-Python: 3.6
```

**Comment by Grazfather** [comment]
If someone isn't using git then the blob hash won't work anyway, so this just adds extra information that is made redundant by the GEF rev.

**Comment by theguy147** [comment]
> I don't understand this. The first line out from version is the git commit hash.
> 
> ```
> gef➤  version
> GEF: rev:0ad5f9976cb09071ff83456e1c285e80f9e02b6a (Git - clean)
> SHA1(/home/graz/code/gef/gef.py): 3a1557190297912278671d27454d3d1fcda619e5
> GDB: 8.1.0.20180409-git
> GDB-Python: 3.6
> ```

You're right if a git repo is found. but if it is `standalone` obviously that information is missing. E.g. for Arch Linux where `gef` has been installed with the package manager that information is always missing

**Comment by hugsy** [comment]
> 
> You're right if a git repo is found. but if it is `standalone` obviously that information is missing. E.g. for Arch Linux where `gef` has been installed with the package manager that information is always missing

What ?? GEF is packaged ?

**Comment by theguy147** [comment]
> > You're right if a git repo is found. but if it is `standalone` obviously that information is missing. E.g. for Arch Linux where `gef` has been installed with the package manager that information is always missing
> 
> What ?? GEF is packaged ?

not officially but in the AUR (Arch User Repository)

**Comment by hugsy** [comment]
WTF ... https://aur.archlinux.org/packages/gef-git/
```
Last Updated:  2018-04-07 13:58
```

**Comment by theguy147** [comment]
> WTF ... https://aur.archlinux.org/packages/gef-git/
> 
> ```
> Last Updated:  2018-04-07 13:58
> ```

its a `git` package and thereby you can setup your AUR helper to automatically update it when the upstream git repo is updated. That date is the last time the so called `PKGBUILD` file was changed - that's the recipe to install it ;)

**Comment by hugsy** [comment]
That's the exact reason we made the upgrade directly from the command line... 🤦‍♂️

**Comment by hugsy** [comment]
> > WTF ... https://aur.archlinux.org/packages/gef-git/
> > ```
> > Last Updated:  2018-04-07 13:58
> > ```
> 
> its a `git` package and thereby you can setup your AUR helper to automatically update it when the upstream git repo is updated. That date is the last time the so called `PKGBUILD` file was changed - that's the recipe to install it ;)

Ah I see, but still...

**Comment by theguy147** [comment]
Anyway I think the git information is also omitted if you source a symlink in your gdbinit file instead of the actual `gef.py` in its directory.
I just noticed in some of the issues that this information was missing but I could still find the commit using the above described technique so I came up with the idea to make it easier...
