### ISSUE TITLE
heap chunks doesn't list chunks in a non-main arena

### ISSUE THREAD

**Issue by irontigran** [hugsy/gef#706]
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Fedora 31
* Architecture: x86-64
* GEF version (including the Python library version) run `version` in GEF.
```
GEF: rev:169e6e6dad57fe1325b1cabafbaf405cd5705cb7 (Git - clean)
SHA1(~/gef/gef.py): cd2793e58829c5b047204f8b73cb53d2c8835015
GDB: Fedora 8.3.50.20190824-30.fc31
GDB-Python: 3.7
```

### Step 2: Describe your problem

The `heap chunks` command does not list chunks in non-main arenas, even after switching arenas with the `heap set-arena` command. This looks like the same issue as #422, but it looks to still be a problem, and I thought it could use a more careful description.

#### Steps to reproduce

From the project root directory:

1. `make testbins`
2. `gdb -ex 'run' /tmp/heap-non-main.out`
3. List the available arenas with `heap arenas`
4. Set the current arena to the non-main arena with `heap set-arena`
5. Print the address of `p2` with `p p2`
6. Run `heap chunks` and note that it only prints chunks from the main arena - `p2` is not among them. (See the screenshot below)

#### Minimalist test case

`heap-non-main.c`, from the standard test cases, is a good minimal test case.

```c
// compile using make, or gcc -Wall -DDEBUG=1 -ggdb -O0 -pthread -o /tmp/heap-non-main.out heap-non-main.c
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

void *thread()
{
        void* p1 = malloc(0x18);
        void* p2 = malloc(0x18);
        free(p1);
        __builtin_trap();
        (void)p2;

        return NULL;
}

int main(int argc, char** argv, char** envp)
{
        void* p1 = malloc(0x10);

        pthread_t thread1;
        pthread_create(&thread1, NULL, thread, NULL);
        pthread_join(thread1, NULL);

        (void)p1;
        return EXIT_SUCCESS;
}

```

#### Observed Results

`gef`'s `heap chunks` command only prints the chunks in the main arena.

#### Expected results

`heap chunks` should print the chunks in a non-main arena if that arena has been set to be the current arena using `heap set-arena`.

#### Traces

![gef-bad-heap-chunks](https://user-images.githubusercontent.com/22407135/132098300-fcb3ed4f-b5e0-43d2-86dd-9d29d01f653c.png)

**Comment by theguy147** [comment]
yes, you're right!

the `heap chunks` internally always uses `main_arena` and starts looking at chunks from the start of the `heap_section`:

https://github.com/hugsy/gef/blob/169e6e6dad57fe1325b1cabafbaf405cd5705cb7/gef.py#L6706

https://github.com/hugsy/gef/blob/169e6e6dad57fe1325b1cabafbaf405cd5705cb7/gef.py#L6712

Here options should be added to allow usage with non-main-arenas.

Furthermore `MallocStateStruct` currently only allows to be used with symbols because it unconditionally prepends a "&" sign to the address passed:

https://github.com/hugsy/gef/blob/169e6e6dad57fe1325b1cabafbaf405cd5705cb7/gef.py#L638

I will create a PR later today or tomorrow after some more testing.

**Comment by theguy147** [comment]
@irontigran I have opened a PR (#706) for this issue but it is still missing some tests that should/will be added later. If you want you can test it in the meantime and report back if it solves this issue for you.
