### ISSUE TITLE
Stack addresses won't dereference on remote debug target

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#73]
UPDATE: Reason is is that the stack address is considered 'invalid' because the address isn't found to be in a valid range, since `file_lookup_address` doesn't work for stack addresses in remote processes.
![](https://cloud.githubusercontent.com/assets/497310/19135378/1b7e82fc-8b19-11e6-8d4a-891e032ab857.png)

This is with arm-linux-gnueabi-gdbserver, with osx compiled as the remote client. Same issue with `telescope`. Will investigate more after work.

**Comment by Grazfather** [comment]
This doesn't seem to be a problem when running gdb on the arm machine itself, just with the gdbserver. Before I dig into this: Do you know any reason this would fail?

**Comment by hugsy** [comment]
No idea. Can you even read memory ? Like 
```
gef> x/x $sp
``` 
then try
```
gef> dereference $sp
```

**Comment by Grazfather** [comment]
```
gef> x/10x $sp
0x7efed59c:     0x00000000      0xffffffff      0x00000003      0x000100d9
0x7efed5ac:     0x0008db4d      0x00000000      0x7efed608      0x7efed608
0x7efed5bc:     0x00027737      0x00000000
gef> dereference $sp 20
0x7efed59c|+0x0000:     <-$sp
0x7efed5a0|+0x0004:
0x7efed5a4|+0x0008:
...
```

The issue is that the address is being found as invalid, the reason for that is that it can't find the address with neither `process_lookup_address` nor `file_lookup_address`.

`vmmap` doesn't work either. Is that expected with remote? That would explain it.

**Comment by Grazfather** [comment]
It reads the sections from /proc/pid/maps _on the local system_. Of course that won't work with remote targets 😆

**Comment by hugsy** [comment]
Use `gef-remote`

**Comment by Grazfather** [comment]
Yes I was. Same issue. Both `process_lookup_address` and `file_lookup_address` return None. `process_lookup_address` doesn't behave differently with `gef-remote`, file_lookup_address would work, but since this is a stack address I am dereferencing, its overlapping range obviously isn't found in `info file`.

**Comment by hugsy** [comment]
Cannot reproduce, working well on a QEMU ARMv6 VM:

![1](https://cloud.githubusercontent.com/assets/590234/20027548/754580a2-a35a-11e6-9f6b-44b989465cba.png)

Can you provide more info on your test env?

**Comment by Grazfather** [comment]
I will try to repro again on Monday (hw is at work) and try to repro on a pi.

**Comment by Grazfather** [comment]
I also cannot repro on my grazberrypi with remote debugging.

When running it locally it's successfully downloading the maps file (impressive feature!). I think this is what's failing on the other machine.

**Comment by hugsy** [comment]
So was it a false positive on your end ? Can we close this issue then ?

**Comment by Grazfather** [comment]
No, let me repro on the bad machine: I think it fails simply because the file download fails.

**Comment by Grazfather** [comment]
Can't repro!
