### ISSUE TITLE
Modify X86 function_parameters to improve support for plugins

### ISSUE THREAD

**Issue by caprinux** [hugsy/gef#777]
Reference: https://github.com/mahaloz/decomp2gef/pull/13

**Is your feature request related to a problem? Please describe.**

As of now, X86.function_parameter is configured as such
```py
 function_parameters = ["$esp", ]
```
Plugins which make use of function_parameters will experience IndexError when trying to reference any parameter beyond the first parameter. 

**Describe the solution you'd like**
Perhaps we could broaden our definition for the X86 function_parameter by providing a few additional parameters

```py
function_parameters = ['$esp', '$esp+4', '$esp+8', '$esp+12', '$esp+16', '$esp+20']
```

As far as I know this should be merely an extremely minor quality change which should not break anything as far as I have tested.

Any opinions?

**Comment by theguy147** [comment]
sorry, for only replying this late to your issue. we are in the middle of some major refactoring of GEF.

I see your point, but just increasing the `function_parameters` a few places does not really solve the underlying issue. It might be an idea to convert it to a method that takes an index and returns the appropriate string instead. @hugsy what do you think?
