### ISSUE TITLE
set-flags doesn't work on ARM

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#79]
```bash
gef> flags ~thumb
Python Exception <class 'gdb.error'> Attempt to assign to an unmodifiable value.:
Error occurred in Python command: Attempt to assign to an unmodifiable value.
gef> info registers $cpsr
cpsr           0x20000030       536870960
gef> p/x $cpsr
$7 = 0x20000030
gef> set $cpsr = 0x20000010
Attempt to assign to an unmodifiable value.
```

I don't think it's an issue with gef... just that you can't write directly to the CPSR in gdb for some reason.

**Comment by hugsy** [comment]
There is no issue. `THUMB` is a CPU mode of the ARM processor family, not an editable flag of the CPS register. It cannot be edited. 

But maybe `gef` could spit out a more human-friendly error message.

**Comment by Grazfather** [comment]
haha what a brain fart on my part. I was just quickly testing all the features on ARM and must have tried to toggle the first flag that is shown.
