### ISSUE TITLE
format-string-helper doesn't work on ARM thumb

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#80]
In this particular test case, i am checking `vsnprintf`.

I think the reason is that you're setting the breakpoint after the prologue (e.g. `b vsnprintf` instead of `b *vsnprintf`. In my case the arg (r2) is already overwritten.

``` asm
0x00090d3f    <vsnprintf+14>     movs   r2, #144 ; 0x90  <-$pc # Arg overwritten
0x00090d41    <vsnprintf+16>     movs   r1, #0
0x00090d43    <vsnprintf+18>     mov   r7, r3
0x00090d45    <vsnprintf+20>     mov.w   r4, #4294967295
0x00090d49    <vsnprintf+24>     bl   0x9138a <memset> # This is where the bp is set.
```

Because this address (0x90) isn't valid, the BP handler returns false.
The fix is to set the bp at the start of the function, not after the prologue. I'll have to figure out how to do that with a `gdb.Breakpoint`.

**Comment by Grazfather** [comment]
Fixed in 686ced1

**Comment by Grazfather** [comment]
Feel free to cherry-pick the above, since it's on my Arch branch.

**Comment by Grazfather** [comment]
```bash
[+] Possible insecure format string '$r2' -> 0x7ee7d3f0: 'report %x'
[+] Triggered by '*vsnprintf()'
[*] Reason:
Call to '*vsnprintf()' with format string argument in position #2 is in page 0x7ee60000 ([stack]) that has write permission

Breakpoint 3, 0x00090d30 in vsnprintf ()
```

**Comment by hugsy** [comment]
I am surprised, and need to test this further because I used exactly this feature [not long ago](https://blahcat.github.io/2016/03/21/bctf-16-ruin/) and it worked flawlessly.

**Comment by Grazfather** [comment]
It was probably because it was printf and not vnsprintf, or perhaps because this function was thumb mode.

**Comment by hugsy** [comment]
@Grazfather : trying to reproduce, but it's working here (on a Ubuntu ARMv7). Can you attach your C code (or if not, a simplified version of your test case)?

**Comment by Grazfather** [comment]
I'll try to give you a repro-able libc on Monday.

**Comment by hugsy** [comment]
Any update on this ? It makes me curious :laughing:

**Comment by Grazfather** [comment]
I couldn't find a THUMB libc. I can try on the original machine (something at work) to prove it

**Comment by Grazfather** [comment]
Note that this commit was in the arch branch, so it just got merged into master. I still think that's probably correct, but it's less convenient on at least x86, so you might want to revert 686ced1

**Comment by hugsy** [comment]
Oh crap, ok, I'll do that

**Comment by Grazfather** [comment]
I cannot find a goddamn libc.a that's THUMB for the life of me. Even compiling with `-mthumb -static` ends up linking with a non-THUMB _libc.a_ for every compiler I've tried.

I am obviously not making up this issue, but it's clearly not going to come up often, so we can close it. (Though let's revert the change first).

**Comment by hugsy** [comment]
Ok thanks, I'll close for now. If you can manage to get your hands on an example binary, you can re-open and attach it. 
We'll continue for then on.
