### ISSUE TITLE
Variable in install script missing default value 

### ISSUE THREAD

**Issue by sweetyoru** [hugsy/gef#801]
* [ x] Did you use the latest version of GEF from `dev` branch?
* [ x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [ x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [ x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: linux
* Architecture: x86_64
* GEF version (including the Python library version) run `version` in GEF.
GEF: (Standalone)
Blob Hash(/home/[]/.gef-278e84dc8b93c3cb5721d87e05df58b606745e74.py): a77ab224515a2c4a945088767e668585932186cb
SHA1(/home/[]/.gef-278e84dc8b93c3cb5721d87e05df58b606745e74.py): 629bc45f039770cc8389f27243ad57ae62670b5b
GDB: 9.2
GDB-Python: 3.8

### Step 2: Describe your problem

The install script can't run because of missing $wget_found, this will cause syntax error at line 26 when $wget_found is not set.

#### Steps to reproduce

wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh

#### Observed Results

The install script fail.

#### Expected results

gef is installed without error.

**Comment by hugsy** [comment]
Already fixed by https://github.com/hugsy/gef/pull/762
