### ISSUE TITLE
[ppc64] Command 'registers' failed to execute properly, reason: max() arg is an empty sequence

### ISSUE THREAD

**Issue by aik** [hugsy/gef#812]
`registers` does not work with QEMU/powerpc64 - `qemu-system-ppc64 ... -s` when the VM is running. The asm works, breakpoints but not registers.
`target remote localhost:1234` makes gef unable to detect the arch.
`gef-remote --qemu-mode localhost:1234` too as `show architecture` reports `The target architecture is set to "auto" (currently "rs6000:6000").` and `def get_arch() -> str:` fails to parse that the caller does not deal with `rs6000` (ancient powerpc).
Ok, hacked that and now I am getting `[!] Command 'registers' failed to execute properly, reason: [Errno 13] Permission denied: '/proc/1/maps'`.

Does this all mean gef needs more work to support system emulation? https://github.com/cyrus-and/gdb-dashboard supports it and so does bare `gdb`.

**Comment by aik** [comment]
```
gef➤  pi reset_architecture("PowerPC64")
Python Exception <class 'OSError'> Specified arch POWERPC64 is not supported:
Error while executing Python code.
```

**Comment by aik** [comment]
my point was rather why is gef looking at '/proc/1/maps' for qemu-system (it makes sense for qemu-user though), it should use gdb stub in the qemu and get the VM's registers.

**Comment by aik** [comment]
or I just need to avoid `--qemu-mode` and make sure `gef` does not assume qemu at all and work as with any other remote session?

**Comment by hugsy** [comment]
`--qemu-mode` is for qemu-user not qemu-system
if you're using qemu directly you don't need to use `target` , gef works fine even on ppc directly. if you want to use remote, prefer `gef-remote` which is a wrapper around `target` because `target` alone lacks some info we require .

**Comment by aik** [comment]
I do need `target` to connect to the QEMU's GDB stub, I am not debugging QEMU itself, I am debugging the VM running inside it.

**Comment by Noxwizard** [comment]
I've run into the same issue trying to attach to a qemu-system-i386 remote stub.

> if you want to use remote, prefer `gef-remote` which is a wrapper around `target` because `target` alone lacks some info we require .

That doesn't seem to help in this case:
```
gef➤  set arch i386
The target architecture is assumed to be i386
gef➤  gef-remote localhost:1234
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x2ab75146 in ?? ()
[+] Connected to 'localhost:1234'
[+] Remote information loaded to temporary path '/tmp/gef/1'
[!] Command 'gef-remote' failed to execute properly, reason: Not a valid ELF file (magic)
gef➤
```
Then it behaves the same as using `target`, with the register error:
```
[!] Command 'registers' failed to execute properly, reason: max() arg is an empty sequence
```
Running `info registers` does work as expected.

**Comment by hugsy** [comment]
@Noxwizard noted, can you file a proper issue following [the template](https://github.com/hugsy/gef/issues/new?assignees=&labels=triage&template=bug_report.md&title=) then? There's not enough info here to reproduce, so provide a clear step by step. 

Also note that due to the insufficiency intrinsic to the GDB remote protocol (for which there's nothing we can do), I've created [a specific plugin in `gef-extras`](https://github.com/hugsy/gef-extras/blob/dev/scripts/remote.py) to remote connect to GDB using `rpyc`. You might want to give it a try.
