### ISSUE TITLE
module 'keystone' has no attribute 'KS_ARCH_X86'

### ISSUE THREAD

**Issue by o0xmuhe** [hugsy/gef#82]
I have installed ropper with `pip3 install ropper`,and I have installed keystone with source code.
```
gef➤  gef missing 
[*] Command `ropper` is missing, reason  →  module 'keystone' has no attribute 'KS_ARCH_X86'
```
But I got this error,how to fix it?

**Comment by hugsy** [comment]
On Sun, Oct 30, 2016 at 09:31:00PM -0700, o0xmuhe wrote:
> ```
> gef➤  gef missing
> [*] Command `ropper` is missing, reason  →  module 'keystone' has no attribute 'KS_ARCH_X86'
> ```
> I have installed ropper with `pip3 install ropper`.
> But I got this error,how to fix it?
>

This looks like an issue with your keystone installation, not GEF. I would
suggest you to double-check your keystone python3 bindings are fully working on
your computer.

Thanks.
--
hugsy

"Computer science is no more about computers than astronomy is about telescopes." - E. Dijkstra

**Comment by o0xmuhe** [comment]
Thx,I will do it.
