### ISSUE TITLE
ARM: Asm context skips an intruction just before $PC

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#83]
Just noticed this somehow. Looks like you have the same issue, judging by your screen shot in #73 
<img width="698" alt="1__tmux" src="https://cloud.githubusercontent.com/assets/497310/20044085/6dc41eba-a44a-11e6-89ec-c05aa924210b.png">

**Comment by Grazfather** [comment]
I think you just need to remove the `-1` here: https://github.com/hugsy/gef/blob/master/gef.py#L805

**Comment by hugsy** [comment]
![5cafc99cac95677c07c0dd4a043019f886f39812d1000cad884347543829cf55](https://cloud.githubusercontent.com/assets/590234/20112689/a48e3d32-a5ed-11e6-82c3-0d7ed750ffc9.jpg)
