### ISSUE TITLE
Breakpoint commands not entirely working in GEF

### ISSUE THREAD

**Issue by amlamarra** [hugsy/gef#836]
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Ubuntu 20.04
* Architecture: x86_64
* GEF version (including the Python library version) run `version` in GEF.
```
gef➤  version
GEF: (Standalone)
Blob Hash(/home/andrew/.gdbinit-gef.py): 57b691b865c5e4aba3fd706f72c6e6afc5ba0d88
SHA256(/home/andrew/.gdbinit-gef.py): 6fb041276edffe60fe690ad8552ecc516c0f4ff77a21fcaa0e5456224cb91f0e
GDB: 9.2
GDB-Python: 3.8
```

### Step 2: Describe your problem

GDB allows you to execute a set of commands when specific breakpoints are reached. It seems that GEF ignores the `silent` and `continue` commands in this list of commands.

#### Steps to reproduce

1. Set a breakpoint
2. Use the `commands` command to execute a set of commands. For example:
```
$ gdb -q a.out
GEF for linux ready, type `gef' to start, `gef config' to configure
96 commands loaded for GDB 9.2 using Python engine 3.8
Reading symbols from a.out...
(No debugging symbols found in a.out)
gef➤  break *main+15
Breakpoint 1 at 0x1138
gef➤  commands
Type commands for breakpoint(s) 1, one per line.
End with a line saying just "end".
>silent
>i r $rax
>i r $rbx
>cont
>end
gef➤  run
Starting program: /home/andrew/a.out
rax            0x555555555129      0x555555555129
rbx            0x555555555150      0x555555555150
...
    [regular output from the context command]
...
gef➤
```
Context is still shown, even with the `silent` command.
The program does not continue, even with the `cont` command.

#### Minimalist test case

```c
// compile with gcc -fPIE -pic -o my_issue.out my_issue.c
int main(){ return 0; }
```

#### Observed Results

Same results.

#### Expected results

GEF should not show the context and should continue after running the specified commands.

**Comment by amlamarra** [comment]
Understood. But shouldn't the execution automatically continue because of the `continue` command at the end?

**Comment by hugsy** [comment]
> Understood. But shouldn't the execution automatically continue because of the `continue` command at the end?

That's because `context` is executed *after* the `commands` sequence, so the `continue` is already executed. The proper way to set up custom breakpoints with plugins like gef, peda, etc. is to use [`gdb.Breakpoint` Python](https://sourceware.org/gdb/onlinedocs/gdb/Breakpoints-In-Python.html), that  will allow you to continue (or not) execution after the breakpoint is hit (see [the docs](https://sourceware.org/gdb/onlinedocs/gdb/Breakpoints-In-Python.html#index-Breakpoint_002estop)). 

Hope that clarifies.

Cheers,

**Comment by daniellimws** [comment]
@amlamarra I followed what you did. One problem is somehow GDB is confused by `cont` so you should use `continue` or just `c`.

```
gef➤  cont
Ambiguous command "cont": context, continue.
```

That put aside, I think there is some issue with the break commands when GEF is loaded. Check the following asciicasts:

* [GDB with GEF](https://asciinema.org/a/JeoaPunbU0OkfMVaTbYBVz1Q3)
* [Vanilla GDB](https://asciinema.org/a/MQQXb2B9tnomRn5zayMJXhjXm)

Both run the same series of commands but the one with GEF is stuck, while vanilla GDB proceeds nicely. I think there might be a bug that we have to look into.

@amlamarra You can refer to the following code on GDB breakpoints in Python.
https://github.com/hugsy/gef/blob/7f45550ea610a832817edc8cc18248deea90cf59/gef.py#L4149-L4195

But yes you would need to implement a command that uses this custom breakpoint, which might be too much work for a simple task.
https://github.com/hugsy/gef/blob/7f45550ea610a832817edc8cc18248deea90cf59/gef.py#L6551-L6571

I can investigate more into this problem when I'm free or maybe someone else will look into it before me.

**Comment by hugsy** [comment]
Closing for housecleaning
