### ISSUE TITLE
Add support for SIMD registers

### ISSUE THREAD

**Issue by B14CK313** [hugsy/gef#837]
**Is your feature request related to a problem? Please describe.**
`gef` doesn't seem to support SIMD registers like $xmm0 (SSE).

**Describe the solution you'd like**
It would be great if support for SIMD registers could be added to `gef` to make it easier to debug functions with floating point instructions. The standard `gdb` commands (e.g. `info reg xmm0`) are just too verbose, and it's tedious to keep track of these registers by using `i r <register>` repeatedly. It would be much easier if you could use a custom context pane for this, but I can't find a way to retrieve the value of these registers in `gef,` because `get_register("$xmm0")` returns `None`.

Trying to display SSE registers using a custom context pane and below the annoyingly verbose output of the inbuilt `gdb` command:
![image](https://user-images.githubusercontent.com/22134010/170823257-89ffac0d-d9cd-493f-962e-0df59db5183c.png)

_Thank you for creating and maintaining this great project!_

**Comment by hugsy** [comment]
👋 

Glad you enjoy the project.

Regarding your question, I considered it but AFAIK there's no programmatic way to handle SSE registers from the Python API. 

For example:
```
pi gdb.selected_frame().read_register("xmm0")
```

Returns `gdb.Value` as expected, but I cannot find a way to handle it as integer instead. I must say I didn't spend too long on it, so if you happen to know (or find) a way post it here and yeah, SSE regs can be added then.

Cheers,

**Comment by hugsy** [comment]
Actually I just noticed it works fine when it's cast as an array:

```
gef➤  pi for i in range(2): print(int(gdb.parse_and_eval("$xmm0").cast( gdb.lookup_type("uint64_t").array(1))[i]))
0
0
```
