### ISSUE TITLE
Feature request: Work without ELF

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#84]
e.g. think jtagging with OpenOCD.

Right now some functionality works, and some we can't expect to work (e.g. vmmap) but some like telescope would be fanstatic.

**Comment by Grazfather** [comment]
Would also be nice for things like `avr-gdb` (One could write a new arch rather easily once my arch code is merged in).

This would require a way to set the arch in gef without needing to parse it from the elf header.

**Comment by Grazfather** [comment]
Just a note: You get a good way there just by setting `current_elf = Elf()`, which has sensible defaults.

`get_memory_alignment` can also check the type of `$pc` as long as the target is running.

**Comment by Grazfather** [comment]
So this is a classic problem with GDB (in terms of understanding).

There are basically four things that can change around:

Arch: e.g. x86, ARM
Host OS: e.g. linux, osx
Host arch
ELF/PE/Mach-o

I think we handle 'arch' pretty well: There's a class (really an interface) that supported architectures can implement.

For ELF/PE/Mach-o, it's more hacked it. Functions that do elf-specific things have to add support for mach o by first checking if it's mach-o. Adding PE would require the same.

I think that we should handle this by copying the Arch approach: Implement a base class/interface, and move the ELF-specific stuff into an ELF class, and MachO into it's own as well. Then things that are specific to these container types will be implemented by the appropriate class.

instead of
```python
def checksec(file):
    if is_macho(file): return checksec_macho(file)

    ...<checksec elf>
```

it would be

```python
def checksec(file):
    return current_binary.checksec()
```

Unfortunately it means keeping more state (current arch, current binary, etc) but I think it's worth the effort.

**Comment by hugsy** [comment]
I think it'll be safe to close this (5 year old) issue when #779 is merged because:
 - it introduces a new class `GenericArchitecture` which is the default
 - it should allow for other format support (PE & Mach-O) from `gef-extras` as long as those external format scripts are loaded from the gdbinit (i.e. before `new_objfile` signal is thrown)

**Comment by hugsy** [comment]
#779 is merged
