### ISSUE TITLE
Install script broken by branch rename

### ISSUE THREAD

**Issue by Scoder12** [hugsy/gef#847]
* N/A Did you use the latest version of GEF from `dev` branch?
* N/A Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you search through the [documentation](https://github.com/hugsy/gef/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

N/A

### Step 2: Describe your problem

https://gef.blah.cat/sh defaults to `branch=master`

#### Steps to reproduce

```
❯ curl --silent https://api.github.com/repos/hugsy/gef/git/ref/heads/master
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/git#get-a-reference"
}
```

**Comment by hugsy** [comment]
This will be fixed this weekend with the next release. For now feel free to edit the script manually or switch to the `dev` branch.
