### ISSUE TITLE
Massive documentation re-work

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#86]
With the too many requests I have regarding `gef` install or usage, I need to make more documentation. 

Idea list:

   * [x] Exhaustive description of commands and options
   * [x] One documentation file per command
   * [x] Write-up a quick FAQ for frequent install error/warning messages (ex: Python support not compiled, wrong Python version, etc.)  
  * [x] Add a PEDA compatibility page to show how to find an equivalent for the commands in PEDA
  * [x] Video tutorials for install __and__ command use (https://www.youtube.com/playlist?list=PLjAuO31Rg972WeMvdR_57Qu-aVM8T6DkQ)
  * [x] Provide ready-to-use environment for testing (https://blahcat.github.io/2017/06/25/qemu-images-to-play-with/)

**Comment by hugsy** [comment]
Add a PEDA compatibility page to show how to find an equivalent for the commands in PEDA

**Comment by shahril96** [comment]
@hugsy I just want to say thanks for the work you have spent on the documentation, and most importantly, to the project itself! I migrated from pwndbg to gef because of the documentation and the interface looks much more slick & beautiful. Thanks! :smile:

**Comment by hugsy** [comment]
Related to #161 : make the doc clearer that GEF need a locale of `en_*.UTF-8` (not just UTF-8)

**Comment by hugsy** [comment]
Tutorial screencasts will be publicly released after Black Hat Arsenal.
