### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pi0projects** [hugsy/gef#879]
### GEF+GDB version

2022.06 GEF version and GDB 12.1

### Operating System

Ubuntu 22.04

### Describe the issue you encountered

/home/default/.gdbinit:1: Error in sourced command file:
~/.gef-2b72f5d0d9f0f218a91cd1ca5148e45923b950d5.py:52: Error in sourced command file:
Undefined command: "import".  Try "help".

### How can the issue be reproduced?

I attempted to install gef per the instructions on the site, running the following command
bash -c "$(curl -fsSL https://gef.blah.cat/sh)". Unfortunately gef did not properly install.

### Architecture impacted

- [X] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue

Provide a step-by-step to reproduce your issue.
I simply ran bash -c "$(curl -fsSL https://gef.blah.cat/sh)" on a freshly compiled version of gdb 12.1

### Minimalist test case

Use this field for a minimal code to compile and spot the issue:
```c
// compile with gcc -fPIE -pic -o my_issue.out my_issue.c
int main(){ return 0; }
```
You can also provide a Dockerfile if you prefer

### Additional context?

- Screenshots
- [https://i.imgur.com/BkcLWgV.png](url)
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by hugsy** [comment]
Your GDB is not compiled with Python support. This is not a problem with GEF
