### ISSUE TITLE
Installing ropgadget in a virtualenv don't work

### ISSUE THREAD

**Issue by dummys** [hugsy/gef#88]
Hi,

I'm trying to use your tool with ropgadget in a virtualenv and it's not working.
I'm on arch linux, I installed with pip3 install ropgadget.
In the Venv I can do ipython and import ropgadget without problem.
My gdb is compiled with python3.
How can I help you to debug ?

**Comment by hugsy** [comment]
Not sure how to help you with that. You should look for a way to force GDB into your Venv... but this is not a `gef` issue.

**Comment by dummys** [comment]
gdb doesn't use the venv if it is activated ?

**Comment by hugsy** [comment]
Dunno, never used it like this...

**Comment by dummys** [comment]
ok, the idea of using a venv, it's to not polute the computer with python package...
So you install all the package with pip ?

**Comment by hugsy** [comment]
My bad... I meant, I know VirtualEnv but I've never used it with GDB. So yes, all the packages were installed directly using `pip` (no venv).

**Comment by Grazfather** [comment]
@dummys yes VirtualEnvs are nice but they don't play nice with GDB since GDB imports it own `gdb` package and it unaware of the existence of virtualenvs.

You might be able to 'hack it in' by _prepending_ `sys.path` with the path of your venv in _.gdbinit_, but this is a hack.
