### ISSUE TITLE
[Bug] Kali cant use gef

### ISSUE THREAD

**Issue by iiipod** [hugsy/gef#883]
### GEF+GDB version

GEF: rev:2830670a9b0ff3ab73c3da8ec1451a6256a24cef (Git - clean)
SHA256(/home/do/tools/gef/gef.py): 451bc37b640d39692931b884c6ec021666a22715b7912993596267c7bd930977
GDB: 12.1
GDB-Python: 3.10

### Operating System

Kali GNU/Linux Rolling 
Release:	2022.3 

### Describe the issue you encountered

gdb -q 
gef>start
return only gef>
looks like had executed reset or clear command, can not seen output content, people who debug the file must move your mouse.

### How can the issue be reproduced?

gdb -q 
gef>start

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue

Provide a step-by-step to reproduce your issue.
$ gdb -q 
gef> start
return only gef>
looks like had executed reset or clear command 

### Minimalist test case

Use this field for a minimal code to compile and spot the issue:
```c
// compile with gcc -fPIE -pic -o my_issue.out my_issue.c
int main(){ return 0; }
```
You can also provide a Dockerfile if you prefer

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by hugsy** [comment]
Please read the documentation thoroughly and/or ask questions on the discord. This is not a bug
