### ISSUE TITLE
[Bug] Registers layout display failed when I remote a riscv target

### ISSUE THREAD

**Issue by Squirre17** [hugsy/gef#884]
### GEF+GDB version

gef➤  version
GEF: rev:b4bffdc4a1aca35dc83756b3c59f17de114a1710 (Git - dirty)
SHA256(/home/squ/tools/gef/gef.py): 19c8e13b68663c19a39d985a42b5db50c954e7a722eee4f8ec304216e6ceafb8
GDB: 9.2
GDB-Python: 3.8

### Operating System

Ubuntu 20.04.3 LTS

### Describe the issue you encountered

I want to cross compile a riscv target and debug it with qemu and gef in my Ubuntu
but default registers layout can't display and caused a error message like following
"[!] Command 'registers' failed to execute properly, reason: max() arg is an empty sequence"

![image](https://user-images.githubusercontent.com/79578430/185408470-8a32a363-9154-41ff-b7dc-a39a872db56f.png)

### How can the issue be reproduced?

1. cross compile a riscv target with any content
```c
// riscv64-unknown-elf-gcc -g -O0 main.c
int main(){
        int a=1, b=2,c;
        c = a + b;
        return 0;
}
```

2. execute it with qemu and waiting for debugger connect
```shell
qemu-riscv64 -g 1234 ./a.out
```
3. launch gdb-multiarch 
```shell
set arch riscv
file a.out
target remote 1234
```

and finally can see the error message

### Architecture impacted

- [ ] X86
- [ ] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [X] RISCV

### Describe your issue

1. cross compile a riscv target with any content
```c
// riscv64-unknown-elf-gcc -g -O0 main.c
int main(){
        int a=1, b=2,c;
        c = a + b;
        return 0;
}
```

2. execute it with qemu and waiting for debugger connect
```shell
qemu-riscv64 -g 1234 ./a.out
```
3. launch gdb-multiarch 
```shell
set arch riscv
file a.out
target remote 1234
```

and finally can see the error message

### Minimalist test case

```c
// riscv64-unknown-elf-gcc -g -O0 main.c
int main(){ return 0; }
```

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by hugsy** [comment]
What if you use `gef-remote` instead of `target`?

**Comment by Squirre17** [comment]
> What if you use `gef-remote` instead of `target`?

I try to do what you said, but another error came up
```
[!] Command 'gef-remote' failed to execute properly, reason: CPU type is currently not supported: riscv:rv64
```
![image](https://user-images.githubusercontent.com/79578430/185522730-faf4eeef-06a8-4911-a603-d71a3c94a8b8.png)

**Comment by hugsy** [comment]
The version you're using [is too old](https://github.com/hugsy/gef/commit/b4bffdc4a1aca35dc83756b3c59f17de114a1710). Try again with a more recent

**Comment by Squirre17** [comment]
I have updated gef according to your docs
![image](https://user-images.githubusercontent.com/79578430/185537658-ca0adf68-2e22-46f0-bfb0-01d4f085ecd8.png)
and other error came up, seems like it try to access 'init' process address space...... I don't affirm if this error comes from qemu or gef...
![image](https://user-images.githubusercontent.com/79578430/185537785-4045b7c0-d902-4737-bca3-b182c183ed8a.png)

**Comment by Squirre17** [comment]
solved by discord channel. 🥰
```shell
gef-remote --qemu-user --qemu-binary ./target localhost 4444
```
--qemu-user also apply to qemu-system emulate
![image](https://user-images.githubusercontent.com/79578430/187816280-4c818a9c-1d03-4bb5-ba53-46e7bf680f0c.png)

**Comment by hugsy** [comment]
For reference, it's all in the docs: https://hugsy.github.io/gef/commands/gef-remote/#qemu-user
