### ISSUE TITLE
“Registers” can't use 

### ISSUE THREAD

**Issue by 16ea** [hugsy/gef#885]
### GEF+GDB version

gef➤  version
GEF: (Standalone)
Blob Hash(/home/eeee/.gef-2b72f5d0d9f0f218a91cd1ca5148e45923b950d5.py): 8dc57b700e3c1c85822449033a01c94dfae9e4a6
SHA256(/home/eeee/.gef-2b72f5d0d9f0f218a91cd1ca5148e45923b950d5.py): 63d3e10d38a367c3e4d37de8e0701bcdff2a4e7c9a0a4ec5d83ccb8b2fe6188d
GDB: 9.2
GDB-Python: 3.8

### Operating System

Ubuntu 20.04.4 LTS

### Describe the issue you encountered

First,i use "./qemu-riscv64 -g 1234 ./target" in a terminal;
then i use "gdb-multiarch ./target" in another terminal, and input "target remote localhost:1234"
then i find 
[!] Command 'registers' failed to execute properly, reason: [Errno 13] Permission denied: '/proc/1/maps'
─────────────────────────────────────────────────────────────────────────────────── stack ────
[!] Command 'dereference' failed to execute properly, reason: [Errno 13] Permission denied: '/proc/1/maps'
and i can't use registers command, can't look registers messages,can't look stack messages
<img width="898" alt="iShot_2022-08-22_22 48 49" src="https://user-images.githubusercontent.com/85932203/185952750-47cda850-2f15-4522-9831-55c88ee6aab2.png">

### How can the issue be reproduced?

<img width="456" alt="1" src="https://user-images.githubusercontent.com/85932203/185953653-fad39505-fa9d-43b5-94da-058a0c48b3d0.png">
<img width="903" alt="2" src="https://user-images.githubusercontent.com/85932203/185953669-81d5ae87-4337-4c3d-8df3-512af0111122.png">
<img width="919" alt="3" src="https://user-images.githubusercontent.com/85932203/185953687-e0109af9-7e0d-4e09-bcec-06404ce8e93c.png">

### Architecture impacted

- [ ] X86
- [ ] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [X] RISCV

### Describe your issue

Provide a step-by-step to reproduce your issue.

### Minimalist test case

[src.zip](https://github.com/hugsy/gef/files/9395424/src.zip)

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by Grazfather** [comment]
Please read the manual. You need to use `gef remote` not `target remote`

**Comment by 16ea** [comment]
it occurs 

"gef➤  gef-remote 127.0.0.1:9000
[!] Missing parameters
"

**Comment by hugsy** [comment]
This is not a bug with GEF. Please read thoroughly the manual, if you have extra questions, ask them on the Discord.

**Comment by hugsy** [comment]
Solution in the docs.
This is also a dup of #884 [solved]

**Comment by 16ea** [comment]
gef-remote --qemu-user --qemu-binary ./a localhost 4444 即可解决
