### ISSUE TITLE
[Bug] 'registers' failed to execute properly

### ISSUE THREAD

**Issue by v0lp3** [hugsy/gef#886]
### GEF+GDB version

GEF: (Standalone)
Blob Hash(/home/v0lp3/.gdbinit-gef.py): ef5d12df13a2abaefce20b4cdfe4b23e3e314898
SHA256(/home/v0lp3/.gdbinit-gef.py): 451bc37b640d39692931b884c6ec021666a22715b7912993596267c7bd930977
GDB: 12.1
GDB-Python: 3.10

### Operating System

Arch Linux

### Describe the issue you encountered

There are two issues:

If I try to attach to a remote session with: 
`target remote <ip>:<port>`

Gef fails to show registers value because it raise the error:

`[!] Command 'registers' failed to execute properly, reason: max() arg is an empty sequence`

Otherwise if i try to attach to a remote session with the command:

`gef-remote <ip> <port>`

I get the error:

`[!] Command 'gef-remote' failed to execute properly, reason: Unknown remote I/O error 0`

### Architecture impacted

- [ ] X86
- [ ] X64
- [ ] ARM
- [ ] ARM64
- [X] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

**Comment by hugsy** [comment]
1. Search for existing closed issues
2. Do not use `target remote`, only use `gef-remote`
3. There's no steps for us to try to reproduce
