### ISSUE TITLE
[Bug] 'checksec' is deprecated

### ISSUE THREAD

**Issue by CaledoniaProject** [hugsy/gef#887]
### GEF+GDB version

```shell
gef➤  version
GEF: (Standalone)
Blob Hash(/root/.gdbinit-gef.py): 8dc57b700e3c1c85822449033a01c94dfae9e4a6
SHA256(/root/.gdbinit-gef.py): 63d3e10d38a367c3e4d37de8e0701bcdff2a4e7c9a0a4ec5d83ccb8b2fe6188d
GDB: 9.2
GDB-Python: 3.8
```

### Operating System

Ubuntu 22.04

### Describe the issue you encountered

I don't like the warnings:

```
[*] .gdbinit-gef.py:L8764 'checksec' is deprecated and will be removed in a feature release. Use Elf(fname).checksec()
```

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [X] X86
- [ ] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Open a 32bit program and run checksec

### Minimalist test case

I think this part is irrevalent

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by Grazfather** [comment]
Thanks. Filed #888 to fix it.
