### ISSUE TITLE
Feature Request: Show registers changed between context prints

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#89]
Basically keep track of the registers on the last print, when printing them anew, highlight those that have changed.

**Comment by hugsy** [comment]
Good idea, that's easy using [`events.register_changed`](https://sourceware.org/gdb/onlinedocs/gdb/Events-In-Python.html). Just need to make sure of the backward compat ...

**Comment by hugsy** [comment]
Fixed by 4097e1
![](https://i.imgur.com/RKoROru.png)
