### ISSUE TITLE
Need a method to get memory permission for a specific address

### ISSUE THREAD

**Issue by CaledoniaProject** [hugsy/gef#890]
### Type of feature request

Additional API

### Summary Description

Giving an address or a variable, I would like to know if the address is writable/executable etc.

Right now I had to do a `vmmap`, then find the region that the address resides.

### Implementation idea/suggestion

Not sure how to do that with gdb python, maybe take a look at here: https://sourceware.org/gdb/onlinedocs/gdb/Memory-Region-Attributes.html

**Comment by hugsy** [comment]
Like `xinfo` ?

**Comment by CaledoniaProject** [comment]
That worked great for me
