### ISSUE TITLE
Rust backtrace is overloaded

### ISSUE THREAD

**Issue by SWW13** [hugsy/gef#895]
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/usr/share/gef/gef.py): 0765cc54d350b332ddafb2d71d20ae6aea221006
SHA256(/usr/share/gef/gef.py): 631dd3d83a8797a0b53b2267097c100b28f01868d7ba131730340f22994c272c
GDB: 12.1
GDB-Python: 3.10
```

### Operating System

Arch Linux

### Describe the issue you encountered

When debugging a Rust binary the full composition of a structs in the arguments are printed. This can lead to hundreds of lines in the backtrace.

In contrast gdb `bt` shortens the struct definition in prints a short backtrace.
(Not sure if this is considered a bug or a feature request, but as it makes the `trace` option in context useless for Rust binaries I went for bug report.)

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [ ] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

```
$ cargo init --bin
$ $EDITOR src/main.rs
$ cargo build
$ gdb target/debug/example
gef> b main
gef> start
gef> c
gef> c
gef> step
[...]
```

### Minimalist test case

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6007ffab7f8000faf486d3f7e17041c8

```Rust
fn main() {
    let path = std::path::PathBuf::from("/path");
    println!("{:?}", path);
}
```

### Additional context?

Simple example for `Path::from` with an expanded `OsString` struct:

```
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, Name: "example", stopped 0x55555555c927 in std::path::{impl#37}::from (), reason: SINGLE STEP
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
[#0] 0x55555555c927 → std::path::{impl#37}::from(s=std::ffi::os_str::OsString {
  inner: std::sys::unix::os_str::Buf {
    inner: alloc::vec::Vec<u8, alloc::alloc::Global> {
      buf: alloc::raw_vec::RawVec<u8, alloc::alloc::Global> {
        ptr: core::ptr::unique::Unique<u8> {
          pointer: core::ptr::non_null::NonNull<u8> {
            pointer: 0x5555555a4aa0
          },
          _marker: core::marker::PhantomData<u8>
        },
        cap: 0x5,
        alloc: alloc::alloc::Global
      },
      len: 0x5
    }
  }
})
[#1] 0x55555555c712 → std::path::{impl#36}::from<str>(s="/path")
[#2] 0x55555555c0fa → example::main()
```

```
gef➤  bt
#0  std::path::{impl#37}::from (s=...) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/path.rs:1654
#1  0x000055555555c712 in std::path::{impl#36}::from<str> (s=...) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/path.rs:1643
#2  0x000055555555c0fa in example::main () at src/main.rs:2
```

**Comment by hugsy** [comment]
Hi @SWW13 

> In contrast gdb bt shortens the struct definition in prints a short backtrace.
> (Not sure if this is considered a bug or a feature request, but as it makes the trace option in context useless for Rust binaries I went for bug report.)

This counts more as a user preference optimization, not really a bug: you can edit the default `context` layout not to show the `trace` and replace it with the output of `bt` if that's what you prefer (see [the docs](https://hugsy.github.io/gef/commands/context/#adding-custom-context-panes)).

Cheers

**Comment by theguy147** [comment]
@SWW13 Did you manage to resolve your issue/customization?

For further clarification, this is how you could achieve your goal:

```py
# filename: custom_context_pane.py 

def backtrace():
  gef_print(gdb.execute("bt", to_string=True))

register_external_context_pane("gdb_bt", backtrace, lambda: "trace")
```

Then you can remove the long trace from the context with this command (while running gef):

`gef config context.layout "legend regs stack code args source memory threads extra"`

Note, that the string does not contain the `trace` element which it does by default.

And now to activate your custom pane, execute:

`source /path/to/custom_context_pane.py`

Now you get to see GDBs default `bt` command on every breakpoint without having to manually trigger it every time and you won't be bothered by the more verbose `gef` backtrace.
