### ISSUE TITLE
[Bug] gef has unwarp every members in Structural parameter in backtrace

### ISSUE THREAD

**Issue by CppXL** [hugsy/gef#925]
### GEF+GDB version

```shell
GEF: (Standalone)
Blob Hash(/root/.gef-283690ae9bfcecbb3deb80cd275d327c46b276b5.py): 83861546049c4c1130503dd0acb802fc8383aa45
SHA256(/root/.gef-283690ae9bfcecbb3deb80cd275d327c46b276b5.py): a6b9698cdb06eefeb0a2b6ce9d31e706e75e151b4006be8d90cdcaf7f9afa1f1
GDB: 9.2
GDB-Python: 3.8
```

### Operating System

ubuntu 2004

### Describe the issue you encountered

when I use gdb with gef debug `OpenImageIO` library, gef has unwarp every members in Structural parameter in backtrace, but when I use `bt` command, It was normal in output.
`gef` output
![](https://i.imgur.com/3bOflXp.png)
`bt` command output
![](https://i.imgur.com/aGhBVov.png)

### Do you read the docs and look at previously closed issues/PRs for similar cases?

No

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Provide a step-by-step to reproduce your issue.
1. use gdb with gef debug `libOpenImageIO` with debug symbol info
2. run program, gef will unwarp every members in Structural in backtrace

### Minimalist test case

Use this field for a minimal code to compile and spot the issue:
```c
#include "include/OpenImageIO/imagebuf.h"
// #include "include/OpenImageIO/imageio.h"
#include <iostream>
using namespace OIIO;
int main(int, char **) {
  auto buf = ImageBuf("/root/oiiovuln/1.psd");
  for (auto layer = 0; layer < buf.nsubimages(); layer++) {
    // buf.reset("/root/oiiovuln/1.psd", layer);

    std::cout << buf.ymax() << std::endl;
  }
  //   auto sf = OpenImageIO_v2_3::ImageBuf("/root/oiiovuln/1.psd");
  return 0;
}

```
You can also provide a Dockerfile if you prefer

### Additional context?

- Screenshots
- Callstack
- Coredumps
- If possible and useful, please upload the binary

**Comment by hugsy** [comment]
Closing as it is not an issue: some people prefer expanding everything, some don't.
You can edit the context layout using `gef config context.layout` and customize to your own preference (for example just calling `bt`).
